In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\North Carolina\Cabarrus\Property\clean\us_nc_37025_data_prop_building_silver_20251127.csv")
df

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,page_save
0,46706951200000,1,2007,2007,2567.0,1485.0,4052,410020.0,NaN,10734 WAYCROSS DR HUNTERSVILLE,01,1,83.0,185.22,494005.0,46706951200000.html
1,46706963260000,1,2005,2005,3400.0,937.0,4337,509330.0,NaN,10445 SPRING TREE LN HUNTERSVILLE,01,1,81.0,176.40,628800.0,46706963260000.html
2,46707245420000,1,2007,2012,2032.0,699.0,2731,283750.0,NaN,8654 BROOKINGS DR CHARLOTTE,09,1,88.0,151.96,322440.0,46707245420000.html
3,46706990940000,1,2006,2006,3204.0,840.0,4044,509870.0,NaN,712 MERCER PL HUNTERSVILLE,01,1,82.0,187.74,621792.0,46706990940000.html
4,46707260670000,1,2005,2010,1712.0,660.0,2372,282800.0,NaN,8543 BROOKINGS DR CHARLOTTE,09,1,86.0,183.28,328838.0,46707260670000.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82769,66021043140000,1,2023,2023,1279.0,1089.0,2368,250060.0,NaN,2100 GOLD HILL RD E GOLD HILL,01R,1,99.0,158.76,252587.0,66021043140000.html
82770,66023336930000,1,2022,2022,2791.0,1420.0,4211,506870.0,NaN,NaN,01R,1,98.0,167.58,517210.0,66023336930000.html
82771,56610145570000,1,1980,1985,1166.0,882.0,2048,165460.0,NaN,380 ST JOHNS CHURCH RD CONCORD,01R,1,61.0,182.70,271252.0,56610145570000.html
82772,66031133160000,1,1976,1981,1268.0,1130.0,2398,39450.0,NaN,4201 GOLD HILL RD E GOLD HILL,03,2,30.0,77.70,131493.0,66031133160000.html
82773,66020121510000,1,2006,2006,3420.0,1110.0,4530,165170.0,NaN,2245 GOLD HILL RD E MT PLEASANT,49,6,40.0,88.80,412920.0,66020121510000.html

In [3]:
df1 = pd.read_csv(r"D:\North Carolina\Cabarrus\Property\clean\us_nc_37025_data_prop_building-use-model_silver_20251127.csv")
pd.set_option('display.max_columns', None)
df1

,parcel_number,use_code_description,model_description,page_save
0,46707245420000,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,46707245420000.html
1,46706990940000,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,46706990940000.html
2,46707338740000,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,46707338740000.html
3,46706963260000,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,46706963260000.html
4,46707357690000,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,46707357690000.html
...,...,...,...,...
82769,66031133160000,03 - MANU HOME (SINGLE WIDE),02 - MANUFACTURED HOME,66031133160000.html
82770,56612615580000,01R - SINGLE FAMILY RURAL,01 - SINGLE FAMILY HOME,56612615580000.html
82771,56617851540000,02 - MANU HM (MULTI SECTIONAL),02 - MANUFACTURED HOME,56617851540000.html
82772,56937648340000,01R - SINGLE FAMILY RURAL,01 - SINGLE FAMILY HOME,56937648340000.html
82773,56914809170000,03 - MANU HOME (SINGLE WIDE),02 - MANUFACTURED HOME,56914809170000.html

In [4]:
merged_df = pd.merge(
    df,
    df1,
    on=["parcel_number", "page_save"],  # common keys
    how="inner"                          # inner, left, right, outer
)
cols = [c for c in merged_df.columns if c != "page_save"] + ["page_save"]
merged_df = merged_df[cols]
merged_df.to_csv(r"D:\North Carolina\Cabarrus\Property\clean\merged.csv", index=False)

In [5]:
merged_df

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,page_save
0,46706951200000,1,2007,2007,2567.0,1485.0,4052,410020.0,NaN,10734 WAYCROSS DR HUNTERSVILLE,01,1,83.0,185.22,494005.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,46706951200000.html
1,46706963260000,1,2005,2005,3400.0,937.0,4337,509330.0,NaN,10445 SPRING TREE LN HUNTERSVILLE,01,1,81.0,176.40,628800.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,46706963260000.html
2,46707245420000,1,2007,2012,2032.0,699.0,2731,283750.0,NaN,8654 BROOKINGS DR CHARLOTTE,09,1,88.0,151.96,322440.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,46707245420000.html
3,46706990940000,1,2006,2006,3204.0,840.0,4044,509870.0,NaN,712 MERCER PL HUNTERSVILLE,01,1,82.0,187.74,621792.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,46706990940000.html
4,46707260670000,1,2005,2010,1712.0,660.0,2372,282800.0,NaN,8543 BROOKINGS DR CHARLOTTE,09,1,86.0,183.28,328838.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,46707260670000.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82769,66021043140000,1,2023,2023,1279.0,1089.0,2368,250060.0,NaN,2100 GOLD HILL RD E GOLD HILL,01R,1,99.0,158.76,252587.0,01R - SINGLE FAMILY RURAL,01 - SINGLE FAMILY HOME,66021043140000.html
82770,66023336930000,1,2022,2022,2791.0,1420.0,4211,506870.0,NaN,NaN,01R,1,98.0,167.58,517210.0,01R - SINGLE FAMILY RURAL,01 - SINGLE FAMILY HOME,66023336930000.html
82771,56610145570000,1,1980,1985,1166.0,882.0,2048,165460.0,NaN,380 ST JOHNS CHURCH RD CONCORD,01R,1,61.0,182.70,271252.0,01R - SINGLE FAMILY RURAL,01 - SINGLE FAMILY HOME,56610145570000.html
82772,66031133160000,1,1976,1981,1268.0,1130.0,2398,39450.0,NaN,4201 GOLD HILL RD E GOLD HILL,03,2,30.0,77.70,131493.0,03 - MANU HOME (SINGLE WIDE),02 - MANUFACTURED HOME,66031133160000.html
82773,66020121510000,1,2006,2006,3420.0,1110.0,4530,165170.0,NaN,2245 GOLD HILL RD E MT PLEASANT,49,6,40.0,88.80,412920.0,49 - WAREHOUSE - PREFAB,06 - WAREHOUSE/INDUSTRIAL,66020121510000.html

In [6]:
df2 = pd.read_csv(r"D:\North Carolina\Cabarrus\Property\clean\us_nc_37025_data_prop_building-adjustment_silver_20251127.csv")
pd.set_option('display.max_columns', None)
df2

,parcel_number,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,page_save
0,46706990940000,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,46706990940000.html
1,46706951200000,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.98,NaN,NaN,NaN,NaN,NaN,46706951200000.html
2,46706963260000,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,46706963260000.html
3,46707245420000,3,CB,Average,2024,1.00,6,CB,MF6,2024,1.15,Size,CB,Size,2024.0,1.00,NaN,NaN,NaN,NaN,NaN,46707245420000.html
4,46707318010000,4,CB,Above Average,2024,1.10,5,CB,MF5,2024,1.10,Size,CB,Size,2024.0,1.10,NaN,NaN,NaN,NaN,NaN,46707318010000.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82769,56936649440000,4,CB,Above Average,2024,1.10,4,CB,MF4,2024,1.05,Size,CB,Size,2024.0,0.98,NaN,NaN,NaN,NaN,NaN,56936649440000.html
82770,66023336930000,4,CB,Above Average,2024,1.10,4,CB,MF4,2024,1.05,Size,CB,Size,2024.0,0.97,NaN,NaN,NaN,NaN,NaN,66023336930000.html
82771,56914809170000,2,CB,Below Average,2024,0.90,4,CB,MF4,2024,1.04,Size,CB,Size,2024.0,1.06,NaN,NaN,NaN,NaN,NaN,56914809170000.html
82772,66021043140000,2,CB,Below Average,2024,0.90,4,CB,MF4,2024,1.05,Size,CB,Size,2024.0,1.38,NaN,NaN,NaN,NaN,NaN,66021043140000.html
82773,66020121510000,3,CB,Average,2024,1.00,4,CB,MF4,2024,1.04,Size,CB,Size,2024.0,1.19,20.0,CB,Non-Std Wall Height,2024.0,1.13,66020121510000.html

In [7]:
merged_df = pd.merge(
    merged_df,
    df2,
    on=["parcel_number", "page_save"],
    how="inner"
)

# move page_save to last column
cols = [c for c in merged_df.columns if c != "page_save"] + ["page_save"]
merged_df = merged_df[cols]

merged_df.to_csv(r"D:\North Carolina\Cabarrus\Property\clean\merged.csv", index=False)

In [8]:
merged_df

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,page_save
0,46706951200000,1,2007,2007,2567.0,1485.0,4052,410020.0,NaN,10734 WAYCROSS DR HUNTERSVILLE,01,1,83.0,185.22,494005.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.98,NaN,NaN,NaN,NaN,NaN,46706951200000.html
1,46706963260000,1,2005,2005,3400.0,937.0,4337,509330.0,NaN,10445 SPRING TREE LN HUNTERSVILLE,01,1,81.0,176.40,628800.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,46706963260000.html
2,46707245420000,1,2007,2012,2032.0,699.0,2731,283750.0,NaN,8654 BROOKINGS DR CHARLOTTE,09,1,88.0,151.96,322440.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.00,6,CB,MF6,2024,1.15,Size,CB,Size,2024.0,1.00,NaN,NaN,NaN,NaN,NaN,46707245420000.html
3,46706990940000,1,2006,2006,3204.0,840.0,4044,509870.0,NaN,712 MERCER PL HUNTERSVILLE,01,1,82.0,187.74,621792.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,46706990940000.html
4,46707260670000,1,2005,2010,1712.0,660.0,2372,282800.0,NaN,8543 BROOKINGS DR CHARLOTTE,09,1,86.0,183.28,328838.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.00,6,CB,MF6,2024,1.15,Size,CB,Size,2024.0,1.15,NaN,NaN,NaN,NaN,NaN,46707260670000.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82769,66021043140000,1,2023,2023,1279.0,1089.0,2368,250060.0,NaN,2100 GOLD HILL RD E GOLD HILL,01R,1,99.0,158.76,252587.0,01R - SINGLE FAMILY RURAL,01 - SINGLE FAMILY HOME,2,CB,Below Average,2024,0.90,4,CB,MF4,2024,1.05,Size,CB,Size,2024.0,1.38,NaN,NaN,NaN,NaN,NaN,66021043140000.html
82770,66023336930000,1,2022,2022,2791.0,1420.0,4211,506870.0,NaN,NaN,01R,1,98.0,167.58,517210.0,01R - SINGLE FAMILY RURAL,01 - SINGLE FAMILY HOME,4,CB,Above Average,2024,1.10,4,CB,MF4,2024,1.05,Size,CB,Size,2024.0,0.97,NaN,NaN,NaN,NaN,NaN,66023336930000.html
82771,56610145570000,1,1980,1985,1166.0,882.0,2048,165460.0,NaN,380 ST JOHNS CHURCH RD CONCORD,01R,1,61.0,182.70,271252.0,01R - SINGLE FAMILY RURAL,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.00,3,CB,MF3,2024,1.00,Size,CB,Size,2024.0,1.42,NaN,NaN,NaN,NaN,NaN,56610145570000.html
82772,66031133160000,1,1976,1981,1268.0,1130.0,2398,39450.0,NaN,4201 GOLD HILL RD E GOLD HILL,03,2,30.0,77.70,131493.0,03 - MANU HOME (SINGLE WIDE),02 - MANUFACTURED HOME,1,CB,Minimum,2024,0.75,4,CB,MF4,2024,1.04,Size,CB,Size,2024.0,0.98,NaN,NaN,NaN,NaN,NaN,66031133160000.html
82773,66020121510000,1,2006,2006,3420.0,1110.0,4530,165170.0,NaN,2245 GOLD HILL RD E MT PLEASANT,49,6,40.0,88.80,412920.0,49 - WAREHOUSE - PREFAB,06 - WAREHOUSE/INDUSTRIAL,3,CB,Average,2024,1.00,4,CB,MF4,2024,1.04,Size,CB,Size,2024.0,1.19,20.0,CB,Non-Std Wall Height,2024.0,1.13,66020121510000.html

In [9]:
df3 = pd.read_csv(r"D:\North Carolina\Cabarrus\Property\clean\us_nc_37025_data_prop_sub-area-information_silver_20251127.csv")
df3

,parcel_number,sub_area_type,description,actual_area,percent_of_base,effective_area,replacement_cost_new,page_save
0,46706951200000,BAS,Base Living Area,1099.0,100,1099.0,203557.0,46706951200000.html
1,46706951200000,FGD,"Garage, Finished, with Door",452.0,45,203.0,37600.0,46706951200000.html
2,46706951200000,PTO,Patio,850.0,5,43.0,7964.0,46706951200000.html
3,46706951200000,FOP,"Porch, Open, Finished",182.0,35,64.0,11854.0,46706951200000.html
4,46706951200000,FUS,"Upper Story, Finished",1468.0,85,1248.0,231155.0,46706951200000.html
...,...,...,...,...,...,...,...,...
365925,66020121510000,BAS,Base Living Area,1950.0,100,1950.0,173160.0,66020121510000.html
365926,56937648340000,BAS,Base Living Area,1226.0,100,1226.0,203908.0,56937648340000.html
365927,56937648340000,FOP,"Porch, Open, Finished",252.0,35,88.0,14636.0,56937648340000.html
365928,56937648340000,STP,Stoop,126.0,25,32.0,5322.0,56937648340000.html
365929,56937648340000,FUS,"Upper Story, Finished",432.0,85,367.0,61039.0,56937648340000.html

In [10]:
merged_df

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,page_save
0,46706951200000,1,2007,2007,2567.0,1485.0,4052,410020.0,NaN,10734 WAYCROSS DR HUNTERSVILLE,01,1,83.0,185.22,494005.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.98,NaN,NaN,NaN,NaN,NaN,46706951200000.html
1,46706963260000,1,2005,2005,3400.0,937.0,4337,509330.0,NaN,10445 SPRING TREE LN HUNTERSVILLE,01,1,81.0,176.40,628800.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,46706963260000.html
2,46707245420000,1,2007,2012,2032.0,699.0,2731,283750.0,NaN,8654 BROOKINGS DR CHARLOTTE,09,1,88.0,151.96,322440.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.00,6,CB,MF6,2024,1.15,Size,CB,Size,2024.0,1.00,NaN,NaN,NaN,NaN,NaN,46707245420000.html
3,46706990940000,1,2006,2006,3204.0,840.0,4044,509870.0,NaN,712 MERCER PL HUNTERSVILLE,01,1,82.0,187.74,621792.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,46706990940000.html
4,46707260670000,1,2005,2010,1712.0,660.0,2372,282800.0,NaN,8543 BROOKINGS DR CHARLOTTE,09,1,86.0,183.28,328838.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.00,6,CB,MF6,2024,1.15,Size,CB,Size,2024.0,1.15,NaN,NaN,NaN,NaN,NaN,46707260670000.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82769,66021043140000,1,2023,2023,1279.0,1089.0,2368,250060.0,NaN,2100 GOLD HILL RD E GOLD HILL,01R,1,99.0,158.76,252587.0,01R - SINGLE FAMILY RURAL,01 - SINGLE FAMILY HOME,2,CB,Below Average,2024,0.90,4,CB,MF4,2024,1.05,Size,CB,Size,2024.0,1.38,NaN,NaN,NaN,NaN,NaN,66021043140000.html
82770,66023336930000,1,2022,2022,2791.0,1420.0,4211,506870.0,NaN,NaN,01R,1,98.0,167.58,517210.0,01R - SINGLE FAMILY RURAL,01 - SINGLE FAMILY HOME,4,CB,Above Average,2024,1.10,4,CB,MF4,2024,1.05,Size,CB,Size,2024.0,0.97,NaN,NaN,NaN,NaN,NaN,66023336930000.html
82771,56610145570000,1,1980,1985,1166.0,882.0,2048,165460.0,NaN,380 ST JOHNS CHURCH RD CONCORD,01R,1,61.0,182.70,271252.0,01R - SINGLE FAMILY RURAL,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.00,3,CB,MF3,2024,1.00,Size,CB,Size,2024.0,1.42,NaN,NaN,NaN,NaN,NaN,56610145570000.html
82772,66031133160000,1,1976,1981,1268.0,1130.0,2398,39450.0,NaN,4201 GOLD HILL RD E GOLD HILL,03,2,30.0,77.70,131493.0,03 - MANU HOME (SINGLE WIDE),02 - MANUFACTURED HOME,1,CB,Minimum,2024,0.75,4,CB,MF4,2024,1.04,Size,CB,Size,2024.0,0.98,NaN,NaN,NaN,NaN,NaN,66031133160000.html
82773,66020121510000,1,2006,2006,3420.0,1110.0,4530,165170.0,NaN,2245 GOLD HILL RD E MT PLEASANT,49,6,40.0,88.80,412920.0,49 - WAREHOUSE - PREFAB,06 - WAREHOUSE/INDUSTRIAL,3,CB,Average,2024,1.00,4,CB,MF4,2024,1.04,Size,CB,Size,2024.0,1.19,20.0,CB,Non-Std Wall Height,2024.0,1.13,66020121510000.html

In [11]:
df3[df3.duplicated()]

Empty DataFrame
Columns: [parcel_number, sub_area_type, description, actual_area, percent_of_base, effective_area, replacement_cost_new, page_save]
Index: []

In [12]:
# value_cols = [
#     "description",
#     "actual_area",
#     "percent_of_base",
#     "effective_area",
#     "replacement_cost_new"
# ]


# pivot_df = (
#     df3
#     .set_index(["parcel_number", "page_save", "sub_area_type"])[value_cols]
#     .unstack("sub_area_type")
# )


# # desired sub_area_type order (auto-detect & sort if needed)
# sub_area_order = sorted(df3["sub_area_type"].unique())

# ordered_cols = []
# for sub in sub_area_order:
#     for col in value_cols:
#         ordered_cols.append((col, sub))

# pivot_df = pivot_df[ordered_cols]

# # flatten column names → BAS_description, BAS_actual_area, etc.
# pivot_df.columns = [
#     f"{sub}_{col}"
#     for col, sub in pivot_df.columns
# ]

# pivot_df = pivot_df.reset_index()


# merged_df = pd.merge(
#     merged_df,
#     pivot_df,
#     on=["parcel_number", "page_save"],
#     how="left"
# )


# cols = [c for c in merged_df.columns if c != "page_save"] + ["page_save"]
# merged_df = merged_df[cols]
# merged_df

In [13]:
df3['sub_area_type'].value_counts()

sub_area_type
BAS    82720
FOP    67637
FGD    44772
FUS    39484
PTO    32244
       ...
FCB        1
UCB        1
FDU        1
UDU        1
UDS        1
Name: count, Length: 73, dtype: int64

In [14]:
value_cols = [
    "description",
    "actual_area",
    "percent_of_base",
    "effective_area",
    "replacement_cost_new"
]
agg_map = {
    "description": "first",
    "actual_area": "sum",
    "percent_of_base": "sum",
    "effective_area": "sum",
    "replacement_cost_new": "sum"
}

grouped_df = (
    df3
    .groupby(["parcel_number", "page_save", "sub_area_type"], as_index=False)
    .agg(agg_map)
)
pivot_df = (
    grouped_df
    .set_index(["parcel_number", "page_save", "sub_area_type"])[value_cols]
    .unstack("sub_area_type")
)
sub_area_order = sorted(grouped_df["sub_area_type"].unique())

ordered_cols = []
for sub in sub_area_order:
    for col in value_cols:
        ordered_cols.append((col, sub))

pivot_df = pivot_df[ordered_cols]
pivot_df.columns = [
    f"{sub}_{col}"
    for col, sub in pivot_df.columns
]

pivot_df = pivot_df.reset_index()
merged_df = pd.merge(
    merged_df,
    pivot_df,
    on=["parcel_number", "page_save"],
    how="left"
)
cols = [c for c in merged_df.columns if c != "page_save"] + ["page_save"]
merged_df = merged_df[cols]

In [15]:
merged_df

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,ALP_description,ALP_actual_area,ALP_percent_of_base,ALP_effective_area,ALP_replacement_cost_new,AOF_description,AOF_actual_area,AOF_percent_of_base,AOF_effective_area,AOF_replacement_cost_new,APB_description,APB_actual_area,APB_percent_of_base,APB_effective_area,APB_replacement_cost_new,APT_description,APT_actual_area,APT_percent_of_base,APT_effective_area,APT_replacement_cost_new,BAS_description,BAS_actual_area,BAS_percent_of_base,BAS_effective_area,BAS_replacement_cost_new,BOF_description,BOF_actual_area,BOF_percent_of_base,BOF_effective_area,BOF_replacement_cost_new,CAN_description,CAN_actual_area,CAN_percent_of_base,CAN_effective_area,CAN_replacement_cost_new,CAS_description,CAS_actual_area,CAS_percent_of_base,CAS_effective_area,CAS_replacement_cost_new,CBM_description,CBM_actual_area,CBM_percent_of_base,CBM_effective_area,CBM_replacement_cost_new,CDN_description,CDN_actual_area,CDN_percent_of_base,CDN_effective_area,CDN_replacement_cost_new,CLP_description,CLP_actual_area,CLP_percent_of_base,CLP_effective_area,CLP_replacement_cost_new,FAT_description,FAT_actual_area,FAT_percent_of_base,FAT_effective_area,FAT_replacement_cost_new,FBM_description,FBM_actual_area,FBM_percent_of_base,FBM_effective_area,FBM_replacement_cost_new,FCB_description,FCB_actual_area,FCB_percent_of_base,FCB_effective_area,FCB_replacement_cost_new,FCP_description,FCP_actual_area,FCP_percent_of_base,FCP_effective_area,FCP_replacement_cost_new,FDC_description,FDC_actual_area,FDC_percent_of_base,FDC_effective_area,FDC_replacement_cost_new,FDG_description,FDG_actual_area,FDG_percent_of_base,FDG_effective_area,FDG_replacement_cost_new,FDU_description,FDU_actual_area,FDU_percent_of_base,FDU_effective_area,FDU_replacement_cost_new,FEP_description,FEP_actual_area,FEP_percent_of_base,FEP_effective_area,FEP_replacement_cost_new,FGB_description,FGB_actual_area,FGB_percent_of_base,FGB_effective_area,FGB_replacement_cost_new,FGD_description,FGD_actual_area,FGD_percent_of_base,FGD_effective_area,FGD_replacement_cost_new,FGR_description,FGR_actual_area,FGR_percent_of_base,FGR_effective_area,FGR_replacement_cost_new,FHS_description,FHS_actual_area,FHS_percent_of_base,FHS_effective_area,FHS_replacement_cost_new,FOF_description,FOF_actual_area,FOF_percent_of_base,FOF_effective_area,FOF_replacement_cost_new,FOG_description,FOG_actual_area,FOG_percent_of_base,FOG_effective_area,FOG_replacement_cost_new,FOP_description,FOP_actual_area,FOP_percent_of_base,FOP_effective_area,FOP_replacement_cost_new,FSP_description,FSP_actual_area,FSP_percent_of_base,FSP_effective_area,FSP_replacement_cost_new,FST_description,FST_actual_area,FST_percent_of_base,FST_effective_area,FST_replacement_cost_new,FUS_description,FUS_actual_area,FUS_percent_of_base,FUS_effective_area,FUS_replacement_cost_new,FUT_description,FUT_actual_area,FUT_percent_of_base,FUT_effective_area,FUT_replacement_cost_new,GOF_description,GOF_actual_area,GOF_percent_of_base,GOF_effective_area,GOF_replacement_cost_new,LAB_description,LAB_actual_area,LAB_percent_of_base,LAB_effective_area,LAB_replacement_cost_new,LFG_description,LFG_actual_area,LFG_percent_of_base,LFG_effective_area,LFG_replacement_cost_new,LFT_description,LFT_actual_area,LFT_percent_of_base,LFT_effective_area,LFT_replacement_cost_new,LLF_description,LLF_actual_area,LLF_percent_of_base,LLF_effective_area,LLF_replacement_cost_new,LLS_description,LLS_actual_area,LLS_percent_of_base,LLS_effective_area,LLS_replacement_cost_new,LLU_description,LLU_actual_area,LLU_percent_of_base,LLU_effective_area,LLU_replacement_cost_new,LUG_description,LUG_actual_area,LUG_percent_of_base,LUG_effective_area,LUG_replacement_cost_new,MEZ_description,MEZ_actual_area,MEZ_percent_of_base,MEZ_effective_area,MEZ_replacement_cost_new,MFG_description,MFG_actual_area,MFG_percent_of_base,MFG_effective_area,MFG_replacement_cost_new,MFM_description,MFM_actual_area,MFM_percent_of_base,MFM_effective_area,MFM_replacement_cost_new,MOF_description,MOF_actual_area,MOF_percent_of_base,MOF_effective_area,MOF_replacement_cost_new,OEB_description,OEB_actual_area,OEB_percent_of_base,OEB_effective_area,OEB_replacement_cost_new,PTO_description,PTO_actual_area,PTO_percent_of_base,PTO_effective_area,PTO_replacement_cost_new,PTR_description,PTR_actual_area,PTR_percent_of_base,PTR_effective_area,PTR_replacement_cost_new,SBM_description,SBM_actual_area,SBM_percent_of_base,SBM_effective_area,SBM_replacement_cost_new,SDA_description,SDA_actual_area,SDA_percent_of_base,SDA_effective_area,SDA_replacement_cost_new,SFB_description,SFB_actual_area,SFB_percent_of_base,SFB_effective_area,SFB_replacement_cost_new,SPA_description,SPA_actual_area,SPA_percent_of_base,SPA_effective_area,SPA_replacement_cost_new,SRH_description,SRH_actual_area,SRH_percent_of_base,SRH_effective_area,SRH_replacement_cost_new,SRU_description,SRU_actual_area,SRU_percent_of_base,SRU_effective_area,SRU_replacement_cost_new,STP_description,STP_actual_area,STP_percent_of_base,STP_effective_area,STP_replacement_cost_new,TER_description,TER_actual_area,TER_percent_of_base,TER_effective_area,TER_replacement_cost_new,UAT_description,UAT_actual_area,UAT_percent_of_base,UAT_effective_area,UAT_replacement_cost_new,UBM_description,UBM_actual_area,UBM_percent_of_base,UBM_effective_area,UBM_replacement_cost_new,UCB_description,UCB_actual_area,UCB_percent_of_base,UCB_effective_area,UCB_replacement_cost_new,UCP_description,UCP_actual_area,UCP_percent_of_base,UCP_effective_area,UCP_replacement_cost_new,UDC_description,UDC_actual_area,UDC_percent_of_base,UDC_effective_area,UDC_replacement_cost_new,UDG_description,UDG_actual_area,UDG_percent_of_base,UDG_effective_area,UDG_replacement_cost_new,UDS_description,UDS_actual_area,UDS_percent_of_base,UDS_effective_area,UDS_replacement_cost_new,UDU_description,UDU_actual_area,UDU_percent_of_base,UDU_effective_area,UDU_replacement_cost_new,UEP_description,UEP_actual_area,UEP_percent_of_base,UEP_effective_area,UEP_replacement_cost_new,UGB_description,UGB_actual_area,UGB_percent_of_base,UGB_effective_area,UGB_replacement_cost_new,UGD_description,UGD_actual_area,UGD_percent_of_base,UGD_effective_area,UGD_replacement_cost_new,UGR_description,UGR_actual_area,UGR_percent_of_base,UGR_effective_area,UGR_replacement_cost_new,ULP_description,ULP_actual_area,ULP_percent_of_base,ULP_effective_area,ULP_replacement_cost_new,UOG_description,UOG_actual_area,UOG_percent_of_base,UOG_effective_area,UOG_replacement_cost_new,UOP_description,UOP_actual_area,UOP_percent_of_base,UOP_effective_area,UOP_replacement_cost_new,USP_description,USP_actual_area,USP_percent_of_base,USP_effective_area,USP_replacement_cost_new,UST_description,UST_actual_area,UST_percent_of_base,UST_effective_area,UST_replacement_cost_new,UUS_description,UUS_actual_area,UUS_percent_of_base,UUS_effective_area,UUS_replacement_cost_new,UUT_description,UUT_actual_area,UUT_percent_of_base,UUT_effective_area,UUT_replacement_cost_new,WDD_description,WDD_actual_area,WDD_percent_of_base,WDD_effective_area,WDD_replacement_cost_new,page_save
0,46706951200000,1,2007,2007,2567.0,1485.0,4052,410020.0,NaN,10734 WAYCROSS DR HUNTERSVILLE,01,1,83.0,185.22,494005.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1099.0,100.0,1099.0,203557.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",452.0,45.0,203.0,37600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",182.0,35.0,64.0,11854.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1468.0,85.0,1248.0,231155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,850.0,5.0,43.0,7964.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46706951200000.html
1,46706963260000,1,2005,2005,3400.0,937.0,4337,509330.0,NaN,10445 SPRING TREE LN HUNTERSVILLE,01,1,81.0,176.40,628800.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,2070.0,100.0,2070.0,365148.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",649.0,45.0,292.0,51509.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",24.0,35.0,8.0,1411.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1330.0,85.0,1131.0,199508.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,264.0,20.0,53.0,9349.0,46706963260000.html
2,46707245420000,1,2007,2012,2032.0,699.0,2731,283750.0,NaN,8654 BROOKINGS DR CHARLOTTE,09,1,88.0,151.96,322440.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.00,6,CB,MF6,2024,1.15,Size,CB,Size,2024.0,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,810.0,100.0,810.0,123088.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",446.0,45.0,201.0,30544.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",78.0,35.0,27.0,4103.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1222.0,85.0,1039.0,157886.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,175.0,20.0,35.0,5319.0,46707245420000.html
3,46706990940000,1,2006,2006,3204.0,840.0,4044,509870.0,NaN,712 MERCER PL HUNTERSVILLE,01,1,82.0,187.74,621792.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1823.0,100.0,1823.0,342250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",400.0,45.0,180.0,33793.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",248.0,35.0,87.0,16333.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1381.0,85.0,1174.0,220407.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,192.0,20.0,38.0,7134.0,46706990940000.html
4,46707260670000,1,2005,2010,1712.0,660.0,2372,282800.0,NaN,8543 BROOKINGS DR CHARLOTTE,09,1,86.0,183.28,328838.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.00,6,CB,MF6,2024,1.15,Size,CB,Size,2024.0,1.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,624.0,100.0,624.0,114367.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",444.0,45.0,200.0,36656.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",56.0,35.0,20.0,3666.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1088.0,85.0,925.0,169534.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,100.0,5.0,5.0,916.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,60.0,20.0,12.0,2199.0,46707260670000.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

In [16]:
merged_df[merged_df['parcel_number'] == 46706951200000]

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,ALP_description,ALP_actual_area,ALP_percent_of_base,ALP_effective_area,ALP_replacement_cost_new,AOF_description,AOF_actual_area,AOF_percent_of_base,AOF_effective_area,AOF_replacement_cost_new,APB_description,APB_actual_area,APB_percent_of_base,APB_effective_area,APB_replacement_cost_new,APT_description,APT_actual_area,APT_percent_of_base,APT_effective_area,APT_replacement_cost_new,BAS_description,BAS_actual_area,BAS_percent_of_base,BAS_effective_area,BAS_replacement_cost_new,BOF_description,BOF_actual_area,BOF_percent_of_base,BOF_effective_area,BOF_replacement_cost_new,CAN_description,CAN_actual_area,CAN_percent_of_base,CAN_effective_area,CAN_replacement_cost_new,CAS_description,CAS_actual_area,CAS_percent_of_base,CAS_effective_area,CAS_replacement_cost_new,CBM_description,CBM_actual_area,CBM_percent_of_base,CBM_effective_area,CBM_replacement_cost_new,CDN_description,CDN_actual_area,CDN_percent_of_base,CDN_effective_area,CDN_replacement_cost_new,CLP_description,CLP_actual_area,CLP_percent_of_base,CLP_effective_area,CLP_replacement_cost_new,FAT_description,FAT_actual_area,FAT_percent_of_base,FAT_effective_area,FAT_replacement_cost_new,FBM_description,FBM_actual_area,FBM_percent_of_base,FBM_effective_area,FBM_replacement_cost_new,FCB_description,FCB_actual_area,FCB_percent_of_base,FCB_effective_area,FCB_replacement_cost_new,FCP_description,FCP_actual_area,FCP_percent_of_base,FCP_effective_area,FCP_replacement_cost_new,FDC_description,FDC_actual_area,FDC_percent_of_base,FDC_effective_area,FDC_replacement_cost_new,FDG_description,FDG_actual_area,FDG_percent_of_base,FDG_effective_area,FDG_replacement_cost_new,FDU_description,FDU_actual_area,FDU_percent_of_base,FDU_effective_area,FDU_replacement_cost_new,FEP_description,FEP_actual_area,FEP_percent_of_base,FEP_effective_area,FEP_replacement_cost_new,FGB_description,FGB_actual_area,FGB_percent_of_base,FGB_effective_area,FGB_replacement_cost_new,FGD_description,FGD_actual_area,FGD_percent_of_base,FGD_effective_area,FGD_replacement_cost_new,FGR_description,FGR_actual_area,FGR_percent_of_base,FGR_effective_area,FGR_replacement_cost_new,FHS_description,FHS_actual_area,FHS_percent_of_base,FHS_effective_area,FHS_replacement_cost_new,FOF_description,FOF_actual_area,FOF_percent_of_base,FOF_effective_area,FOF_replacement_cost_new,FOG_description,FOG_actual_area,FOG_percent_of_base,FOG_effective_area,FOG_replacement_cost_new,FOP_description,FOP_actual_area,FOP_percent_of_base,FOP_effective_area,FOP_replacement_cost_new,FSP_description,FSP_actual_area,FSP_percent_of_base,FSP_effective_area,FSP_replacement_cost_new,FST_description,FST_actual_area,FST_percent_of_base,FST_effective_area,FST_replacement_cost_new,FUS_description,FUS_actual_area,FUS_percent_of_base,FUS_effective_area,FUS_replacement_cost_new,FUT_description,FUT_actual_area,FUT_percent_of_base,FUT_effective_area,FUT_replacement_cost_new,GOF_description,GOF_actual_area,GOF_percent_of_base,GOF_effective_area,GOF_replacement_cost_new,LAB_description,LAB_actual_area,LAB_percent_of_base,LAB_effective_area,LAB_replacement_cost_new,LFG_description,LFG_actual_area,LFG_percent_of_base,LFG_effective_area,LFG_replacement_cost_new,LFT_description,LFT_actual_area,LFT_percent_of_base,LFT_effective_area,LFT_replacement_cost_new,LLF_description,LLF_actual_area,LLF_percent_of_base,LLF_effective_area,LLF_replacement_cost_new,LLS_description,LLS_actual_area,LLS_percent_of_base,LLS_effective_area,LLS_replacement_cost_new,LLU_description,LLU_actual_area,LLU_percent_of_base,LLU_effective_area,LLU_replacement_cost_new,LUG_description,LUG_actual_area,LUG_percent_of_base,LUG_effective_area,LUG_replacement_cost_new,MEZ_description,MEZ_actual_area,MEZ_percent_of_base,MEZ_effective_area,MEZ_replacement_cost_new,MFG_description,MFG_actual_area,MFG_percent_of_base,MFG_effective_area,MFG_replacement_cost_new,MFM_description,MFM_actual_area,MFM_percent_of_base,MFM_effective_area,MFM_replacement_cost_new,MOF_description,MOF_actual_area,MOF_percent_of_base,MOF_effective_area,MOF_replacement_cost_new,OEB_description,OEB_actual_area,OEB_percent_of_base,OEB_effective_area,OEB_replacement_cost_new,PTO_description,PTO_actual_area,PTO_percent_of_base,PTO_effective_area,PTO_replacement_cost_new,PTR_description,PTR_actual_area,PTR_percent_of_base,PTR_effective_area,PTR_replacement_cost_new,SBM_description,SBM_actual_area,SBM_percent_of_base,SBM_effective_area,SBM_replacement_cost_new,SDA_description,SDA_actual_area,SDA_percent_of_base,SDA_effective_area,SDA_replacement_cost_new,SFB_description,SFB_actual_area,SFB_percent_of_base,SFB_effective_area,SFB_replacement_cost_new,SPA_description,SPA_actual_area,SPA_percent_of_base,SPA_effective_area,SPA_replacement_cost_new,SRH_description,SRH_actual_area,SRH_percent_of_base,SRH_effective_area,SRH_replacement_cost_new,SRU_description,SRU_actual_area,SRU_percent_of_base,SRU_effective_area,SRU_replacement_cost_new,STP_description,STP_actual_area,STP_percent_of_base,STP_effective_area,STP_replacement_cost_new,TER_description,TER_actual_area,TER_percent_of_base,TER_effective_area,TER_replacement_cost_new,UAT_description,UAT_actual_area,UAT_percent_of_base,UAT_effective_area,UAT_replacement_cost_new,UBM_description,UBM_actual_area,UBM_percent_of_base,UBM_effective_area,UBM_replacement_cost_new,UCB_description,UCB_actual_area,UCB_percent_of_base,UCB_effective_area,UCB_replacement_cost_new,UCP_description,UCP_actual_area,UCP_percent_of_base,UCP_effective_area,UCP_replacement_cost_new,UDC_description,UDC_actual_area,UDC_percent_of_base,UDC_effective_area,UDC_replacement_cost_new,UDG_description,UDG_actual_area,UDG_percent_of_base,UDG_effective_area,UDG_replacement_cost_new,UDS_description,UDS_actual_area,UDS_percent_of_base,UDS_effective_area,UDS_replacement_cost_new,UDU_description,UDU_actual_area,UDU_percent_of_base,UDU_effective_area,UDU_replacement_cost_new,UEP_description,UEP_actual_area,UEP_percent_of_base,UEP_effective_area,UEP_replacement_cost_new,UGB_description,UGB_actual_area,UGB_percent_of_base,UGB_effective_area,UGB_replacement_cost_new,UGD_description,UGD_actual_area,UGD_percent_of_base,UGD_effective_area,UGD_replacement_cost_new,UGR_description,UGR_actual_area,UGR_percent_of_base,UGR_effective_area,UGR_replacement_cost_new,ULP_description,ULP_actual_area,ULP_percent_of_base,ULP_effective_area,ULP_replacement_cost_new,UOG_description,UOG_actual_area,UOG_percent_of_base,UOG_effective_area,UOG_replacement_cost_new,UOP_description,UOP_actual_area,UOP_percent_of_base,UOP_effective_area,UOP_replacement_cost_new,USP_description,USP_actual_area,USP_percent_of_base,USP_effective_area,USP_replacement_cost_new,UST_description,UST_actual_area,UST_percent_of_base,UST_effective_area,UST_replacement_cost_new,UUS_description,UUS_actual_area,UUS_percent_of_base,UUS_effective_area,UUS_replacement_cost_new,UUT_description,UUT_actual_area,UUT_percent_of_base,UUT_effective_area,UUT_replacement_cost_new,WDD_description,WDD_actual_area,WDD_percent_of_base,WDD_effective_area,WDD_replacement_cost_new,page_save
0,46706951200000,1,2007,2007,2567.0,1485.0,4052,410020.0,NaN,10734 WAYCROSS DR HUNTERSVILLE,01,1,83.0,185.22,494005.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1099.0,100.0,1099.0,203557.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",452.0,45.0,203.0,37600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",182.0,35.0,64.0,11854.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1468.0,85.0,1248.0,231155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,850.0,5.0,43.0,7964.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46706951200000.html

In [17]:
df4 = pd.read_csv(r"D:\North Carolina\Cabarrus\Property\clean\us_nc_37025_data_prop_building-structural-elements_silver_20251127.csv")
df4

,parcel_number,element,detail_description,point_value,percentage,page_save
0,46706951200000,Air Conditioning Type,03-Central,4.0,100.0,46706951200000.html
1,46706951200000,Bedrooms/Bathrooms/Half-Bathrooms,4/2/1,15.0,NaN,46706951200000.html
2,46706951200000,Exterior Walls,07-Cement Fiber Siding,32.0,100.0,46706951200000.html
3,46706951200000,Fireplace,2-Pre Fabricated,1875.0,100.0,46706951200000.html
4,46706951200000,Foundation,3-Continuous Footing,5.0,100.0,46706951200000.html
...,...,...,...,...,...,...
1109324,66021043140000,Interior Floor Cover,14-Carpet,NaN,50.0,66021043140000.html
1109325,66021043140000,Interior Wall Construction,5-Drywall/Sheetrock,20.0,100.0,66021043140000.html
1109326,66021043140000,Roofing Cover,03-Asphalt or Composition Shingle,3.0,100.0,66021043140000.html
1109327,66021043140000,Roofing Structure,03-Gable,7.0,100.0,66021043140000.html
1109328,66021043140000,Sub Floor System,4-Plywood,8.0,100.0,66021043140000.html

In [22]:
# correct value columns
values_cols = [
    "detail_description",
    "point_value",
    "percentage"
]

# aggregate duplicates
agge_map = {
    "detail_description": "first",
    "point_value": "sum",
    "percentage": "sum"
}

grouped_df4 = (
    df4
    .groupby(["parcel_number", "page_save", "element"], as_index=False)
    .agg(agge_map)
)

# pivot to wide format
pivot_df4 = (
    grouped_df4
    .set_index(["parcel_number", "page_save", "element"])[values_cols]
    .unstack("element")
)

# enforce element-wise ordering
element_order = sorted(grouped_df4["element"].unique())

ordered_cols = []
for el in element_order:
    for col in values_cols:
        ordered_cols.append((col, el))

pivot_df4 = pivot_df4[ordered_cols]

# flatten column names
pivot_df4.columns = [
    f"{el}_{col}"
    for col, el in pivot_df4.columns
]

pivot_df4 = pivot_df4.reset_index()

In [20]:
merged_df = pd.merge(
    merged_df,
    pivot_df4,
    on=["parcel_number", "page_save"],
    how="left"
)

# keep page_save last
cols = [c for c in merged_df.columns if c != "page_save"] + ["page_save"]
merged_df = merged_df[cols]
merged_df

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,ALP_description,ALP_actual_area,ALP_percent_of_base,ALP_effective_area,ALP_replacement_cost_new,AOF_description,AOF_actual_area,AOF_percent_of_base,AOF_effective_area,AOF_replacement_cost_new,APB_description,APB_actual_area,APB_percent_of_base,APB_effective_area,APB_replacement_cost_new,APT_description,APT_actual_area,APT_percent_of_base,APT_effective_area,APT_replacement_cost_new,BAS_description,BAS_actual_area,BAS_percent_of_base,BAS_effective_area,BAS_replacement_cost_new,BOF_description,BOF_actual_area,BOF_percent_of_base,BOF_effective_area,BOF_replacement_cost_new,CAN_description,CAN_actual_area,CAN_percent_of_base,CAN_effective_area,CAN_replacement_cost_new,CAS_description,CAS_actual_area,CAS_percent_of_base,CAS_effective_area,CAS_replacement_cost_new,CBM_description,CBM_actual_area,CBM_percent_of_base,CBM_effective_area,CBM_replacement_cost_new,CDN_description,CDN_actual_area,CDN_percent_of_base,CDN_effective_area,CDN_replacement_cost_new,CLP_description,CLP_actual_area,CLP_percent_of_base,CLP_effective_area,CLP_replacement_cost_new,FAT_description,FAT_actual_area,FAT_percent_of_base,FAT_effective_area,FAT_replacement_cost_new,FBM_description,FBM_actual_area,FBM_percent_of_base,FBM_effective_area,FBM_replacement_cost_new,FCB_description,FCB_actual_area,FCB_percent_of_base,FCB_effective_area,FCB_replacement_cost_new,FCP_description,FCP_actual_area,FCP_percent_of_base,FCP_effective_area,FCP_replacement_cost_new,FDC_description,FDC_actual_area,FDC_percent_of_base,FDC_effective_area,FDC_replacement_cost_new,FDG_description,FDG_actual_area,FDG_percent_of_base,FDG_effective_area,FDG_replacement_cost_new,FDU_description,FDU_actual_area,FDU_percent_of_base,FDU_effective_area,FDU_replacement_cost_new,FEP_description,FEP_actual_area,FEP_percent_of_base,FEP_effective_area,FEP_replacement_cost_new,FGB_description,FGB_actual_area,FGB_percent_of_base,FGB_effective_area,FGB_replacement_cost_new,FGD_description,FGD_actual_area,FGD_percent_of_base,FGD_effective_area,FGD_replacement_cost_new,FGR_description,FGR_actual_area,FGR_percent_of_base,FGR_effective_area,FGR_replacement_cost_new,FHS_description,FHS_actual_area,FHS_percent_of_base,FHS_effective_area,FHS_replacement_cost_new,FOF_description,FOF_actual_area,FOF_percent_of_base,FOF_effective_area,FOF_replacement_cost_new,FOG_description,FOG_actual_area,FOG_percent_of_base,FOG_effective_area,FOG_replacement_cost_new,FOP_description,FOP_actual_area,FOP_percent_of_base,FOP_effective_area,FOP_replacement_cost_new,FSP_description,FSP_actual_area,FSP_percent_of_base,FSP_effective_area,FSP_replacement_cost_new,FST_description,FST_actual_area,FST_percent_of_base,FST_effective_area,FST_replacement_cost_new,FUS_description,FUS_actual_area,FUS_percent_of_base,FUS_effective_area,FUS_replacement_cost_new,FUT_description,FUT_actual_area,FUT_percent_of_base,FUT_effective_area,FUT_replacement_cost_new,GOF_description,GOF_actual_area,GOF_percent_of_base,GOF_effective_area,GOF_replacement_cost_new,LAB_description,LAB_actual_area,LAB_percent_of_base,LAB_effective_area,LAB_replacement_cost_new,LFG_description,LFG_actual_area,LFG_percent_of_base,LFG_effective_area,LFG_replacement_cost_new,LFT_description,LFT_actual_area,LFT_percent_of_base,LFT_effective_area,LFT_replacement_cost_new,LLF_description,LLF_actual_area,LLF_percent_of_base,LLF_effective_area,LLF_replacement_cost_new,LLS_description,LLS_actual_area,LLS_percent_of_base,LLS_effective_area,LLS_replacement_cost_new,LLU_description,LLU_actual_area,LLU_percent_of_base,LLU_effective_area,LLU_replacement_cost_new,LUG_description,LUG_actual_area,LUG_percent_of_base,LUG_effective_area,LUG_replacement_cost_new,MEZ_description,MEZ_actual_area,MEZ_percent_of_base,MEZ_effective_area,MEZ_replacement_cost_new,MFG_description,MFG_actual_area,MFG_percent_of_base,MFG_effective_area,MFG_replacement_cost_new,MFM_description,MFM_actual_area,MFM_percent_of_base,MFM_effective_area,MFM_replacement_cost_new,MOF_description,MOF_actual_area,MOF_percent_of_base,MOF_effective_area,MOF_replacement_cost_new,OEB_description,OEB_actual_area,OEB_percent_of_base,OEB_effective_area,OEB_replacement_cost_new,PTO_description,PTO_actual_area,PTO_percent_of_base,PTO_effective_area,PTO_replacement_cost_new,PTR_description,PTR_actual_area,PTR_percent_of_base,PTR_effective_area,PTR_replacement_cost_new,SBM_description,SBM_actual_area,SBM_percent_of_base,SBM_effective_area,SBM_replacement_cost_new,SDA_description,SDA_actual_area,SDA_percent_of_base,SDA_effective_area,SDA_replacement_cost_new,SFB_description,SFB_actual_area,SFB_percent_of_base,SFB_effective_area,SFB_replacement_cost_new,SPA_description,SPA_actual_area,SPA_percent_of_base,SPA_effective_area,SPA_replacement_cost_new,SRH_description,SRH_actual_area,SRH_percent_of_base,SRH_effective_area,SRH_replacement_cost_new,SRU_description,SRU_actual_area,SRU_percent_of_base,SRU_effective_area,SRU_replacement_cost_new,STP_description,STP_actual_area,STP_percent_of_base,STP_effective_area,STP_replacement_cost_new,TER_description,TER_actual_area,TER_percent_of_base,TER_effective_area,TER_replacement_cost_new,UAT_description,UAT_actual_area,UAT_percent_of_base,UAT_effective_area,UAT_replacement_cost_new,UBM_description,UBM_actual_area,UBM_percent_of_base,UBM_effective_area,UBM_replacement_cost_new,UCB_description,UCB_actual_area,UCB_percent_of_base,UCB_effective_area,UCB_replacement_cost_new,UCP_description,UCP_actual_area,UCP_percent_of_base,UCP_effective_area,UCP_replacement_cost_new,UDC_description,UDC_actual_area,UDC_percent_of_base,UDC_effective_area,UDC_replacement_cost_new,UDG_description,UDG_actual_area,UDG_percent_of_base,UDG_effective_area,UDG_replacement_cost_new,UDS_description,UDS_actual_area,UDS_percent_of_base,UDS_effective_area,UDS_replacement_cost_new,UDU_description,UDU_actual_area,UDU_percent_of_base,UDU_effective_area,UDU_replacement_cost_new,UEP_description,UEP_actual_area,UEP_percent_of_base,UEP_effective_area,UEP_replacement_cost_new,UGB_description,UGB_actual_area,UGB_percent_of_base,UGB_effective_area,UGB_replacement_cost_new,UGD_description,UGD_actual_area,UGD_percent_of_base,UGD_effective_area,UGD_replacement_cost_new,UGR_description,UGR_actual_area,UGR_percent_of_base,UGR_effective_area,UGR_replacement_cost_new,ULP_description,ULP_actual_area,ULP_percent_of_base,ULP_effective_area,ULP_replacement_cost_new,UOG_description,UOG_actual_area,UOG_percent_of_base,UOG_effective_area,UOG_replacement_cost_new,UOP_description,UOP_actual_area,UOP_percent_of_base,UOP_effective_area,UOP_replacement_cost_new,USP_description,USP_actual_area,USP_percent_of_base,USP_effective_area,USP_replacement_cost_new,UST_description,UST_actual_area,UST_percent_of_base,UST_effective_area,UST_replacement_cost_new,UUS_description,UUS_actual_area,UUS_percent_of_base,UUS_effective_area,UUS_replacement_cost_new,UUT_description,UUT_actual_area,UUT_percent_of_base,UUT_effective_area,UUT_replacement_cost_new,WDD_description,WDD_actual_area,WDD_percent_of_base,WDD_effective_area,WDD_replacement_cost_new,Air Conditioning Type_detail_description,Air Conditioning Type_point_value,Air Conditioning Type_percentage,Average Rooms Per Floor_detail_description,Average Rooms Per Floor_point_value,Average Rooms Per Floor_percentage,Bedrooms/Bathrooms/Half-Bathrooms_detail_description,Bedrooms/Bathrooms/Half-Bathrooms_point_value,Bedrooms/Bathrooms/Half-Bathrooms_percentage,Ceiling & Insulation_detail_description,Ceiling & Insulation_point_value,Ceiling & Insulation_percentage,Commercial Heat & Air_detail_description,Commercial Heat & Air_point_value,Commercial Heat & Air_percentage,Common Owned Percentage_detail_description,Common Owned Percentage_point_value,Common Owned Percentage_percentage,Common Wall Percentage_detail_description,Common Wall Percentage_point_value,Common Wall Percentage_percentage,Condo Land Type_detail_description,Condo Land Type_point_value,Condo Land Type_percentage,Exterior Walls_detail_description,Exterior Walls_point_value,Exterior Walls_percentage,Fireplace_detail_description,Fireplace_point_value,Fireplace_percentage,Floor Number_detail_description,Floor Number_point_value,Floor Number_percentage,Foundation_detail_description,Foundation_point_value,Foundation_percentage,Heating Fuel_detail_description,Heating Fuel_point_value,Heating Fuel_percentage,Heating Type_detail_description,Heating Type_point_value,Heating Type_percentage,Interior Floor Cover_detail_description,Interior Floor Cover_point_value,Interior Floor Cover_percentage,Interior Wall Construction_detail_description,Interior Wall Construction_point_value,Interior Wall Construction_percentage,Plumbing Fixtures_detail_description,Plumbing Fixtures_point_value,Plumbing Fixtures_percentage,Roofing Cover_detail_description,Roofing Cover_point_value,Roofing Cover_percentage,Roofing Structure_detail_description,Roofing Structure_point_value,Roofing Structure_percentage,Structural Frame_detail_description,Structural Frame_point_value,Structural Frame_percentage,Sub Floor System_detail_description,Sub Floor System_point_value,Sub Floor System_percentage,Unit Count_detail_description,Unit Count_point_value,Unit Count_percentage,Unit Location_detail_description,Unit Location_point_value,Unit Location_percentage,page_save
0,46706951200000,1,2007,2007,2567.0,1485.0,4052,410020.0,NaN,10734 WAYCROSS DR HUNTERSVILLE,01,1,83.0,185.22,494005.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1099.0,100.0,1099.0,203557.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",452.0,45.0,203.0,37600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",182.0,35.0,64.0,11854.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1468.0,85.0,1248.0,231155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,850.0,5.0,43.0,7964.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-Central,4.0,100.0,NaN,NaN,NaN,4/2/1,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07-Cement Fiber Siding,32.0,100.0,2-Pre Fabricated,1875.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,03-Gas,1.0,100.0,04-Forced Air - Ducted,4.0,100.0,08-Sheet Vinyl,10.0,100.0,6-Custom Interior,32.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,06-Irregular/Cathedral,13.0,100.0,NaN,NaN,NaN,4-Plywood,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,46706951200000.html
1,46706963260000,1,2005,2005,3400.0,937.0,4337,509330.0,NaN,10445 SPRING TREE LN HUNTERSVILLE,01,1,81.0,176.40,628800.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,2070.0,100.0,2070.0,365148.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",649.0,45.0,292.0,51509.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",24.0,35.0,8.0,1411.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1330.0,85.0,1131.0,199508.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,264.0,20.0,53.0,9349.0,03-Central,4.0,100.0,NaN,NaN,NaN,4/3/1,17.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10-Aluminum/Vinyl Siding,32.0,100.0,2-Pre Fabricated,1875.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,03-Gas,1.0,100.0,04-Forced Air - Ducted,4.0,100.0,08-Sheet Vinyl,6.0,100.0,6-Custom Interior,32.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,06-Irregular/Cathedral,13.0,100.0,NaN,NaN,NaN,4-Plywood,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,46706963260000.html
2,46707245420000,1,2007,2012,2032.0,699.0,2731,283750.0,NaN,8654 BROOKINGS DR CHARLOTTE,09,1,88.0,151.96,322440.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.00,6,CB,MF6,2024,1.15,Size,CB,Size,2024.0,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,810.0,100.0,810.0,123088.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",446.0,45.0,201.0,30544.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",78.0,35.0,27.0,4103.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1222.0,85.0,1039.0,157886.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,175.0,20.0,35.0,5319.0,03-Central,4.0,100.0,NaN,NaN,NaN,3/2/1,13.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10-Aluminum/Vinyl Siding,30.0,100.0,2-Pre Fabricated,1500.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,03-Gas,1.0,100.0,04-Forced Air - Ducted,4.0,100.0,12-Hardwood,10.0,100.0,5-Drywall/Sheetrock,26.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,06-Irregular/Cathedral,13.0,100.0,NaN,NaN,NaN,2-Slab on Grade-Residential/Commercial,5.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,46707245420000.html
3,46706990940000,1,2006,2006,3204.0,840.0,4044,509870.0,NaN,712 MERCER PL HUNTERSVILLE,01,1,82.0,187.74,621792.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1823.0,100.0,1823.0,342250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",400.0,45.0,180.0,33793.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",248.0,35.0,87.0,16333.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1381.0,85.0,1174.0,220407.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,192.0,20.0,38.0,7134.0,03-Central,4.0,100.0,NaN,NaN,NaN,4/2/1,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07-Cement Fiber Siding,32.0,100.0,2-Pre Fabricated,1875.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,03-Gas,1.0,100.0,04-Forced Air - Ducted,4.0,100.0,12-Hardwood,16.0,100.0,6-Custom Interior,32.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,06-Irregular/Cathedral,13.0,100.0,NaN,NaN,NaN,4-Plywood,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,46706990940000.html

In [21]:
df5 = pd.read_csv(r"D:\North Carolina\Cabarrus\Property\clean\us_nc_37025_data_prop_building-bed-bath-half_silver_20251127.csv")
df5

,parcel_number,room_type,base_area,upper_level,lower_level,page_save
0,46706951200000,Bathrooms,NaN,2.0,NaN,46706951200000.html
1,46706951200000,Bedrooms,NaN,4.0,NaN,46706951200000.html
2,46706951200000,Half-Bathrooms,1.0,NaN,NaN,46706951200000.html
3,46707457780000,Bathrooms,1.0,3.0,NaN,46707457780000.html
4,46707457780000,Bedrooms,1.0,4.0,NaN,46707457780000.html
...,...,...,...,...,...,...
189556,56304158720000,Bedrooms,2.0,NaN,NaN,56304158720000.html
189557,56211134900000,Bathrooms,1.0,1.0,NaN,56211134900000.html
189558,56211134900000,Bedrooms,NaN,3.0,NaN,56211134900000.html
189559,55194367850000,Bathrooms,1.0,2.0,NaN,55194367850000.html
189560,55194367850000,Bedrooms,1.0,3.0,NaN,55194367850000.html

In [23]:
# correct value columns
valuess_cols = [
    "base_area",
    "upper_level",
    "lower_level"
]

# aggregate duplicates
aggee_map = {
    "base_area": "first",
    "upper_level": "sum",
    "lower_level": "sum"
}

grouped_df5 = (
    df5
    .groupby(["parcel_number", "page_save", "room_type"], as_index=False)
    .agg(aggee_map)
)

# pivot to wide format
pivot_df5 = (
    grouped_df5
    .set_index(["parcel_number", "page_save", "room_type"])[valuess_cols]
    .unstack("room_type")
)

# enforce element-wise ordering
element_order = sorted(grouped_df5["room_type"].unique())

ordered_cols = []
for el in element_order:
    for col in valuess_cols:
        ordered_cols.append((col, el))

pivot_df5 = pivot_df5[ordered_cols]

# flatten column names
pivot_df5.columns = [
    f"{el}_{col}"
    for col, el in pivot_df5.columns
]
pivot_df5 = pivot_df5.reset_index()

In [24]:
merged_df = pd.merge(
    merged_df,
    pivot_df5,
    on=["parcel_number", "page_save"],
    how="left"
)

# keep page_save last
cols = [c for c in merged_df.columns if c != "page_save"] + ["page_save"]
merged_df = merged_df[cols]
merged_df

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,ALP_description,ALP_actual_area,ALP_percent_of_base,ALP_effective_area,ALP_replacement_cost_new,AOF_description,AOF_actual_area,AOF_percent_of_base,AOF_effective_area,AOF_replacement_cost_new,APB_description,APB_actual_area,APB_percent_of_base,APB_effective_area,APB_replacement_cost_new,APT_description,APT_actual_area,APT_percent_of_base,APT_effective_area,APT_replacement_cost_new,BAS_description,BAS_actual_area,BAS_percent_of_base,BAS_effective_area,BAS_replacement_cost_new,BOF_description,BOF_actual_area,BOF_percent_of_base,BOF_effective_area,BOF_replacement_cost_new,CAN_description,CAN_actual_area,CAN_percent_of_base,CAN_effective_area,CAN_replacement_cost_new,CAS_description,CAS_actual_area,CAS_percent_of_base,CAS_effective_area,CAS_replacement_cost_new,CBM_description,CBM_actual_area,CBM_percent_of_base,CBM_effective_area,CBM_replacement_cost_new,CDN_description,CDN_actual_area,CDN_percent_of_base,CDN_effective_area,CDN_replacement_cost_new,CLP_description,CLP_actual_area,CLP_percent_of_base,CLP_effective_area,CLP_replacement_cost_new,FAT_description,FAT_actual_area,FAT_percent_of_base,FAT_effective_area,FAT_replacement_cost_new,FBM_description,FBM_actual_area,FBM_percent_of_base,FBM_effective_area,FBM_replacement_cost_new,FCB_description,FCB_actual_area,FCB_percent_of_base,FCB_effective_area,FCB_replacement_cost_new,FCP_description,FCP_actual_area,FCP_percent_of_base,FCP_effective_area,FCP_replacement_cost_new,FDC_description,FDC_actual_area,FDC_percent_of_base,FDC_effective_area,FDC_replacement_cost_new,FDG_description,FDG_actual_area,FDG_percent_of_base,FDG_effective_area,FDG_replacement_cost_new,FDU_description,FDU_actual_area,FDU_percent_of_base,FDU_effective_area,FDU_replacement_cost_new,FEP_description,FEP_actual_area,FEP_percent_of_base,FEP_effective_area,FEP_replacement_cost_new,FGB_description,FGB_actual_area,FGB_percent_of_base,FGB_effective_area,FGB_replacement_cost_new,FGD_description,FGD_actual_area,FGD_percent_of_base,FGD_effective_area,FGD_replacement_cost_new,FGR_description,FGR_actual_area,FGR_percent_of_base,FGR_effective_area,FGR_replacement_cost_new,FHS_description,FHS_actual_area,FHS_percent_of_base,FHS_effective_area,FHS_replacement_cost_new,FOF_description,FOF_actual_area,FOF_percent_of_base,FOF_effective_area,FOF_replacement_cost_new,FOG_description,FOG_actual_area,FOG_percent_of_base,FOG_effective_area,FOG_replacement_cost_new,FOP_description,FOP_actual_area,FOP_percent_of_base,FOP_effective_area,FOP_replacement_cost_new,FSP_description,FSP_actual_area,FSP_percent_of_base,FSP_effective_area,FSP_replacement_cost_new,FST_description,FST_actual_area,FST_percent_of_base,FST_effective_area,FST_replacement_cost_new,FUS_description,FUS_actual_area,FUS_percent_of_base,FUS_effective_area,FUS_replacement_cost_new,FUT_description,FUT_actual_area,FUT_percent_of_base,FUT_effective_area,FUT_replacement_cost_new,GOF_description,GOF_actual_area,GOF_percent_of_base,GOF_effective_area,GOF_replacement_cost_new,LAB_description,LAB_actual_area,LAB_percent_of_base,LAB_effective_area,LAB_replacement_cost_new,LFG_description,LFG_actual_area,LFG_percent_of_base,LFG_effective_area,LFG_replacement_cost_new,LFT_description,LFT_actual_area,LFT_percent_of_base,LFT_effective_area,LFT_replacement_cost_new,LLF_description,LLF_actual_area,LLF_percent_of_base,LLF_effective_area,LLF_replacement_cost_new,LLS_description,LLS_actual_area,LLS_percent_of_base,LLS_effective_area,LLS_replacement_cost_new,LLU_description,LLU_actual_area,LLU_percent_of_base,LLU_effective_area,LLU_replacement_cost_new,LUG_description,LUG_actual_area,LUG_percent_of_base,LUG_effective_area,LUG_replacement_cost_new,MEZ_description,MEZ_actual_area,MEZ_percent_of_base,MEZ_effective_area,MEZ_replacement_cost_new,MFG_description,MFG_actual_area,MFG_percent_of_base,MFG_effective_area,MFG_replacement_cost_new,MFM_description,MFM_actual_area,MFM_percent_of_base,MFM_effective_area,MFM_replacement_cost_new,MOF_description,MOF_actual_area,MOF_percent_of_base,MOF_effective_area,MOF_replacement_cost_new,OEB_description,OEB_actual_area,OEB_percent_of_base,OEB_effective_area,OEB_replacement_cost_new,PTO_description,PTO_actual_area,PTO_percent_of_base,PTO_effective_area,PTO_replacement_cost_new,PTR_description,PTR_actual_area,PTR_percent_of_base,PTR_effective_area,PTR_replacement_cost_new,SBM_description,SBM_actual_area,SBM_percent_of_base,SBM_effective_area,SBM_replacement_cost_new,SDA_description,SDA_actual_area,SDA_percent_of_base,SDA_effective_area,SDA_replacement_cost_new,SFB_description,SFB_actual_area,SFB_percent_of_base,SFB_effective_area,SFB_replacement_cost_new,SPA_description,SPA_actual_area,SPA_percent_of_base,SPA_effective_area,SPA_replacement_cost_new,SRH_description,SRH_actual_area,SRH_percent_of_base,SRH_effective_area,SRH_replacement_cost_new,SRU_description,SRU_actual_area,SRU_percent_of_base,SRU_effective_area,SRU_replacement_cost_new,STP_description,STP_actual_area,STP_percent_of_base,STP_effective_area,STP_replacement_cost_new,TER_description,TER_actual_area,TER_percent_of_base,TER_effective_area,TER_replacement_cost_new,UAT_description,UAT_actual_area,UAT_percent_of_base,UAT_effective_area,UAT_replacement_cost_new,UBM_description,UBM_actual_area,UBM_percent_of_base,UBM_effective_area,UBM_replacement_cost_new,UCB_description,UCB_actual_area,UCB_percent_of_base,UCB_effective_area,UCB_replacement_cost_new,UCP_description,UCP_actual_area,UCP_percent_of_base,UCP_effective_area,UCP_replacement_cost_new,UDC_description,UDC_actual_area,UDC_percent_of_base,UDC_effective_area,UDC_replacement_cost_new,UDG_description,UDG_actual_area,UDG_percent_of_base,UDG_effective_area,UDG_replacement_cost_new,UDS_description,UDS_actual_area,UDS_percent_of_base,UDS_effective_area,UDS_replacement_cost_new,UDU_description,UDU_actual_area,UDU_percent_of_base,UDU_effective_area,UDU_replacement_cost_new,UEP_description,UEP_actual_area,UEP_percent_of_base,UEP_effective_area,UEP_replacement_cost_new,UGB_description,UGB_actual_area,UGB_percent_of_base,UGB_effective_area,UGB_replacement_cost_new,UGD_description,UGD_actual_area,UGD_percent_of_base,UGD_effective_area,UGD_replacement_cost_new,UGR_description,UGR_actual_area,UGR_percent_of_base,UGR_effective_area,UGR_replacement_cost_new,ULP_description,ULP_actual_area,ULP_percent_of_base,ULP_effective_area,ULP_replacement_cost_new,UOG_description,UOG_actual_area,UOG_percent_of_base,UOG_effective_area,UOG_replacement_cost_new,UOP_description,UOP_actual_area,UOP_percent_of_base,UOP_effective_area,UOP_replacement_cost_new,USP_description,USP_actual_area,USP_percent_of_base,USP_effective_area,USP_replacement_cost_new,UST_description,UST_actual_area,UST_percent_of_base,UST_effective_area,UST_replacement_cost_new,UUS_description,UUS_actual_area,UUS_percent_of_base,UUS_effective_area,UUS_replacement_cost_new,UUT_description,UUT_actual_area,UUT_percent_of_base,UUT_effective_area,UUT_replacement_cost_new,WDD_description,WDD_actual_area,WDD_percent_of_base,WDD_effective_area,WDD_replacement_cost_new,Air Conditioning Type_detail_description,Air Conditioning Type_point_value,Air Conditioning Type_percentage,Average Rooms Per Floor_detail_description,Average Rooms Per Floor_point_value,Average Rooms Per Floor_percentage,Bedrooms/Bathrooms/Half-Bathrooms_detail_description,Bedrooms/Bathrooms/Half-Bathrooms_point_value,Bedrooms/Bathrooms/Half-Bathrooms_percentage,Ceiling & Insulation_detail_description,Ceiling & Insulation_point_value,Ceiling & Insulation_percentage,Commercial Heat & Air_detail_description,Commercial Heat & Air_point_value,Commercial Heat & Air_percentage,Common Owned Percentage_detail_description,Common Owned Percentage_point_value,Common Owned Percentage_percentage,Common Wall Percentage_detail_description,Common Wall Percentage_point_value,Common Wall Percentage_percentage,Condo Land Type_detail_description,Condo Land Type_point_value,Condo Land Type_percentage,Exterior Walls_detail_description,Exterior Walls_point_value,Exterior Walls_percentage,Fireplace_detail_description,Fireplace_point_value,Fireplace_percentage,Floor Number_detail_description,Floor Number_point_value,Floor Number_percentage,Foundation_detail_description,Foundation_point_value,Foundation_percentage,Heating Fuel_detail_description,Heating Fuel_point_value,Heating Fuel_percentage,Heating Type_detail_description,Heating Type_point_value,Heating Type_percentage,Interior Floor Cover_detail_description,Interior Floor Cover_point_value,Interior Floor Cover_percentage,Interior Wall Construction_detail_description,Interior Wall Construction_point_value,Interior Wall Construction_percentage,Plumbing Fixtures_detail_description,Plumbing Fixtures_point_value,Plumbing Fixtures_percentage,Roofing Cover_detail_description,Roofing Cover_point_value,Roofing Cover_percentage,Roofing Structure_detail_description,Roofing Structure_point_value,Roofing Structure_percentage,Structural Frame_detail_description,Structural Frame_point_value,Structural Frame_percentage,Sub Floor System_detail_description,Sub Floor System_point_value,Sub Floor System_percentage,Unit Count_detail_description,Unit Count_point_value,Unit Count_percentage,Unit Location_detail_description,Unit Location_point_value,Unit Location_percentage,Bathrooms_base_area,Bathrooms_upper_level,Bathrooms_lower_level,Bedrooms_base_area,Bedrooms_upper_level,Bedrooms_lower_level,Half-Bathrooms_base_area,Half-Bathrooms_upper_level,Half-Bathrooms_lower_level,page_save
0,46706951200000,1,2007,2007,2567.0,1485.0,4052,410020.0,NaN,10734 WAYCROSS DR HUNTERSVILLE,01,1,83.0,185.22,494005.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1099.0,100.0,1099.0,203557.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",452.0,45.0,203.0,37600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",182.0,35.0,64.0,11854.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1468.0,85.0,1248.0,231155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,850.0,5.0,43.0,7964.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-Central,4.0,100.0,NaN,NaN,NaN,4/2/1,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07-Cement Fiber Siding,32.0,100.0,2-Pre Fabricated,1875.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,03-Gas,1.0,100.0,04-Forced Air - Ducted,4.0,100.0,08-Sheet Vinyl,10.0,100.0,6-Custom Interior,32.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,06-Irregular/Cathedral,13.0,100.0,NaN,NaN,NaN,4-Plywood,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,4.0,0.0,1.0,0.0,0.0,46706951200000.html
1,46706963260000,1,2005,2005,3400.0,937.0,4337,509330.0,NaN,10445 SPRING TREE LN HUNTERSVILLE,01,1,81.0,176.40,628800.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,2070.0,100.0,2070.0,365148.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",649.0,45.0,292.0,51509.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",24.0,35.0,8.0,1411.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1330.0,85.0,1131.0,199508.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,264.0,20.0,53.0,9349.0,03-Central,4.0,100.0,NaN,NaN,NaN,4/3/1,17.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10-Aluminum/Vinyl Siding,32.0,100.0,2-Pre Fabricated,1875.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,03-Gas,1.0,100.0,04-Forced Air - Ducted,4.0,100.0,08-Sheet Vinyl,6.0,100.0,6-Custom Interior,32.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,06-Irregular/Cathedral,13.0,100.0,NaN,NaN,NaN,4-Plywood,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,0.0,1.0,3.0,0.0,1.0,0.0,0.0,46706963260000.html
2,46707245420000,1,2007,2012,2032.0,699.0,2731,283750.0,NaN,8654 BROOKINGS DR CHARLOTTE,09,1,88.0,151.96,322440.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.00,6,CB,MF6,2024,1.15,Size,CB,Size,2024.0,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,810.0,100.0,810.0,123088.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",446.0,45.0,201.0,30544.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",78.0,35.0,27.0,4103.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1222.0,85.0,1039.0,157886.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,175.0,20.0,35.0,5319.0,03-Central,4.0,100.0,NaN,NaN,NaN,3/2/1,13.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10-Aluminum/Vinyl Siding,30.0,100.0,2-Pre Fabricated,1500.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,03-Gas,1.0,100.0,04-Forced Air - Ducted,4.0,100.0,12-Hardwood,10.0,100.0,5-Drywall/Sheetrock,26.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,06-Irregular/Cathedral,13.0,100.0,NaN,NaN,NaN,2-Slab on Grade-Residential/Commercial,5.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,3.0,0.0,1.0,0.0,0.0,46707245420000.html
3,46706990940000,1,2006,2006,3204.0,840.0,4044,509870.0,NaN,712 MERCER PL HUNTERSVILLE,01,1,82.0,187.74,621792.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1823.0,100.0,1823.0,342250.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",400.0,45.0,180.0,33793.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",248.0,35.0,87.0,16333.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1381.0,85.0,1174.0,220407.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,192.0,20.0,38.0,7134.0,03-Central,4.0,100.0,NaN,NaN,NaN,4/2/1,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07-Cement Fiber Siding,32.0,100.0,2-Pre Fabricated,1875.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,03-Gas,1.0,100.0,04-Forced Air - Ducted,4.0,100.0,12-Hardwood,16.0,100.0,6-Custom Interior,32.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,06-Irregular/Cathedral,13.0,100.0,NaN,NaN,NaN,4-Plywood,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,1.0,3.0,0.0,1.0,0.0,0.0,46706990940000.html

In [25]:
df6 = pd.read_csv(r"D:\North Carolina\Cabarrus\Property\clean\us_nc_37025_data_prop_building-obxf_silver_20251127.csv")
df6

,parcel_number,bldg_number,code,description,length,width,units,unit_price,condition_factor,l_b,actual_year_built,effective_year_built,annual_depreciation,depreciation_override,net_percent_good,appraised_value,page_save
0,46707324050000,1,10,DRIVE CON,17.0,26.0,442.0,4.2,100.0,L,2002,2002,100.0,NaN,50.0,1021.0,46707324050000.html
1,46706963260000,1,10,DRIVE CON,NaN,NaN,1000.0,4.2,100.0,L,2005,2005,95.0,NaN,50.0,1848.0,46706963260000.html
2,46706990940000,1,10,DRIVE CON,50.0,14.0,700.0,4.2,100.0,L,2006,2006,90.0,NaN,50.0,1470.0,46706990940000.html
3,46707245420000,1,10,DRIVE CON,30.0,17.0,510.0,4.2,100.0,L,2007,2007,85.0,NaN,50.0,1071.0,46707245420000.html
4,46706951200000,1,10,DRIVE CON,NaN,NaN,800.0,4.2,100.0,L,2008,2008,80.0,NaN,50.0,1562.0,46706951200000.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155401,66020121510000,1,NaN,DRIVE CON,43.0,24.0,1032.0,4.2,100.0,NaN,2011,2011,65.0,NaN,50.0,1907.0,66020121510000.html
155402,66020121510000,1,NaN,FIREPL PTO,NaN,NaN,1.0,6200.0,100.0,NaN,2011,2011,39.0,NaN,61.0,3782.0,66020121510000.html
155403,66020121510000,1,NaN,STG QUONST,30.0,40.0,1200.0,25.0,100.0,NaN,2020,2020,12.0,NaN,88.0,30360.0,66020121510000.html
155404,56937648340000,1,02,GARAGE FR,20.0,20.0,400.0,14.0,100.0,L,1980,1985,100.0,NaN,30.0,1848.0,56937648340000.html
155405,56937648340000,1,03,CARPORT ML,20.0,10.0,200.0,7.0,100.0,L,1990,1990,100.0,NaN,30.0,525.0,56937648340000.html

In [26]:
merged_df = pd.merge(
    merged_df,
    df6,
    on=["parcel_number", "page_save"],
    how="left"
)

# keep page_save last
cols = [c for c in merged_df.columns if c != "page_save"] + ["page_save"]
merged_df = merged_df[cols]
merged_df

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value_x,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,ALP_description,ALP_actual_area,ALP_percent_of_base,ALP_effective_area,ALP_replacement_cost_new,AOF_description,AOF_actual_area,AOF_percent_of_base,AOF_effective_area,AOF_replacement_cost_new,APB_description,APB_actual_area,APB_percent_of_base,APB_effective_area,APB_replacement_cost_new,APT_description,APT_actual_area,APT_percent_of_base,APT_effective_area,APT_replacement_cost_new,BAS_description,BAS_actual_area,BAS_percent_of_base,BAS_effective_area,BAS_replacement_cost_new,BOF_description,BOF_actual_area,BOF_percent_of_base,BOF_effective_area,BOF_replacement_cost_new,CAN_description,CAN_actual_area,CAN_percent_of_base,CAN_effective_area,CAN_replacement_cost_new,CAS_description,CAS_actual_area,CAS_percent_of_base,CAS_effective_area,CAS_replacement_cost_new,CBM_description,CBM_actual_area,CBM_percent_of_base,CBM_effective_area,CBM_replacement_cost_new,CDN_description,CDN_actual_area,CDN_percent_of_base,CDN_effective_area,CDN_replacement_cost_new,CLP_description,CLP_actual_area,CLP_percent_of_base,CLP_effective_area,CLP_replacement_cost_new,FAT_description,FAT_actual_area,FAT_percent_of_base,FAT_effective_area,FAT_replacement_cost_new,FBM_description,FBM_actual_area,FBM_percent_of_base,FBM_effective_area,FBM_replacement_cost_new,FCB_description,FCB_actual_area,FCB_percent_of_base,FCB_effective_area,FCB_replacement_cost_new,FCP_description,FCP_actual_area,FCP_percent_of_base,FCP_effective_area,FCP_replacement_cost_new,FDC_description,FDC_actual_area,FDC_percent_of_base,FDC_effective_area,FDC_replacement_cost_new,FDG_description,FDG_actual_area,FDG_percent_of_base,FDG_effective_area,FDG_replacement_cost_new,FDU_description,FDU_actual_area,FDU_percent_of_base,FDU_effective_area,FDU_replacement_cost_new,FEP_description,FEP_actual_area,FEP_percent_of_base,FEP_effective_area,FEP_replacement_cost_new,FGB_description,FGB_actual_area,FGB_percent_of_base,FGB_effective_area,FGB_replacement_cost_new,FGD_description,FGD_actual_area,FGD_percent_of_base,FGD_effective_area,FGD_replacement_cost_new,FGR_description,FGR_actual_area,FGR_percent_of_base,FGR_effective_area,FGR_replacement_cost_new,FHS_description,FHS_actual_area,FHS_percent_of_base,FHS_effective_area,FHS_replacement_cost_new,FOF_description,FOF_actual_area,FOF_percent_of_base,FOF_effective_area,FOF_replacement_cost_new,FOG_description,FOG_actual_area,FOG_percent_of_base,FOG_effective_area,FOG_replacement_cost_new,FOP_description,FOP_actual_area,FOP_percent_of_base,FOP_effective_area,FOP_replacement_cost_new,FSP_description,FSP_actual_area,FSP_percent_of_base,FSP_effective_area,FSP_replacement_cost_new,FST_description,FST_actual_area,FST_percent_of_base,FST_effective_area,FST_replacement_cost_new,FUS_description,FUS_actual_area,FUS_percent_of_base,FUS_effective_area,FUS_replacement_cost_new,FUT_description,FUT_actual_area,FUT_percent_of_base,FUT_effective_area,FUT_replacement_cost_new,GOF_description,GOF_actual_area,GOF_percent_of_base,GOF_effective_area,GOF_replacement_cost_new,LAB_description,LAB_actual_area,LAB_percent_of_base,LAB_effective_area,LAB_replacement_cost_new,LFG_description,LFG_actual_area,LFG_percent_of_base,LFG_effective_area,LFG_replacement_cost_new,LFT_description,LFT_actual_area,LFT_percent_of_base,LFT_effective_area,LFT_replacement_cost_new,LLF_description,LLF_actual_area,LLF_percent_of_base,LLF_effective_area,LLF_replacement_cost_new,LLS_description,LLS_actual_area,LLS_percent_of_base,LLS_effective_area,LLS_replacement_cost_new,LLU_description,LLU_actual_area,LLU_percent_of_base,LLU_effective_area,LLU_replacement_cost_new,LUG_description,LUG_actual_area,LUG_percent_of_base,LUG_effective_area,LUG_replacement_cost_new,MEZ_description,MEZ_actual_area,MEZ_percent_of_base,MEZ_effective_area,MEZ_replacement_cost_new,MFG_description,MFG_actual_area,MFG_percent_of_base,MFG_effective_area,MFG_replacement_cost_new,MFM_description,MFM_actual_area,MFM_percent_of_base,MFM_effective_area,MFM_replacement_cost_new,MOF_description,MOF_actual_area,MOF_percent_of_base,MOF_effective_area,MOF_replacement_cost_new,OEB_description,OEB_actual_area,OEB_percent_of_base,OEB_effective_area,OEB_replacement_cost_new,PTO_description,PTO_actual_area,PTO_percent_of_base,PTO_effective_area,PTO_replacement_cost_new,PTR_description,PTR_actual_area,PTR_percent_of_base,PTR_effective_area,PTR_replacement_cost_new,SBM_description,SBM_actual_area,SBM_percent_of_base,SBM_effective_area,SBM_replacement_cost_new,SDA_description,SDA_actual_area,SDA_percent_of_base,SDA_effective_area,SDA_replacement_cost_new,SFB_description,SFB_actual_area,SFB_percent_of_base,SFB_effective_area,SFB_replacement_cost_new,SPA_description,SPA_actual_area,SPA_percent_of_base,SPA_effective_area,SPA_replacement_cost_new,SRH_description,SRH_actual_area,SRH_percent_of_base,SRH_effective_area,SRH_replacement_cost_new,SRU_description,SRU_actual_area,SRU_percent_of_base,SRU_effective_area,SRU_replacement_cost_new,STP_description,STP_actual_area,STP_percent_of_base,STP_effective_area,STP_replacement_cost_new,TER_description,TER_actual_area,TER_percent_of_base,TER_effective_area,TER_replacement_cost_new,UAT_description,UAT_actual_area,UAT_percent_of_base,UAT_effective_area,UAT_replacement_cost_new,UBM_description,UBM_actual_area,UBM_percent_of_base,UBM_effective_area,UBM_replacement_cost_new,UCB_description,UCB_actual_area,UCB_percent_of_base,UCB_effective_area,UCB_replacement_cost_new,UCP_description,UCP_actual_area,UCP_percent_of_base,UCP_effective_area,UCP_replacement_cost_new,UDC_description,UDC_actual_area,UDC_percent_of_base,UDC_effective_area,UDC_replacement_cost_new,UDG_description,UDG_actual_area,UDG_percent_of_base,UDG_effective_area,UDG_replacement_cost_new,UDS_description,UDS_actual_area,UDS_percent_of_base,UDS_effective_area,UDS_replacement_cost_new,UDU_description,UDU_actual_area,UDU_percent_of_base,UDU_effective_area,UDU_replacement_cost_new,UEP_description,UEP_actual_area,UEP_percent_of_base,UEP_effective_area,UEP_replacement_cost_new,UGB_description,UGB_actual_area,UGB_percent_of_base,UGB_effective_area,UGB_replacement_cost_new,UGD_description,UGD_actual_area,UGD_percent_of_base,UGD_effective_area,UGD_replacement_cost_new,UGR_description,UGR_actual_area,UGR_percent_of_base,UGR_effective_area,UGR_replacement_cost_new,ULP_description,ULP_actual_area,ULP_percent_of_base,ULP_effective_area,ULP_replacement_cost_new,UOG_description,UOG_actual_area,UOG_percent_of_base,UOG_effective_area,UOG_replacement_cost_new,UOP_description,UOP_actual_area,UOP_percent_of_base,UOP_effective_area,UOP_replacement_cost_new,USP_description,USP_actual_area,USP_percent_of_base,USP_effective_area,USP_replacement_cost_new,UST_description,UST_actual_area,UST_percent_of_base,UST_effective_area,UST_replacement_cost_new,UUS_description,UUS_actual_area,UUS_percent_of_base,UUS_effective_area,UUS_replacement_cost_new,UUT_description,UUT_actual_area,UUT_percent_of_base,UUT_effective_area,UUT_replacement_cost_new,WDD_description,WDD_actual_area,WDD_percent_of_base,WDD_effective_area,WDD_replacement_cost_new,Air Conditioning Type_detail_description,Air Conditioning Type_point_value,Air Conditioning Type_percentage,Average Rooms Per Floor_detail_description,Average Rooms Per Floor_point_value,Average Rooms Per Floor_percentage,Bedrooms/Bathrooms/Half-Bathrooms_detail_description,Bedrooms/Bathrooms/Half-Bathrooms_point_value,Bedrooms/Bathrooms/Half-Bathrooms_percentage,Ceiling & Insulation_detail_description,Ceiling & Insulation_point_value,Ceiling & Insulation_percentage,Commercial Heat & Air_detail_description,Commercial Heat & Air_point_value,Commercial Heat & Air_percentage,Common Owned Percentage_detail_description,Common Owned Percentage_point_value,Common Owned Percentage_percentage,Common Wall Percentage_detail_description,Common Wall Percentage_point_value,Common Wall Percentage_percentage,Condo Land Type_detail_description,Condo Land Type_point_value,Condo Land Type_percentage,Exterior Walls_detail_description,Exterior Walls_point_value,Exterior Walls_percentage,Fireplace_detail_description,Fireplace_point_value,Fireplace_percentage,Floor Number_detail_description,Floor Number_point_value,Floor Number_percentage,Foundation_detail_description,Foundation_point_value,Foundation_percentage,Heating Fuel_detail_description,Heating Fuel_point_value,Heating Fuel_percentage,Heating Type_detail_description,Heating Type_point_value,Heating Type_percentage,Interior Floor Cover_detail_description,Interior Floor Cover_point_value,Interior Floor Cover_percentage,Interior Wall Construction_detail_description,Interior Wall Construction_point_value,Interior Wall Construction_percentage,Plumbing Fixtures_detail_description,Plumbing Fixtures_point_value,Plumbing Fixtures_percentage,Roofing Cover_detail_description,Roofing Cover_point_value,Roofing Cover_percentage,Roofing Structure_detail_description,Roofing Structure_point_value,Roofing Structure_percentage,Structural Frame_detail_description,Structural Frame_point_value,Structural Frame_percentage,Sub Floor System_detail_description,Sub Floor System_point_value,Sub Floor System_percentage,Unit Count_detail_description,Unit Count_point_value,Unit Count_percentage,Unit Location_detail_description,Unit Location_point_value,Unit Location_percentage,Bathrooms_base_area,Bathrooms_upper_level,Bathrooms_lower_level,Bedrooms_base_area,Bedrooms_upper_level,Bedrooms_lower_level,Half-Bathrooms_base_area,Half-Bathrooms_upper_level,Half-Bathrooms_lower_level,bldg_number,code,description,length,width,units,unit_price,condition_factor,l_b,actual_year_built,effective_year_built,annual_depreciation,depreciation_override,net_percent_good,appraised_value_y,page_save
0,46706951200000,1,2007,2007,2567.0,1485.0,4052,410020.0,NaN,10734 WAYCROSS DR HUNTERSVILLE,01,1,83.0,185.22,494005.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1099.0,100.0,1099.0,203557.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",452.0,45.0,203.0,37600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",182.0,35.0,64.0,11854.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1468.0,85.0,1248.0,231155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,850.0,5.0,43.0,7964.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-Central,4.0,100.0,NaN,NaN,NaN,4/2/1,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07-Cement Fiber Siding,32.0,100.0,2-Pre Fabricated,1875.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,03-Gas,1.0,100.0,04-Forced Air - Ducted,4.0,100.0,08-Sheet Vinyl,10.0,100.0,6-Custom Interior,32.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,06-Irregular/Cathedral,13.0,100.0,NaN,NaN,NaN,4-Plywood,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,4.0,0.0,1.0,0.0,0.0,1.0,10,DRIVE CON,NaN,NaN,800.0,4.2,100.0,L,2008.0,2008.0,80.0,NaN,50.0,1562.0,46706951200000.html
1,46706963260000,1,2005,2005,3400.0,937.0,4337,509330.0,NaN,10445 SPRING TREE LN HUNTERSVILLE,01,1,81.0,176.40,628800.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,2070.0,100.0,2070.0,365148.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",649.0,45.0,292.0,51509.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",24.0,35.0,8.0,1411.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1330.0,85.0,1131.0,199508.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,264.0,20.0,53.0,9349.0,03-Central,4.0,100.0,NaN,NaN,NaN,4/3/1,17.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10-Aluminum/Vinyl Siding,32.0,100.0,2-Pre Fabricated,1875.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,03-Gas,1.0,100.0,04-Forced Air - Ducted,4.0,100.0,08-Sheet Vinyl,6.0,100.0,6-Custom Interior,32.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,06-Irregular/Cathedral,13.0,100.0,NaN,NaN,NaN,4-Plywood,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,2.0,0.0,1.0,3.0,0.0,1.0,0.0,0.0,1.0,10,DRIVE CON,NaN,NaN,1000.0,4.2,100.0,L,2005.0,2005.0,95.0,NaN,50.0,1848.0,46706963260000.html
2,46707245420000,1,2007,2012,2032.0,699.0,2731,283750.0,NaN,8654 BROOKINGS DR CHARLOTTE,09,1,88.0,151.96,322440.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.00,6,CB,MF6,2024,1.15,Size,CB,Size,2024.0,1.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,810.0,100.0,810.0,123088.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",446.0,45.0,201.0,30544.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",78.0,35.0,27.0,4103.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1222.0,85.0,1039.0,157886.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,175.0,20.0,35.0,5319.0,03-Central,4.0,100.0,NaN,NaN,NaN,3/2/1,13.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10-Aluminum/Vinyl Siding,30.0,100.0,2-Pre Fabricated,1500.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,03-Gas,1.0,100.0,04-Forced Air - Ducted,4.0,100.0,12-Hardwood,10.0,100.0,5-Drywall/Sheetrock,26.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,06-Irregular/Cathedral,13.0,100.0,NaN,NaN,NaN,2-Slab on Grade-Residential/Commercial,5.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,3.0,0.0,1.0,0.0,0.0,1.0,10,DRIVE CON,30.0,17.0,510.0,4.2,100.0,L,2007.0,2007.0,85.0,NaN,50.0,1071.0,46707245420000.html

In [27]:
merged_df[merged_df['parcel_number'] == 46706951200000]

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value_x,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,ALP_description,ALP_actual_area,ALP_percent_of_base,ALP_effective_area,ALP_replacement_cost_new,AOF_description,AOF_actual_area,AOF_percent_of_base,AOF_effective_area,AOF_replacement_cost_new,APB_description,APB_actual_area,APB_percent_of_base,APB_effective_area,APB_replacement_cost_new,APT_description,APT_actual_area,APT_percent_of_base,APT_effective_area,APT_replacement_cost_new,BAS_description,BAS_actual_area,BAS_percent_of_base,BAS_effective_area,BAS_replacement_cost_new,BOF_description,BOF_actual_area,BOF_percent_of_base,BOF_effective_area,BOF_replacement_cost_new,CAN_description,CAN_actual_area,CAN_percent_of_base,CAN_effective_area,CAN_replacement_cost_new,CAS_description,CAS_actual_area,CAS_percent_of_base,CAS_effective_area,CAS_replacement_cost_new,CBM_description,CBM_actual_area,CBM_percent_of_base,CBM_effective_area,CBM_replacement_cost_new,CDN_description,CDN_actual_area,CDN_percent_of_base,CDN_effective_area,CDN_replacement_cost_new,CLP_description,CLP_actual_area,CLP_percent_of_base,CLP_effective_area,CLP_replacement_cost_new,FAT_description,FAT_actual_area,FAT_percent_of_base,FAT_effective_area,FAT_replacement_cost_new,FBM_description,FBM_actual_area,FBM_percent_of_base,FBM_effective_area,FBM_replacement_cost_new,FCB_description,FCB_actual_area,FCB_percent_of_base,FCB_effective_area,FCB_replacement_cost_new,FCP_description,FCP_actual_area,FCP_percent_of_base,FCP_effective_area,FCP_replacement_cost_new,FDC_description,FDC_actual_area,FDC_percent_of_base,FDC_effective_area,FDC_replacement_cost_new,FDG_description,FDG_actual_area,FDG_percent_of_base,FDG_effective_area,FDG_replacement_cost_new,FDU_description,FDU_actual_area,FDU_percent_of_base,FDU_effective_area,FDU_replacement_cost_new,FEP_description,FEP_actual_area,FEP_percent_of_base,FEP_effective_area,FEP_replacement_cost_new,FGB_description,FGB_actual_area,FGB_percent_of_base,FGB_effective_area,FGB_replacement_cost_new,FGD_description,FGD_actual_area,FGD_percent_of_base,FGD_effective_area,FGD_replacement_cost_new,FGR_description,FGR_actual_area,FGR_percent_of_base,FGR_effective_area,FGR_replacement_cost_new,FHS_description,FHS_actual_area,FHS_percent_of_base,FHS_effective_area,FHS_replacement_cost_new,FOF_description,FOF_actual_area,FOF_percent_of_base,FOF_effective_area,FOF_replacement_cost_new,FOG_description,FOG_actual_area,FOG_percent_of_base,FOG_effective_area,FOG_replacement_cost_new,FOP_description,FOP_actual_area,FOP_percent_of_base,FOP_effective_area,FOP_replacement_cost_new,FSP_description,FSP_actual_area,FSP_percent_of_base,FSP_effective_area,FSP_replacement_cost_new,FST_description,FST_actual_area,FST_percent_of_base,FST_effective_area,FST_replacement_cost_new,FUS_description,FUS_actual_area,FUS_percent_of_base,FUS_effective_area,FUS_replacement_cost_new,FUT_description,FUT_actual_area,FUT_percent_of_base,FUT_effective_area,FUT_replacement_cost_new,GOF_description,GOF_actual_area,GOF_percent_of_base,GOF_effective_area,GOF_replacement_cost_new,LAB_description,LAB_actual_area,LAB_percent_of_base,LAB_effective_area,LAB_replacement_cost_new,LFG_description,LFG_actual_area,LFG_percent_of_base,LFG_effective_area,LFG_replacement_cost_new,LFT_description,LFT_actual_area,LFT_percent_of_base,LFT_effective_area,LFT_replacement_cost_new,LLF_description,LLF_actual_area,LLF_percent_of_base,LLF_effective_area,LLF_replacement_cost_new,LLS_description,LLS_actual_area,LLS_percent_of_base,LLS_effective_area,LLS_replacement_cost_new,LLU_description,LLU_actual_area,LLU_percent_of_base,LLU_effective_area,LLU_replacement_cost_new,LUG_description,LUG_actual_area,LUG_percent_of_base,LUG_effective_area,LUG_replacement_cost_new,MEZ_description,MEZ_actual_area,MEZ_percent_of_base,MEZ_effective_area,MEZ_replacement_cost_new,MFG_description,MFG_actual_area,MFG_percent_of_base,MFG_effective_area,MFG_replacement_cost_new,MFM_description,MFM_actual_area,MFM_percent_of_base,MFM_effective_area,MFM_replacement_cost_new,MOF_description,MOF_actual_area,MOF_percent_of_base,MOF_effective_area,MOF_replacement_cost_new,OEB_description,OEB_actual_area,OEB_percent_of_base,OEB_effective_area,OEB_replacement_cost_new,PTO_description,PTO_actual_area,PTO_percent_of_base,PTO_effective_area,PTO_replacement_cost_new,PTR_description,PTR_actual_area,PTR_percent_of_base,PTR_effective_area,PTR_replacement_cost_new,SBM_description,SBM_actual_area,SBM_percent_of_base,SBM_effective_area,SBM_replacement_cost_new,SDA_description,SDA_actual_area,SDA_percent_of_base,SDA_effective_area,SDA_replacement_cost_new,SFB_description,SFB_actual_area,SFB_percent_of_base,SFB_effective_area,SFB_replacement_cost_new,SPA_description,SPA_actual_area,SPA_percent_of_base,SPA_effective_area,SPA_replacement_cost_new,SRH_description,SRH_actual_area,SRH_percent_of_base,SRH_effective_area,SRH_replacement_cost_new,SRU_description,SRU_actual_area,SRU_percent_of_base,SRU_effective_area,SRU_replacement_cost_new,STP_description,STP_actual_area,STP_percent_of_base,STP_effective_area,STP_replacement_cost_new,TER_description,TER_actual_area,TER_percent_of_base,TER_effective_area,TER_replacement_cost_new,UAT_description,UAT_actual_area,UAT_percent_of_base,UAT_effective_area,UAT_replacement_cost_new,UBM_description,UBM_actual_area,UBM_percent_of_base,UBM_effective_area,UBM_replacement_cost_new,UCB_description,UCB_actual_area,UCB_percent_of_base,UCB_effective_area,UCB_replacement_cost_new,UCP_description,UCP_actual_area,UCP_percent_of_base,UCP_effective_area,UCP_replacement_cost_new,UDC_description,UDC_actual_area,UDC_percent_of_base,UDC_effective_area,UDC_replacement_cost_new,UDG_description,UDG_actual_area,UDG_percent_of_base,UDG_effective_area,UDG_replacement_cost_new,UDS_description,UDS_actual_area,UDS_percent_of_base,UDS_effective_area,UDS_replacement_cost_new,UDU_description,UDU_actual_area,UDU_percent_of_base,UDU_effective_area,UDU_replacement_cost_new,UEP_description,UEP_actual_area,UEP_percent_of_base,UEP_effective_area,UEP_replacement_cost_new,UGB_description,UGB_actual_area,UGB_percent_of_base,UGB_effective_area,UGB_replacement_cost_new,UGD_description,UGD_actual_area,UGD_percent_of_base,UGD_effective_area,UGD_replacement_cost_new,UGR_description,UGR_actual_area,UGR_percent_of_base,UGR_effective_area,UGR_replacement_cost_new,ULP_description,ULP_actual_area,ULP_percent_of_base,ULP_effective_area,ULP_replacement_cost_new,UOG_description,UOG_actual_area,UOG_percent_of_base,UOG_effective_area,UOG_replacement_cost_new,UOP_description,UOP_actual_area,UOP_percent_of_base,UOP_effective_area,UOP_replacement_cost_new,USP_description,USP_actual_area,USP_percent_of_base,USP_effective_area,USP_replacement_cost_new,UST_description,UST_actual_area,UST_percent_of_base,UST_effective_area,UST_replacement_cost_new,UUS_description,UUS_actual_area,UUS_percent_of_base,UUS_effective_area,UUS_replacement_cost_new,UUT_description,UUT_actual_area,UUT_percent_of_base,UUT_effective_area,UUT_replacement_cost_new,WDD_description,WDD_actual_area,WDD_percent_of_base,WDD_effective_area,WDD_replacement_cost_new,Air Conditioning Type_detail_description,Air Conditioning Type_point_value,Air Conditioning Type_percentage,Average Rooms Per Floor_detail_description,Average Rooms Per Floor_point_value,Average Rooms Per Floor_percentage,Bedrooms/Bathrooms/Half-Bathrooms_detail_description,Bedrooms/Bathrooms/Half-Bathrooms_point_value,Bedrooms/Bathrooms/Half-Bathrooms_percentage,Ceiling & Insulation_detail_description,Ceiling & Insulation_point_value,Ceiling & Insulation_percentage,Commercial Heat & Air_detail_description,Commercial Heat & Air_point_value,Commercial Heat & Air_percentage,Common Owned Percentage_detail_description,Common Owned Percentage_point_value,Common Owned Percentage_percentage,Common Wall Percentage_detail_description,Common Wall Percentage_point_value,Common Wall Percentage_percentage,Condo Land Type_detail_description,Condo Land Type_point_value,Condo Land Type_percentage,Exterior Walls_detail_description,Exterior Walls_point_value,Exterior Walls_percentage,Fireplace_detail_description,Fireplace_point_value,Fireplace_percentage,Floor Number_detail_description,Floor Number_point_value,Floor Number_percentage,Foundation_detail_description,Foundation_point_value,Foundation_percentage,Heating Fuel_detail_description,Heating Fuel_point_value,Heating Fuel_percentage,Heating Type_detail_description,Heating Type_point_value,Heating Type_percentage,Interior Floor Cover_detail_description,Interior Floor Cover_point_value,Interior Floor Cover_percentage,Interior Wall Construction_detail_description,Interior Wall Construction_point_value,Interior Wall Construction_percentage,Plumbing Fixtures_detail_description,Plumbing Fixtures_point_value,Plumbing Fixtures_percentage,Roofing Cover_detail_description,Roofing Cover_point_value,Roofing Cover_percentage,Roofing Structure_detail_description,Roofing Structure_point_value,Roofing Structure_percentage,Structural Frame_detail_description,Structural Frame_point_value,Structural Frame_percentage,Sub Floor System_detail_description,Sub Floor System_point_value,Sub Floor System_percentage,Unit Count_detail_description,Unit Count_point_value,Unit Count_percentage,Unit Location_detail_description,Unit Location_point_value,Unit Location_percentage,Bathrooms_base_area,Bathrooms_upper_level,Bathrooms_lower_level,Bedrooms_base_area,Bedrooms_upper_level,Bedrooms_lower_level,Half-Bathrooms_base_area,Half-Bathrooms_upper_level,Half-Bathrooms_lower_level,bldg_number,code,description,length,width,units,unit_price,condition_factor,l_b,actual_year_built,effective_year_built,annual_depreciation,depreciation_override,net_percent_good,appraised_value_y,page_save
0,46706951200000,1,2007,2007,2567.0,1485.0,4052,410020.0,NaN,10734 WAYCROSS DR HUNTERSVILLE,01,1,83.0,185.22,494005.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,5,CB,Custom,2024,1.25,2,CB,MF2,2024,0.95,Size,CB,Size,2024.0,0.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1099.0,100.0,1099.0,203557.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",452.0,45.0,203.0,37600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",182.0,35.0,64.0,11854.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1468.0,85.0,1248.0,231155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,850.0,5.0,43.0,7964.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-Central,4.0,100.0,NaN,NaN,NaN,4/2/1,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07-Cement Fiber Siding,32.0,100.0,2-Pre Fabricated,1875.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,03-Gas,1.0,100.0,04-Forced Air - Ducted,4.0,100.0,08-Sheet Vinyl,10.0,100.0,6-Custom Interior,32.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,06-Irregular/Cathedral,13.0,100.0,NaN,NaN,NaN,4-Plywood,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,4.0,0.0,1.0,0.0,0.0,1.0,10,DRIVE CON,NaN,NaN,800.0,4.2,100.0,L,2008.0,2008.0,80.0,NaN,50.0,1562.0,46706951200000.html

In [28]:
merged_df[merged_df['parcel_number'] == 66020121510000]

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value_x,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,ALP_description,ALP_actual_area,ALP_percent_of_base,ALP_effective_area,ALP_replacement_cost_new,AOF_description,AOF_actual_area,AOF_percent_of_base,AOF_effective_area,AOF_replacement_cost_new,APB_description,APB_actual_area,APB_percent_of_base,APB_effective_area,APB_replacement_cost_new,APT_description,APT_actual_area,APT_percent_of_base,APT_effective_area,APT_replacement_cost_new,BAS_description,BAS_actual_area,BAS_percent_of_base,BAS_effective_area,BAS_replacement_cost_new,BOF_description,BOF_actual_area,BOF_percent_of_base,BOF_effective_area,BOF_replacement_cost_new,CAN_description,CAN_actual_area,CAN_percent_of_base,CAN_effective_area,CAN_replacement_cost_new,CAS_description,CAS_actual_area,CAS_percent_of_base,CAS_effective_area,CAS_replacement_cost_new,CBM_description,CBM_actual_area,CBM_percent_of_base,CBM_effective_area,CBM_replacement_cost_new,CDN_description,CDN_actual_area,CDN_percent_of_base,CDN_effective_area,CDN_replacement_cost_new,CLP_description,CLP_actual_area,CLP_percent_of_base,CLP_effective_area,CLP_replacement_cost_new,FAT_description,FAT_actual_area,FAT_percent_of_base,FAT_effective_area,FAT_replacement_cost_new,FBM_description,FBM_actual_area,FBM_percent_of_base,FBM_effective_area,FBM_replacement_cost_new,FCB_description,FCB_actual_area,FCB_percent_of_base,FCB_effective_area,FCB_replacement_cost_new,FCP_description,FCP_actual_area,FCP_percent_of_base,FCP_effective_area,FCP_replacement_cost_new,FDC_description,FDC_actual_area,FDC_percent_of_base,FDC_effective_area,FDC_replacement_cost_new,FDG_description,FDG_actual_area,FDG_percent_of_base,FDG_effective_area,FDG_replacement_cost_new,FDU_description,FDU_actual_area,FDU_percent_of_base,FDU_effective_area,FDU_replacement_cost_new,FEP_description,FEP_actual_area,FEP_percent_of_base,FEP_effective_area,FEP_replacement_cost_new,FGB_description,FGB_actual_area,FGB_percent_of_base,FGB_effective_area,FGB_replacement_cost_new,FGD_description,FGD_actual_area,FGD_percent_of_base,FGD_effective_area,FGD_replacement_cost_new,FGR_description,FGR_actual_area,FGR_percent_of_base,FGR_effective_area,FGR_replacement_cost_new,FHS_description,FHS_actual_area,FHS_percent_of_base,FHS_effective_area,FHS_replacement_cost_new,FOF_description,FOF_actual_area,FOF_percent_of_base,FOF_effective_area,FOF_replacement_cost_new,FOG_description,FOG_actual_area,FOG_percent_of_base,FOG_effective_area,FOG_replacement_cost_new,FOP_description,FOP_actual_area,FOP_percent_of_base,FOP_effective_area,FOP_replacement_cost_new,FSP_description,FSP_actual_area,FSP_percent_of_base,FSP_effective_area,FSP_replacement_cost_new,FST_description,FST_actual_area,FST_percent_of_base,FST_effective_area,FST_replacement_cost_new,FUS_description,FUS_actual_area,FUS_percent_of_base,FUS_effective_area,FUS_replacement_cost_new,FUT_description,FUT_actual_area,FUT_percent_of_base,FUT_effective_area,FUT_replacement_cost_new,GOF_description,GOF_actual_area,GOF_percent_of_base,GOF_effective_area,GOF_replacement_cost_new,LAB_description,LAB_actual_area,LAB_percent_of_base,LAB_effective_area,LAB_replacement_cost_new,LFG_description,LFG_actual_area,LFG_percent_of_base,LFG_effective_area,LFG_replacement_cost_new,LFT_description,LFT_actual_area,LFT_percent_of_base,LFT_effective_area,LFT_replacement_cost_new,LLF_description,LLF_actual_area,LLF_percent_of_base,LLF_effective_area,LLF_replacement_cost_new,LLS_description,LLS_actual_area,LLS_percent_of_base,LLS_effective_area,LLS_replacement_cost_new,LLU_description,LLU_actual_area,LLU_percent_of_base,LLU_effective_area,LLU_replacement_cost_new,LUG_description,LUG_actual_area,LUG_percent_of_base,LUG_effective_area,LUG_replacement_cost_new,MEZ_description,MEZ_actual_area,MEZ_percent_of_base,MEZ_effective_area,MEZ_replacement_cost_new,MFG_description,MFG_actual_area,MFG_percent_of_base,MFG_effective_area,MFG_replacement_cost_new,MFM_description,MFM_actual_area,MFM_percent_of_base,MFM_effective_area,MFM_replacement_cost_new,MOF_description,MOF_actual_area,MOF_percent_of_base,MOF_effective_area,MOF_replacement_cost_new,OEB_description,OEB_actual_area,OEB_percent_of_base,OEB_effective_area,OEB_replacement_cost_new,PTO_description,PTO_actual_area,PTO_percent_of_base,PTO_effective_area,PTO_replacement_cost_new,PTR_description,PTR_actual_area,PTR_percent_of_base,PTR_effective_area,PTR_replacement_cost_new,SBM_description,SBM_actual_area,SBM_percent_of_base,SBM_effective_area,SBM_replacement_cost_new,SDA_description,SDA_actual_area,SDA_percent_of_base,SDA_effective_area,SDA_replacement_cost_new,SFB_description,SFB_actual_area,SFB_percent_of_base,SFB_effective_area,SFB_replacement_cost_new,SPA_description,SPA_actual_area,SPA_percent_of_base,SPA_effective_area,SPA_replacement_cost_new,SRH_description,SRH_actual_area,SRH_percent_of_base,SRH_effective_area,SRH_replacement_cost_new,SRU_description,SRU_actual_area,SRU_percent_of_base,SRU_effective_area,SRU_replacement_cost_new,STP_description,STP_actual_area,STP_percent_of_base,STP_effective_area,STP_replacement_cost_new,TER_description,TER_actual_area,TER_percent_of_base,TER_effective_area,TER_replacement_cost_new,UAT_description,UAT_actual_area,UAT_percent_of_base,UAT_effective_area,UAT_replacement_cost_new,UBM_description,UBM_actual_area,UBM_percent_of_base,UBM_effective_area,UBM_replacement_cost_new,UCB_description,UCB_actual_area,UCB_percent_of_base,UCB_effective_area,UCB_replacement_cost_new,UCP_description,UCP_actual_area,UCP_percent_of_base,UCP_effective_area,UCP_replacement_cost_new,UDC_description,UDC_actual_area,UDC_percent_of_base,UDC_effective_area,UDC_replacement_cost_new,UDG_description,UDG_actual_area,UDG_percent_of_base,UDG_effective_area,UDG_replacement_cost_new,UDS_description,UDS_actual_area,UDS_percent_of_base,UDS_effective_area,UDS_replacement_cost_new,UDU_description,UDU_actual_area,UDU_percent_of_base,UDU_effective_area,UDU_replacement_cost_new,UEP_description,UEP_actual_area,UEP_percent_of_base,UEP_effective_area,UEP_replacement_cost_new,UGB_description,UGB_actual_area,UGB_percent_of_base,UGB_effective_area,UGB_replacement_cost_new,UGD_description,UGD_actual_area,UGD_percent_of_base,UGD_effective_area,UGD_replacement_cost_new,UGR_description,UGR_actual_area,UGR_percent_of_base,UGR_effective_area,UGR_replacement_cost_new,ULP_description,ULP_actual_area,ULP_percent_of_base,ULP_effective_area,ULP_replacement_cost_new,UOG_description,UOG_actual_area,UOG_percent_of_base,UOG_effective_area,UOG_replacement_cost_new,UOP_description,UOP_actual_area,UOP_percent_of_base,UOP_effective_area,UOP_replacement_cost_new,USP_description,USP_actual_area,USP_percent_of_base,USP_effective_area,USP_replacement_cost_new,UST_description,UST_actual_area,UST_percent_of_base,UST_effective_area,UST_replacement_cost_new,UUS_description,UUS_actual_area,UUS_percent_of_base,UUS_effective_area,UUS_replacement_cost_new,UUT_description,UUT_actual_area,UUT_percent_of_base,UUT_effective_area,UUT_replacement_cost_new,WDD_description,WDD_actual_area,WDD_percent_of_base,WDD_effective_area,WDD_replacement_cost_new,Air Conditioning Type_detail_description,Air Conditioning Type_point_value,Air Conditioning Type_percentage,Average Rooms Per Floor_detail_description,Average Rooms Per Floor_point_value,Average Rooms Per Floor_percentage,Bedrooms/Bathrooms/Half-Bathrooms_detail_description,Bedrooms/Bathrooms/Half-Bathrooms_point_value,Bedrooms/Bathrooms/Half-Bathrooms_percentage,Ceiling & Insulation_detail_description,Ceiling & Insulation_point_value,Ceiling & Insulation_percentage,Commercial Heat & Air_detail_description,Commercial Heat & Air_point_value,Commercial Heat & Air_percentage,Common Owned Percentage_detail_description,Common Owned Percentage_point_value,Common Owned Percentage_percentage,Common Wall Percentage_detail_description,Common Wall Percentage_point_value,Common Wall Percentage_percentage,Condo Land Type_detail_description,Condo Land Type_point_value,Condo Land Type_percentage,Exterior Walls_detail_description,Exterior Walls_point_value,Exterior Walls_percentage,Fireplace_detail_description,Fireplace_point_value,Fireplace_percentage,Floor Number_detail_description,Floor Number_point_value,Floor Number_percentage,Foundation_detail_description,Foundation_point_value,Foundation_percentage,Heating Fuel_detail_description,Heating Fuel_point_value,Heating Fuel_percentage,Heating Type_detail_description,Heating Type_point_value,Heating Type_percentage,Interior Floor Cover_detail_description,Interior Floor Cover_point_value,Interior Floor Cover_percentage,Interior Wall Construction_detail_description,Interior Wall Construction_point_value,Interior Wall Construction_percentage,Plumbing Fixtures_detail_description,Plumbing Fixtures_point_value,Plumbing Fixtures_percentage,Roofing Cover_detail_description,Roofing Cover_point_value,Roofing Cover_percentage,Roofing Structure_detail_description,Roofing Structure_point_value,Roofing Structure_percentage,Structural Frame_detail_description,Structural Frame_point_value,Structural Frame_percentage,Sub Floor System_detail_description,Sub Floor System_point_value,Sub Floor System_percentage,Unit Count_detail_description,Unit Count_point_value,Unit Count_percentage,Unit Location_detail_description,Unit Location_point_value,Unit Location_percentage,Bathrooms_base_area,Bathrooms_upper_level,Bathrooms_lower_level,Bedrooms_base_area,Bedrooms_upper_level,Bedrooms_lower_level,Half-Bathrooms_base_area,Half-Bathrooms_upper_level,Half-Bathrooms_lower_level,bldg_number,code,description,length,width,units,unit_price,condition_factor,l_b,actual_year_built,effective_year_built,annual_depreciation,depreciation_override,net_percent_good,appraised_value_y,page_save
162248,66020121510000,1,2006,2006,3420.0,1110.0,4530,165170.0,NaN,2245 GOLD HILL RD E MT PLEASANT,49,6,40.0,88.8,412920.0,49 - WAREHOUSE - PREFAB,06 - WAREHOUSE/INDUSTRIAL,3,CB,Average,2024,1.0,4,CB,MF4,2024,1.04,Size,CB,Size,2024.0,1.19,20.0,CB,Non-Std Wall Height,2024.0,1.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1950.0,100.0,1950.0,173160.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Carport, Finished",600.0,40.0,240.0,21312.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Office, Fair",1470.0,150.0,2205.0,195804.0,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",510.0,50.0,255.0,22644.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-Central,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,12-No Ceiling - No Insulation,0.0,100.0,1-None,0.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24-Modular Metal,20.0,100.0,2-Pre Fabricated,0.0,100.0,NaN,NaN,NaN,4-Spread Footing,8.0,100.0,04-Electric,1.0,100.0,10-Heat Pump,6.0,100.0,04-Concrete Coated,4.0,100.0,1-Masonry or Minimum,5.0,100.0,3.00,5.0,0.0,12-Metal,8.0,100.0,10-Steel Frame or Truss,18.0,100.0,06-Steel,15.0,100.0,2-Slab on Grade-Residential/Commercial,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,DRIVE CON,43.0,24.0,1032.0,4.2,100.0,NaN,2011.0,2011.0,65.0,NaN,50.0,1907.0,66020121510000.html
162249,66020121510000,1,2006,2006,3420.0,1110.0,4530,165170.0,NaN,2245 GOLD HILL RD E MT PLEASANT,49,6,40.0,88.8,412920.0,49 - WAREHOUSE - PREFAB,06 - WAREHOUSE/INDUSTRIAL,3,CB,Average,2024,1.0,4,CB,MF4,2024,1.04,Size,CB,Size,2024.0,1.19,20.0,CB,Non-Std Wall Height,2024.0,1.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1950.0,100.0,1950.0,173160.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Carport, Finished",600.0,40.0,240.0,21312.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Office, Fair",1470.0,150.0,2205.0,195804.0,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",510.0,50.0,255.0,22644.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-Central,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,12-No Ceiling - No Insulation,0.0,100.0,1-None,0.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24-Modular Metal,20.0,100.0,2-Pre Fabricated,0.0,100.0,NaN,NaN,NaN,4-Spread Footing,8.0,100.0,04-Electric,1.0,100.0,10-Heat Pump,6.0,100.0,04-Concrete Coated,4.0,100.0,1-Masonry or Minimum,5.0,100.0,3.00,5.0,0.0,12-Metal,8.0,100.0,10-Steel Frame or Truss,18.0,100.0,06-Steel,15.0,100.0,2-Slab on Grade-Residential/Commercial,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,FIREPL PTO,NaN,NaN,1.0,6200.0,100.0,NaN,2011.0,2011.0,39.0,NaN,61.0,3782.0,66020121510000.html
162250,66020121510000,1,2006,2006,3420.0,1110.0,4530,165170.0,NaN,2245 GOLD HILL RD E MT PLEASANT,49,6,40.0,88.8,412920.0,49 - WAREHOUSE - PREFAB,06 - WAREHOUSE/INDUSTRIAL,3,CB,Average,2024,1.0,4,CB,MF4,2024,1.04,Size,CB,Size,2024.0,1.19,20.0,CB,Non-Std Wall Height,2024.0,1.13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1950.0,100.0,1950.0,173160.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Carport, Finished",600.0,40.0,240.0,21312.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Office, Fair",1470.0,150.0,2205.0,195804.0,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",510.0,50.0,255.0,22644.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-Central,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,12-No Ceiling - No Insulation,0.0,100.0,1-None,0.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24-Modular Metal,20.0,100.0,2-Pre Fabricated,0.0,100.0,NaN,NaN,NaN,4-Spread Footing,8.0,100.0,04-Electric,1.0,100.0,10-Heat Pump,6.0,100.0,04-Concrete Coated,4.0,100.0,1-Masonry or Minimum,5.0,100.0,3.00,5.0,0.0,12-Metal,8.0,100.0,10-Steel Frame or Truss,18.0,100.0,06-Steel,15.0,100.0,2-Slab on Grade-Residential/Commercial,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,STG QUONST,30.0,40.0,1200.0,25.0,100.0,NaN,2020.0,2020.0,12.0,NaN,88.0,30360.0,66020121510000.html

In [30]:
merged_df[merged_df.duplicated()]

Empty DataFrame
Columns: [parcel_number, bldg_id, ayb, eyb, heated_area, non_heated_area, total_area, appraised_value_x, building_name, property_address, use, model, percent_good, base_rate, replacement_cost_new, use_code_description, model_description, quality_code, quality_countycode, quality_description, quality_valuationyear, quality_value, shape_design_code, shape_design_countycode, shape_design_description, shape_design_valuationyear, shape_design_value, size_code, size_countycode, size_description, size_valuationyear, size_value, non-std_wall_height_code, non-std_wall_height_countycode, non-std_wall_height_description, non-std_wall_height_valuationyear, non-std_wall_height_value, ALP_description, ALP_actual_area, ALP_percent_of_base, ALP_effective_area, ALP_replacement_cost_new, AOF_description, AOF_actual_area, AOF_percent_of_base, AOF_effective_area, AOF_replacement_cost_new, APB_description, APB_actual_area, APB_percent_of_base, APB_effective_area, APB_replacement_cost_new, APT_description, APT_actual_area, APT_percent_of_base, APT_effective_area, APT_replacement_cost_new, BAS_description, BAS_actual_area, BAS_percent_of_base, BAS_effective_area, BAS_replacement_cost_new, BOF_description, BOF_actual_area, BOF_percent_of_base, BOF_effective_area, BOF_replacement_cost_new, CAN_description, CAN_actual_area, CAN_percent_of_base, CAN_effective_area, CAN_replacement_cost_new, CAS_description, CAS_actual_area, CAS_percent_of_base, CAS_effective_area, CAS_replacement_cost_new, CBM_description, CBM_actual_area, CBM_percent_of_base, CBM_effective_area, CBM_replacement_cost_new, CDN_description, CDN_actual_area, CDN_percent_of_base, CDN_effective_area, CDN_replacement_cost_new, CLP_description, CLP_actual_area, CLP_percent_of_base, CLP_effective_area, CLP_replacement_cost_new, FAT_description, FAT_actual_area, FAT_percent_of_base, FAT_effective_area, FAT_replacement_cost_new, FBM_description, FBM_actual_area, FBM_percent_of_base, ...]
Index: []

In [32]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162251 entries, 0 to 162250
Columns: 496 entries, parcel_number to page_save
dtypes: float64(371), int64(10), object(115)
memory usage: 614.0+ MB

In [33]:
empty_cols = merged_df.columns[merged_df.isna().all()]

print(empty_cols.tolist())

['Common Wall Percentage_detail_description']

In [31]:
# values_cols = [
#     "detail_description",
#     "point_value",
#     "percentage"
# ]


# agg_map = {
#     "detail_description": "first",
#     "point_value": "sum",
#     "percentage": "sum"
# }

# grouped_df4 = (
#     df4
#     .groupby(["parcel_number", "page_save", "element"], as_index=False)
#     .agg(agg_map)
# )


# pivot_df4 = (
#     grouped_df4
#     .set_index(["parcel_number", "page_save", "element"])[value_cols]
#     .unstack("element")
# )


# element_order = sorted(grouped_df4["element"].unique())

# ordered_cols = []
# for el in element_order:
#     for col in value_cols:
#         ordered_cols.append((col, el))

# pivot_df4 = pivot_df4[ordered_cols]


# pivot_df4.columns = [
#     f"{el}_{col}"
#     for col, el in pivot_df4.columns
# ]

# pivot_df4 = pivot_df4.reset_index()


# merged_df = pd.merge(
#     merged_df,
#     pivot_df4,
#     on=["parcel_number", "page_save"],
#     how="left"
# )

# cols = [c for c in merged_df.columns if c != "page_save"] + ["page_save"]
# merged_df = merged_df[cols]

In [ ]:
# import pandas as pd
# import glob
# import os

# # Folder containing your CSV files
# folder_path = r"D:\North Carolina\Cabarrus\Property\clean"

# # Find all CSV files
# csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

# # Read the first file
# merged_df = pd.read_csv(csv_files[0])

# # Merge the rest one by one
# for file in csv_files[1:]:
#     df = pd.read_csv(file)
#     merged_df = merged_df.merge(
#         df,
#         on=["parcel_number", "page_save"],
#         how="inner"     # inner merge: only matching rows
#     )

# # Save final merged file
# merged_df.to_csv("us_nc_37025_data_prop_building1_silver_20251127.csv", index=False)

# print("Done! Merged file saved as merged_parcel_page.csv")

In [ ]:
# merged_df
# pd.set_option('display.max_columns', None)
# merged_df

In [ ]:
# merged_df[merged_df.duplicated()]

In [37]:
merged_df[merged_df['parcel_number']==46707318010000]

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value_x,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,ALP_description,ALP_actual_area,ALP_percent_of_base,ALP_effective_area,ALP_replacement_cost_new,AOF_description,AOF_actual_area,AOF_percent_of_base,AOF_effective_area,AOF_replacement_cost_new,APB_description,APB_actual_area,APB_percent_of_base,APB_effective_area,APB_replacement_cost_new,APT_description,APT_actual_area,APT_percent_of_base,APT_effective_area,APT_replacement_cost_new,BAS_description,BAS_actual_area,BAS_percent_of_base,BAS_effective_area,BAS_replacement_cost_new,BOF_description,BOF_actual_area,BOF_percent_of_base,BOF_effective_area,BOF_replacement_cost_new,CAN_description,CAN_actual_area,CAN_percent_of_base,CAN_effective_area,CAN_replacement_cost_new,CAS_description,CAS_actual_area,CAS_percent_of_base,CAS_effective_area,CAS_replacement_cost_new,CBM_description,CBM_actual_area,CBM_percent_of_base,CBM_effective_area,CBM_replacement_cost_new,CDN_description,CDN_actual_area,CDN_percent_of_base,CDN_effective_area,CDN_replacement_cost_new,CLP_description,CLP_actual_area,CLP_percent_of_base,CLP_effective_area,CLP_replacement_cost_new,FAT_description,FAT_actual_area,FAT_percent_of_base,FAT_effective_area,FAT_replacement_cost_new,FBM_description,FBM_actual_area,FBM_percent_of_base,FBM_effective_area,FBM_replacement_cost_new,FCB_description,FCB_actual_area,FCB_percent_of_base,FCB_effective_area,FCB_replacement_cost_new,FCP_description,FCP_actual_area,FCP_percent_of_base,FCP_effective_area,FCP_replacement_cost_new,FDC_description,FDC_actual_area,FDC_percent_of_base,FDC_effective_area,FDC_replacement_cost_new,FDG_description,FDG_actual_area,FDG_percent_of_base,FDG_effective_area,FDG_replacement_cost_new,FDU_description,FDU_actual_area,FDU_percent_of_base,FDU_effective_area,FDU_replacement_cost_new,FEP_description,FEP_actual_area,FEP_percent_of_base,FEP_effective_area,FEP_replacement_cost_new,FGB_description,FGB_actual_area,FGB_percent_of_base,FGB_effective_area,FGB_replacement_cost_new,FGD_description,FGD_actual_area,FGD_percent_of_base,FGD_effective_area,FGD_replacement_cost_new,FGR_description,FGR_actual_area,FGR_percent_of_base,FGR_effective_area,FGR_replacement_cost_new,FHS_description,FHS_actual_area,FHS_percent_of_base,FHS_effective_area,FHS_replacement_cost_new,FOF_description,FOF_actual_area,FOF_percent_of_base,FOF_effective_area,FOF_replacement_cost_new,FOG_description,FOG_actual_area,FOG_percent_of_base,FOG_effective_area,FOG_replacement_cost_new,FOP_description,FOP_actual_area,FOP_percent_of_base,FOP_effective_area,FOP_replacement_cost_new,FSP_description,FSP_actual_area,FSP_percent_of_base,FSP_effective_area,FSP_replacement_cost_new,FST_description,FST_actual_area,FST_percent_of_base,FST_effective_area,FST_replacement_cost_new,FUS_description,FUS_actual_area,FUS_percent_of_base,FUS_effective_area,FUS_replacement_cost_new,FUT_description,FUT_actual_area,FUT_percent_of_base,FUT_effective_area,FUT_replacement_cost_new,GOF_description,GOF_actual_area,GOF_percent_of_base,GOF_effective_area,GOF_replacement_cost_new,LAB_description,LAB_actual_area,LAB_percent_of_base,LAB_effective_area,LAB_replacement_cost_new,LFG_description,LFG_actual_area,LFG_percent_of_base,LFG_effective_area,LFG_replacement_cost_new,LFT_description,LFT_actual_area,LFT_percent_of_base,LFT_effective_area,LFT_replacement_cost_new,LLF_description,LLF_actual_area,LLF_percent_of_base,LLF_effective_area,LLF_replacement_cost_new,LLS_description,LLS_actual_area,LLS_percent_of_base,LLS_effective_area,LLS_replacement_cost_new,LLU_description,LLU_actual_area,LLU_percent_of_base,LLU_effective_area,LLU_replacement_cost_new,LUG_description,LUG_actual_area,LUG_percent_of_base,LUG_effective_area,LUG_replacement_cost_new,MEZ_description,MEZ_actual_area,MEZ_percent_of_base,MEZ_effective_area,MEZ_replacement_cost_new,MFG_description,MFG_actual_area,MFG_percent_of_base,MFG_effective_area,MFG_replacement_cost_new,MFM_description,MFM_actual_area,MFM_percent_of_base,MFM_effective_area,MFM_replacement_cost_new,MOF_description,MOF_actual_area,MOF_percent_of_base,MOF_effective_area,MOF_replacement_cost_new,OEB_description,OEB_actual_area,OEB_percent_of_base,OEB_effective_area,OEB_replacement_cost_new,PTO_description,PTO_actual_area,PTO_percent_of_base,PTO_effective_area,PTO_replacement_cost_new,PTR_description,PTR_actual_area,PTR_percent_of_base,PTR_effective_area,PTR_replacement_cost_new,SBM_description,SBM_actual_area,SBM_percent_of_base,SBM_effective_area,SBM_replacement_cost_new,SDA_description,SDA_actual_area,SDA_percent_of_base,SDA_effective_area,SDA_replacement_cost_new,SFB_description,SFB_actual_area,SFB_percent_of_base,SFB_effective_area,SFB_replacement_cost_new,SPA_description,SPA_actual_area,SPA_percent_of_base,SPA_effective_area,SPA_replacement_cost_new,SRH_description,SRH_actual_area,SRH_percent_of_base,SRH_effective_area,SRH_replacement_cost_new,SRU_description,SRU_actual_area,SRU_percent_of_base,SRU_effective_area,SRU_replacement_cost_new,STP_description,STP_actual_area,STP_percent_of_base,STP_effective_area,STP_replacement_cost_new,TER_description,TER_actual_area,TER_percent_of_base,TER_effective_area,TER_replacement_cost_new,UAT_description,UAT_actual_area,UAT_percent_of_base,UAT_effective_area,UAT_replacement_cost_new,UBM_description,UBM_actual_area,UBM_percent_of_base,UBM_effective_area,UBM_replacement_cost_new,UCB_description,UCB_actual_area,UCB_percent_of_base,UCB_effective_area,UCB_replacement_cost_new,UCP_description,UCP_actual_area,UCP_percent_of_base,UCP_effective_area,UCP_replacement_cost_new,UDC_description,UDC_actual_area,UDC_percent_of_base,UDC_effective_area,UDC_replacement_cost_new,UDG_description,UDG_actual_area,UDG_percent_of_base,UDG_effective_area,UDG_replacement_cost_new,UDS_description,UDS_actual_area,UDS_percent_of_base,UDS_effective_area,UDS_replacement_cost_new,UDU_description,UDU_actual_area,UDU_percent_of_base,UDU_effective_area,UDU_replacement_cost_new,UEP_description,UEP_actual_area,UEP_percent_of_base,UEP_effective_area,UEP_replacement_cost_new,UGB_description,UGB_actual_area,UGB_percent_of_base,UGB_effective_area,UGB_replacement_cost_new,UGD_description,UGD_actual_area,UGD_percent_of_base,UGD_effective_area,UGD_replacement_cost_new,UGR_description,UGR_actual_area,UGR_percent_of_base,UGR_effective_area,UGR_replacement_cost_new,ULP_description,ULP_actual_area,ULP_percent_of_base,ULP_effective_area,ULP_replacement_cost_new,UOG_description,UOG_actual_area,UOG_percent_of_base,UOG_effective_area,UOG_replacement_cost_new,UOP_description,UOP_actual_area,UOP_percent_of_base,UOP_effective_area,UOP_replacement_cost_new,USP_description,USP_actual_area,USP_percent_of_base,USP_effective_area,USP_replacement_cost_new,UST_description,UST_actual_area,UST_percent_of_base,UST_effective_area,UST_replacement_cost_new,UUS_description,UUS_actual_area,UUS_percent_of_base,UUS_effective_area,UUS_replacement_cost_new,UUT_description,UUT_actual_area,UUT_percent_of_base,UUT_effective_area,UUT_replacement_cost_new,WDD_description,WDD_actual_area,WDD_percent_of_base,WDD_effective_area,WDD_replacement_cost_new,Air Conditioning Type_detail_description,Air Conditioning Type_point_value,Air Conditioning Type_percentage,Average Rooms Per Floor_detail_description,Average Rooms Per Floor_point_value,Average Rooms Per Floor_percentage,Bedrooms/Bathrooms/Half-Bathrooms_detail_description,Bedrooms/Bathrooms/Half-Bathrooms_point_value,Bedrooms/Bathrooms/Half-Bathrooms_percentage,Ceiling & Insulation_detail_description,Ceiling & Insulation_point_value,Ceiling & Insulation_percentage,Commercial Heat & Air_detail_description,Commercial Heat & Air_point_value,Commercial Heat & Air_percentage,Common Owned Percentage_detail_description,Common Owned Percentage_point_value,Common Owned Percentage_percentage,Common Wall Percentage_detail_description,Common Wall Percentage_point_value,Common Wall Percentage_percentage,Condo Land Type_detail_description,Condo Land Type_point_value,Condo Land Type_percentage,Exterior Walls_detail_description,Exterior Walls_point_value,Exterior Walls_percentage,Fireplace_detail_description,Fireplace_point_value,Fireplace_percentage,Floor Number_detail_description,Floor Number_point_value,Floor Number_percentage,Foundation_detail_description,Foundation_point_value,Foundation_percentage,Heating Fuel_detail_description,Heating Fuel_point_value,Heating Fuel_percentage,Heating Type_detail_description,Heating Type_point_value,Heating Type_percentage,Interior Floor Cover_detail_description,Interior Floor Cover_point_value,Interior Floor Cover_percentage,Interior Wall Construction_detail_description,Interior Wall Construction_point_value,Interior Wall Construction_percentage,Plumbing Fixtures_detail_description,Plumbing Fixtures_point_value,Plumbing Fixtures_percentage,Roofing Cover_detail_description,Roofing Cover_point_value,Roofing Cover_percentage,Roofing Structure_detail_description,Roofing Structure_point_value,Roofing Structure_percentage,Structural Frame_detail_description,Structural Frame_point_value,Structural Frame_percentage,Sub Floor System_detail_description,Sub Floor System_point_value,Sub Floor System_percentage,Unit Count_detail_description,Unit Count_point_value,Unit Count_percentage,Unit Location_detail_description,Unit Location_point_value,Unit Location_percentage,Bathrooms_base_area,Bathrooms_upper_level,Bathrooms_lower_level,Bedrooms_base_area,Bedrooms_upper_level,Bedrooms_lower_level,Half-Bathrooms_base_area,Half-Bathrooms_upper_level,Half-Bathrooms_lower_level,bldg_number,code,description,length,width,units,unit_price,condition_factor,l_b,actual_year_built,effective_year_built,annual_depreciation,depreciation_override,net_percent_good,appraised_value_y,page_save
6,46707318010000,1,2022,2022,1859.0,532.0,2391,308080.0,NaN,10463 DALTON WOODS CT NW HUNTERSVILLE,09,1,98.0,167.04,314369.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,4,CB,Above Average,2024,1.1,5,CB,MF5,2024,1.1,Size,CB,Size,2024.0,1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,780.0,100.0,780.0,130291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",380.0,45.0,171.0,28564.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1079.0,85.0,917.0,153176.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,120.0,5.0,6.0,1002.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stoop,32.0,25.0,8.0,1336.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-Central,4.0,100.0,NaN,NaN,NaN,3/2/1,13.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10-Aluminum/Vinyl Siding,30.0,100.0,1-None,0.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,04-Electric,1.0,100.0,10-Heat Pump,4.0,100.0,09-Pine or Soft Woods,10.0,100.0,5-Drywall/Sheetrock,26.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,03-Gable,7.0,100.0,NaN,NaN,NaN,2-Slab on Grade-Residential/Commercial,5.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,3.0,0.0,1.0,0.0,0.0,1.0,NaN,DRIVE CON,36.0,16.0,576.0,4.2,100.0,NaN,2022.0,2022.0,10.0,NaN,90.0,2177.0,46707318010000.html
7,46707318010000,1,2022,2022,1859.0,532.0,2391,308080.0,NaN,10463 DALTON WOODS CT NW HUNTERSVILLE,09,1,98.0,167.04,314369.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,4,CB,Above Average,2024,1.1,5,CB,MF5,2024,1.1,Size,CB,Size,2024.0,1.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,780.0,100.0,780.0,130291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",380.0,45.0,171.0,28564.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1079.0,85.0,917.0,153176.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,120.0,5.0,6.0,1002.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stoop,32.0,25.0,8.0,1336.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-Central,4.0,100.0,NaN,NaN,NaN,3/2/1,13.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10-Aluminum/Vinyl Siding,30.0,100.0,1-None,0.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,04-Electric,1.0,100.0,10-Heat Pump,4.0,100.0,09-Pine or Soft Woods,10.0,100.0,5-Drywall/Sheetrock,26.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,03-Gable,7.0,100.0,NaN,NaN,NaN,2-Slab on Grade-Residential/Commercial,5.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,3.0,0.0,1.0,0.0,0.0,1.0,NaN,FEN PVC PR,NaN,NaN,8.0,31.0,100.0,NaN,2022.0,2022.0,10.0,NaN,90.0,223.0,46707318010000.html

In [34]:
merged_df[merged_df['parcel_number']==46706778400000]

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value_x,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,ALP_description,ALP_actual_area,ALP_percent_of_base,ALP_effective_area,ALP_replacement_cost_new,AOF_description,AOF_actual_area,AOF_percent_of_base,AOF_effective_area,AOF_replacement_cost_new,APB_description,APB_actual_area,APB_percent_of_base,APB_effective_area,APB_replacement_cost_new,APT_description,APT_actual_area,APT_percent_of_base,APT_effective_area,APT_replacement_cost_new,BAS_description,BAS_actual_area,BAS_percent_of_base,BAS_effective_area,BAS_replacement_cost_new,BOF_description,BOF_actual_area,BOF_percent_of_base,BOF_effective_area,BOF_replacement_cost_new,CAN_description,CAN_actual_area,CAN_percent_of_base,CAN_effective_area,CAN_replacement_cost_new,CAS_description,CAS_actual_area,CAS_percent_of_base,CAS_effective_area,CAS_replacement_cost_new,CBM_description,CBM_actual_area,CBM_percent_of_base,CBM_effective_area,CBM_replacement_cost_new,CDN_description,CDN_actual_area,CDN_percent_of_base,CDN_effective_area,CDN_replacement_cost_new,CLP_description,CLP_actual_area,CLP_percent_of_base,CLP_effective_area,CLP_replacement_cost_new,FAT_description,FAT_actual_area,FAT_percent_of_base,FAT_effective_area,FAT_replacement_cost_new,FBM_description,FBM_actual_area,FBM_percent_of_base,FBM_effective_area,FBM_replacement_cost_new,FCB_description,FCB_actual_area,FCB_percent_of_base,FCB_effective_area,FCB_replacement_cost_new,FCP_description,FCP_actual_area,FCP_percent_of_base,FCP_effective_area,FCP_replacement_cost_new,FDC_description,FDC_actual_area,FDC_percent_of_base,FDC_effective_area,FDC_replacement_cost_new,FDG_description,FDG_actual_area,FDG_percent_of_base,FDG_effective_area,FDG_replacement_cost_new,FDU_description,FDU_actual_area,FDU_percent_of_base,FDU_effective_area,FDU_replacement_cost_new,FEP_description,FEP_actual_area,FEP_percent_of_base,FEP_effective_area,FEP_replacement_cost_new,FGB_description,FGB_actual_area,FGB_percent_of_base,FGB_effective_area,FGB_replacement_cost_new,FGD_description,FGD_actual_area,FGD_percent_of_base,FGD_effective_area,FGD_replacement_cost_new,FGR_description,FGR_actual_area,FGR_percent_of_base,FGR_effective_area,FGR_replacement_cost_new,FHS_description,FHS_actual_area,FHS_percent_of_base,FHS_effective_area,FHS_replacement_cost_new,FOF_description,FOF_actual_area,FOF_percent_of_base,FOF_effective_area,FOF_replacement_cost_new,FOG_description,FOG_actual_area,FOG_percent_of_base,FOG_effective_area,FOG_replacement_cost_new,FOP_description,FOP_actual_area,FOP_percent_of_base,FOP_effective_area,FOP_replacement_cost_new,FSP_description,FSP_actual_area,FSP_percent_of_base,FSP_effective_area,FSP_replacement_cost_new,FST_description,FST_actual_area,FST_percent_of_base,FST_effective_area,FST_replacement_cost_new,FUS_description,FUS_actual_area,FUS_percent_of_base,FUS_effective_area,FUS_replacement_cost_new,FUT_description,FUT_actual_area,FUT_percent_of_base,FUT_effective_area,FUT_replacement_cost_new,GOF_description,GOF_actual_area,GOF_percent_of_base,GOF_effective_area,GOF_replacement_cost_new,LAB_description,LAB_actual_area,LAB_percent_of_base,LAB_effective_area,LAB_replacement_cost_new,LFG_description,LFG_actual_area,LFG_percent_of_base,LFG_effective_area,LFG_replacement_cost_new,LFT_description,LFT_actual_area,LFT_percent_of_base,LFT_effective_area,LFT_replacement_cost_new,LLF_description,LLF_actual_area,LLF_percent_of_base,LLF_effective_area,LLF_replacement_cost_new,LLS_description,LLS_actual_area,LLS_percent_of_base,LLS_effective_area,LLS_replacement_cost_new,LLU_description,LLU_actual_area,LLU_percent_of_base,LLU_effective_area,LLU_replacement_cost_new,LUG_description,LUG_actual_area,LUG_percent_of_base,LUG_effective_area,LUG_replacement_cost_new,MEZ_description,MEZ_actual_area,MEZ_percent_of_base,MEZ_effective_area,MEZ_replacement_cost_new,MFG_description,MFG_actual_area,MFG_percent_of_base,MFG_effective_area,MFG_replacement_cost_new,MFM_description,MFM_actual_area,MFM_percent_of_base,MFM_effective_area,MFM_replacement_cost_new,MOF_description,MOF_actual_area,MOF_percent_of_base,MOF_effective_area,MOF_replacement_cost_new,OEB_description,OEB_actual_area,OEB_percent_of_base,OEB_effective_area,OEB_replacement_cost_new,PTO_description,PTO_actual_area,PTO_percent_of_base,PTO_effective_area,PTO_replacement_cost_new,PTR_description,PTR_actual_area,PTR_percent_of_base,PTR_effective_area,PTR_replacement_cost_new,SBM_description,SBM_actual_area,SBM_percent_of_base,SBM_effective_area,SBM_replacement_cost_new,SDA_description,SDA_actual_area,SDA_percent_of_base,SDA_effective_area,SDA_replacement_cost_new,SFB_description,SFB_actual_area,SFB_percent_of_base,SFB_effective_area,SFB_replacement_cost_new,SPA_description,SPA_actual_area,SPA_percent_of_base,SPA_effective_area,SPA_replacement_cost_new,SRH_description,SRH_actual_area,SRH_percent_of_base,SRH_effective_area,SRH_replacement_cost_new,SRU_description,SRU_actual_area,SRU_percent_of_base,SRU_effective_area,SRU_replacement_cost_new,STP_description,STP_actual_area,STP_percent_of_base,STP_effective_area,STP_replacement_cost_new,TER_description,TER_actual_area,TER_percent_of_base,TER_effective_area,TER_replacement_cost_new,UAT_description,UAT_actual_area,UAT_percent_of_base,UAT_effective_area,UAT_replacement_cost_new,UBM_description,UBM_actual_area,UBM_percent_of_base,UBM_effective_area,UBM_replacement_cost_new,UCB_description,UCB_actual_area,UCB_percent_of_base,UCB_effective_area,UCB_replacement_cost_new,UCP_description,UCP_actual_area,UCP_percent_of_base,UCP_effective_area,UCP_replacement_cost_new,UDC_description,UDC_actual_area,UDC_percent_of_base,UDC_effective_area,UDC_replacement_cost_new,UDG_description,UDG_actual_area,UDG_percent_of_base,UDG_effective_area,UDG_replacement_cost_new,UDS_description,UDS_actual_area,UDS_percent_of_base,UDS_effective_area,UDS_replacement_cost_new,UDU_description,UDU_actual_area,UDU_percent_of_base,UDU_effective_area,UDU_replacement_cost_new,UEP_description,UEP_actual_area,UEP_percent_of_base,UEP_effective_area,UEP_replacement_cost_new,UGB_description,UGB_actual_area,UGB_percent_of_base,UGB_effective_area,UGB_replacement_cost_new,UGD_description,UGD_actual_area,UGD_percent_of_base,UGD_effective_area,UGD_replacement_cost_new,UGR_description,UGR_actual_area,UGR_percent_of_base,UGR_effective_area,UGR_replacement_cost_new,ULP_description,ULP_actual_area,ULP_percent_of_base,ULP_effective_area,ULP_replacement_cost_new,UOG_description,UOG_actual_area,UOG_percent_of_base,UOG_effective_area,UOG_replacement_cost_new,UOP_description,UOP_actual_area,UOP_percent_of_base,UOP_effective_area,UOP_replacement_cost_new,USP_description,USP_actual_area,USP_percent_of_base,USP_effective_area,USP_replacement_cost_new,UST_description,UST_actual_area,UST_percent_of_base,UST_effective_area,UST_replacement_cost_new,UUS_description,UUS_actual_area,UUS_percent_of_base,UUS_effective_area,UUS_replacement_cost_new,UUT_description,UUT_actual_area,UUT_percent_of_base,UUT_effective_area,UUT_replacement_cost_new,WDD_description,WDD_actual_area,WDD_percent_of_base,WDD_effective_area,WDD_replacement_cost_new,Air Conditioning Type_detail_description,Air Conditioning Type_point_value,Air Conditioning Type_percentage,Average Rooms Per Floor_detail_description,Average Rooms Per Floor_point_value,Average Rooms Per Floor_percentage,Bedrooms/Bathrooms/Half-Bathrooms_detail_description,Bedrooms/Bathrooms/Half-Bathrooms_point_value,Bedrooms/Bathrooms/Half-Bathrooms_percentage,Ceiling & Insulation_detail_description,Ceiling & Insulation_point_value,Ceiling & Insulation_percentage,Commercial Heat & Air_detail_description,Commercial Heat & Air_point_value,Commercial Heat & Air_percentage,Common Owned Percentage_detail_description,Common Owned Percentage_point_value,Common Owned Percentage_percentage,Common Wall Percentage_detail_description,Common Wall Percentage_point_value,Common Wall Percentage_percentage,Condo Land Type_detail_description,Condo Land Type_point_value,Condo Land Type_percentage,Exterior Walls_detail_description,Exterior Walls_point_value,Exterior Walls_percentage,Fireplace_detail_description,Fireplace_point_value,Fireplace_percentage,Floor Number_detail_description,Floor Number_point_value,Floor Number_percentage,Foundation_detail_description,Foundation_point_value,Foundation_percentage,Heating Fuel_detail_description,Heating Fuel_point_value,Heating Fuel_percentage,Heating Type_detail_description,Heating Type_point_value,Heating Type_percentage,Interior Floor Cover_detail_description,Interior Floor Cover_point_value,Interior Floor Cover_percentage,Interior Wall Construction_detail_description,Interior Wall Construction_point_value,Interior Wall Construction_percentage,Plumbing Fixtures_detail_description,Plumbing Fixtures_point_value,Plumbing Fixtures_percentage,Roofing Cover_detail_description,Roofing Cover_point_value,Roofing Cover_percentage,Roofing Structure_detail_description,Roofing Structure_point_value,Roofing Structure_percentage,Structural Frame_detail_description,Structural Frame_point_value,Structural Frame_percentage,Sub Floor System_detail_description,Sub Floor System_point_value,Sub Floor System_percentage,Unit Count_detail_description,Unit Count_point_value,Unit Count_percentage,Unit Location_detail_description,Unit Location_point_value,Unit Location_percentage,Bathrooms_base_area,Bathrooms_upper_level,Bathrooms_lower_level,Bedrooms_base_area,Bedrooms_upper_level,Bedrooms_lower_level,Half-Bathrooms_base_area,Half-Bathrooms_upper_level,Half-Bathrooms_lower_level,bldg_number,code,description,length,width,units,unit_price,condition_factor,l_b,actual_year_built,effective_year_built,annual_depreciation,depreciation_override,net_percent_good,appraised_value_y,page_save
32,46706778400000,1,1983,1983,2956.0,952.0,3908,247990.0,NaN,10610 HARRIS RD HUNTERSVILLE,01,1,59.0,160.02,420313.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.0,3,CB,MF3,2024,1.0,Size,CB,Size,2024.0,1.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1732.0,100.0,1732.0,277155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Basement, Finished",1224.0,45.0,551.0,88171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",624.0,45.0,281.0,44966.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",24.0,35.0,8.0,1280.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,144.0,5.0,7.0,1120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,160.0,20.0,32.0,5121.0,03-Central,4.0,100.0,NaN,NaN,NaN,3/3/0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21-Face Brick,35.0,100.0,3-1 Story Single,2500.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,04-Electric,1.0,100.0,10-Heat Pump,4.0,100.0,08-Sheet Vinyl,6.0,100.0,5-Drywall/Sheetrock,20.0,100.0,NaN,NaN,NaN,10-Wood Shingle/310 Shingle,5.0,100.0,03-Gable,7.0,100.0,NaN,NaN,NaN,4-Plywood,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,1.0,3.0,0.0,0.0,NaN,NaN,NaN,1.0,10,PAVING CON,NaN,NaN,2500.0,7.00,100.0,L,1990.0,1998.0,100.0,NaN,50.0,10063.0,46706778400000.html
33,46706778400000,1,1983,1983,2956.0,952.0,3908,247990.0,NaN,10610 HARRIS RD HUNTERSVILLE,01,1,59.0,160.02,420313.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.0,3,CB,MF3,2024,1.0,Size,CB,Size,2024.0,1.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1732.0,100.0,1732.0,277155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Basement, Finished",1224.0,45.0,551.0,88171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",624.0,45.0,281.0,44966.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",24.0,35.0,8.0,1280.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,144.0,5.0,7.0,1120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,160.0,20.0,32.0,5121.0,03-Central,4.0,100.0,NaN,NaN,NaN,3/3/0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21-Face Brick,35.0,100.0,3-1 Story Single,2500.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,04-Electric,1.0,100.0,10-Heat Pump,4.0,100.0,08-Sheet Vinyl,6.0,100.0,5-Drywall/Sheetrock,20.0,100.0,NaN,NaN,NaN,10-Wood Shingle/310 Shingle,5.0,100.0,03-Gable,7.0,100.0,NaN,NaN,NaN,4-Plywood,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,1.0,3.0,0.0,0.0,NaN,NaN,NaN,1.0,05,FENCE WOOD,NaN,NaN,300.0,13.50,100.0,L,1990.0,1994.0,100.0,NaN,30.0,1215.0,46706778400000.html
34,46706778400000,1,1983,1983,2956.0,952.0,3908,247990.0,NaN,10610 HARRIS RD HUNTERSVILLE,01,1,59.0,160.02,420313.0,01 - SINGLE FAMILY RESIDENTIAL,01 - SINGLE FAMILY HOME,3,CB,Average,2024,1.0,3,CB,MF3,2024,1.0,Size,CB,Size,2024.0,1.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,1732.0,100.0,1732.0,277155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Basement, Finished",1224.0,45.0,551.0,88171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",624.0,45.0,281.0,44966.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Porch, Open, Finished",24.0,35.0,8.0,1280.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,144.0,5.0,7.0,1120.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Wood Deck,160.0,20.0,32.0,5121.0,03-Central,4.0,100.0,NaN,NaN,NaN,3/3/0,15.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21-Face Brick,35.0,100.0,3-1 Story Single,2500.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,04-Electric,1.0,100.0,10-Heat Pump,4.0,100.0,08-Sheet Vinyl,6.0,100.0,5-Drywall/Sheetrock,20.0,100.0,NaN,NaN,NaN,10-Wood Shingle/310 Shingle,5.0,100.0,03-Gable,7.0,100.0,NaN,NaN,NaN,4-Plywood,8.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,1.0,3.0,0.0,0.0,NaN,NaN,NaN,1.0,09,PAVING ASP,15.0,19.0,285.0,2.65,100.0,L,2003.0,2003.0,100.0,NaN,50.0,435.0,46706778400000.html

In [36]:
merged_df[merged_df['parcel_number'].duplicated()]

,parcel_number,bldg_id,ayb,eyb,heated_area,non_heated_area,total_area,appraised_value_x,building_name,property_address,use,model,percent_good,base_rate,replacement_cost_new,use_code_description,model_description,quality_code,quality_countycode,quality_description,quality_valuationyear,quality_value,shape_design_code,shape_design_countycode,shape_design_description,shape_design_valuationyear,shape_design_value,size_code,size_countycode,size_description,size_valuationyear,size_value,non-std_wall_height_code,non-std_wall_height_countycode,non-std_wall_height_description,non-std_wall_height_valuationyear,non-std_wall_height_value,ALP_description,ALP_actual_area,ALP_percent_of_base,ALP_effective_area,ALP_replacement_cost_new,AOF_description,AOF_actual_area,AOF_percent_of_base,AOF_effective_area,AOF_replacement_cost_new,APB_description,APB_actual_area,APB_percent_of_base,APB_effective_area,APB_replacement_cost_new,APT_description,APT_actual_area,APT_percent_of_base,APT_effective_area,APT_replacement_cost_new,BAS_description,BAS_actual_area,BAS_percent_of_base,BAS_effective_area,BAS_replacement_cost_new,BOF_description,BOF_actual_area,BOF_percent_of_base,BOF_effective_area,BOF_replacement_cost_new,CAN_description,CAN_actual_area,CAN_percent_of_base,CAN_effective_area,CAN_replacement_cost_new,CAS_description,CAS_actual_area,CAS_percent_of_base,CAS_effective_area,CAS_replacement_cost_new,CBM_description,CBM_actual_area,CBM_percent_of_base,CBM_effective_area,CBM_replacement_cost_new,CDN_description,CDN_actual_area,CDN_percent_of_base,CDN_effective_area,CDN_replacement_cost_new,CLP_description,CLP_actual_area,CLP_percent_of_base,CLP_effective_area,CLP_replacement_cost_new,FAT_description,FAT_actual_area,FAT_percent_of_base,FAT_effective_area,FAT_replacement_cost_new,FBM_description,FBM_actual_area,FBM_percent_of_base,FBM_effective_area,FBM_replacement_cost_new,FCB_description,FCB_actual_area,FCB_percent_of_base,FCB_effective_area,FCB_replacement_cost_new,FCP_description,FCP_actual_area,FCP_percent_of_base,FCP_effective_area,FCP_replacement_cost_new,FDC_description,FDC_actual_area,FDC_percent_of_base,FDC_effective_area,FDC_replacement_cost_new,FDG_description,FDG_actual_area,FDG_percent_of_base,FDG_effective_area,FDG_replacement_cost_new,FDU_description,FDU_actual_area,FDU_percent_of_base,FDU_effective_area,FDU_replacement_cost_new,FEP_description,FEP_actual_area,FEP_percent_of_base,FEP_effective_area,FEP_replacement_cost_new,FGB_description,FGB_actual_area,FGB_percent_of_base,FGB_effective_area,FGB_replacement_cost_new,FGD_description,FGD_actual_area,FGD_percent_of_base,FGD_effective_area,FGD_replacement_cost_new,FGR_description,FGR_actual_area,FGR_percent_of_base,FGR_effective_area,FGR_replacement_cost_new,FHS_description,FHS_actual_area,FHS_percent_of_base,FHS_effective_area,FHS_replacement_cost_new,FOF_description,FOF_actual_area,FOF_percent_of_base,FOF_effective_area,FOF_replacement_cost_new,FOG_description,FOG_actual_area,FOG_percent_of_base,FOG_effective_area,FOG_replacement_cost_new,FOP_description,FOP_actual_area,FOP_percent_of_base,FOP_effective_area,FOP_replacement_cost_new,FSP_description,FSP_actual_area,FSP_percent_of_base,FSP_effective_area,FSP_replacement_cost_new,FST_description,FST_actual_area,FST_percent_of_base,FST_effective_area,FST_replacement_cost_new,FUS_description,FUS_actual_area,FUS_percent_of_base,FUS_effective_area,FUS_replacement_cost_new,FUT_description,FUT_actual_area,FUT_percent_of_base,FUT_effective_area,FUT_replacement_cost_new,GOF_description,GOF_actual_area,GOF_percent_of_base,GOF_effective_area,GOF_replacement_cost_new,LAB_description,LAB_actual_area,LAB_percent_of_base,LAB_effective_area,LAB_replacement_cost_new,LFG_description,LFG_actual_area,LFG_percent_of_base,LFG_effective_area,LFG_replacement_cost_new,LFT_description,LFT_actual_area,LFT_percent_of_base,LFT_effective_area,LFT_replacement_cost_new,LLF_description,LLF_actual_area,LLF_percent_of_base,LLF_effective_area,LLF_replacement_cost_new,LLS_description,LLS_actual_area,LLS_percent_of_base,LLS_effective_area,LLS_replacement_cost_new,LLU_description,LLU_actual_area,LLU_percent_of_base,LLU_effective_area,LLU_replacement_cost_new,LUG_description,LUG_actual_area,LUG_percent_of_base,LUG_effective_area,LUG_replacement_cost_new,MEZ_description,MEZ_actual_area,MEZ_percent_of_base,MEZ_effective_area,MEZ_replacement_cost_new,MFG_description,MFG_actual_area,MFG_percent_of_base,MFG_effective_area,MFG_replacement_cost_new,MFM_description,MFM_actual_area,MFM_percent_of_base,MFM_effective_area,MFM_replacement_cost_new,MOF_description,MOF_actual_area,MOF_percent_of_base,MOF_effective_area,MOF_replacement_cost_new,OEB_description,OEB_actual_area,OEB_percent_of_base,OEB_effective_area,OEB_replacement_cost_new,PTO_description,PTO_actual_area,PTO_percent_of_base,PTO_effective_area,PTO_replacement_cost_new,PTR_description,PTR_actual_area,PTR_percent_of_base,PTR_effective_area,PTR_replacement_cost_new,SBM_description,SBM_actual_area,SBM_percent_of_base,SBM_effective_area,SBM_replacement_cost_new,SDA_description,SDA_actual_area,SDA_percent_of_base,SDA_effective_area,SDA_replacement_cost_new,SFB_description,SFB_actual_area,SFB_percent_of_base,SFB_effective_area,SFB_replacement_cost_new,SPA_description,SPA_actual_area,SPA_percent_of_base,SPA_effective_area,SPA_replacement_cost_new,SRH_description,SRH_actual_area,SRH_percent_of_base,SRH_effective_area,SRH_replacement_cost_new,SRU_description,SRU_actual_area,SRU_percent_of_base,SRU_effective_area,SRU_replacement_cost_new,STP_description,STP_actual_area,STP_percent_of_base,STP_effective_area,STP_replacement_cost_new,TER_description,TER_actual_area,TER_percent_of_base,TER_effective_area,TER_replacement_cost_new,UAT_description,UAT_actual_area,UAT_percent_of_base,UAT_effective_area,UAT_replacement_cost_new,UBM_description,UBM_actual_area,UBM_percent_of_base,UBM_effective_area,UBM_replacement_cost_new,UCB_description,UCB_actual_area,UCB_percent_of_base,UCB_effective_area,UCB_replacement_cost_new,UCP_description,UCP_actual_area,UCP_percent_of_base,UCP_effective_area,UCP_replacement_cost_new,UDC_description,UDC_actual_area,UDC_percent_of_base,UDC_effective_area,UDC_replacement_cost_new,UDG_description,UDG_actual_area,UDG_percent_of_base,UDG_effective_area,UDG_replacement_cost_new,UDS_description,UDS_actual_area,UDS_percent_of_base,UDS_effective_area,UDS_replacement_cost_new,UDU_description,UDU_actual_area,UDU_percent_of_base,UDU_effective_area,UDU_replacement_cost_new,UEP_description,UEP_actual_area,UEP_percent_of_base,UEP_effective_area,UEP_replacement_cost_new,UGB_description,UGB_actual_area,UGB_percent_of_base,UGB_effective_area,UGB_replacement_cost_new,UGD_description,UGD_actual_area,UGD_percent_of_base,UGD_effective_area,UGD_replacement_cost_new,UGR_description,UGR_actual_area,UGR_percent_of_base,UGR_effective_area,UGR_replacement_cost_new,ULP_description,ULP_actual_area,ULP_percent_of_base,ULP_effective_area,ULP_replacement_cost_new,UOG_description,UOG_actual_area,UOG_percent_of_base,UOG_effective_area,UOG_replacement_cost_new,UOP_description,UOP_actual_area,UOP_percent_of_base,UOP_effective_area,UOP_replacement_cost_new,USP_description,USP_actual_area,USP_percent_of_base,USP_effective_area,USP_replacement_cost_new,UST_description,UST_actual_area,UST_percent_of_base,UST_effective_area,UST_replacement_cost_new,UUS_description,UUS_actual_area,UUS_percent_of_base,UUS_effective_area,UUS_replacement_cost_new,UUT_description,UUT_actual_area,UUT_percent_of_base,UUT_effective_area,UUT_replacement_cost_new,WDD_description,WDD_actual_area,WDD_percent_of_base,WDD_effective_area,WDD_replacement_cost_new,Air Conditioning Type_detail_description,Air Conditioning Type_point_value,Air Conditioning Type_percentage,Average Rooms Per Floor_detail_description,Average Rooms Per Floor_point_value,Average Rooms Per Floor_percentage,Bedrooms/Bathrooms/Half-Bathrooms_detail_description,Bedrooms/Bathrooms/Half-Bathrooms_point_value,Bedrooms/Bathrooms/Half-Bathrooms_percentage,Ceiling & Insulation_detail_description,Ceiling & Insulation_point_value,Ceiling & Insulation_percentage,Commercial Heat & Air_detail_description,Commercial Heat & Air_point_value,Commercial Heat & Air_percentage,Common Owned Percentage_detail_description,Common Owned Percentage_point_value,Common Owned Percentage_percentage,Common Wall Percentage_detail_description,Common Wall Percentage_point_value,Common Wall Percentage_percentage,Condo Land Type_detail_description,Condo Land Type_point_value,Condo Land Type_percentage,Exterior Walls_detail_description,Exterior Walls_point_value,Exterior Walls_percentage,Fireplace_detail_description,Fireplace_point_value,Fireplace_percentage,Floor Number_detail_description,Floor Number_point_value,Floor Number_percentage,Foundation_detail_description,Foundation_point_value,Foundation_percentage,Heating Fuel_detail_description,Heating Fuel_point_value,Heating Fuel_percentage,Heating Type_detail_description,Heating Type_point_value,Heating Type_percentage,Interior Floor Cover_detail_description,Interior Floor Cover_point_value,Interior Floor Cover_percentage,Interior Wall Construction_detail_description,Interior Wall Construction_point_value,Interior Wall Construction_percentage,Plumbing Fixtures_detail_description,Plumbing Fixtures_point_value,Plumbing Fixtures_percentage,Roofing Cover_detail_description,Roofing Cover_point_value,Roofing Cover_percentage,Roofing Structure_detail_description,Roofing Structure_point_value,Roofing Structure_percentage,Structural Frame_detail_description,Structural Frame_point_value,Structural Frame_percentage,Sub Floor System_detail_description,Sub Floor System_point_value,Sub Floor System_percentage,Unit Count_detail_description,Unit Count_point_value,Unit Count_percentage,Unit Location_detail_description,Unit Location_point_value,Unit Location_percentage,Bathrooms_base_area,Bathrooms_upper_level,Bathrooms_lower_level,Bedrooms_base_area,Bedrooms_upper_level,Bedrooms_lower_level,Half-Bathrooms_base_area,Half-Bathrooms_upper_level,Half-Bathrooms_lower_level,bldg_number,code,description,length,width,units,unit_price,condition_factor,l_b,actual_year_built,effective_year_built,annual_depreciation,depreciation_override,net_percent_good,appraised_value_y,page_save
7,46707318010000,1,2022,2022,1859.0,532.0,2391,308080.0,NaN,10463 DALTON WOODS CT NW HUNTERSVILLE,09,1,98.0,167.04,314369.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,4,CB,Above Average,2024,1.10,5,CB,MF5,2024,1.10,Size,CB,Size,2024.0,1.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,780.0,100.0,780.0,130291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",380.0,45.0,171.0,28564.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1079.0,85.0,917.0,153176.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,120.0,5.0,6.0,1002.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stoop,32.0,25.0,8.0,1336.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-Central,4.0,100.0,NaN,NaN,NaN,3/2/1,13.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10-Aluminum/Vinyl Siding,30.0,100.0,1-None,0.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,04-Electric,1.0,100.0,10-Heat Pump,4.0,100.0,09-Pine or Soft Woods,10.0,100.0,5-Drywall/Sheetrock,26.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,03-Gable,7.0,100.0,NaN,NaN,NaN,2-Slab on Grade-Residential/Commercial,5.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,3.0,0.0,1.0,0.0,0.0,1.0,NaN,FEN PVC PR,NaN,NaN,8.0,31.0,100.0,NaN,2022.0,2022.0,10.0,NaN,90.0,223.0,46707318010000.html
9,46707348030000,1,2021,2021,1844.0,532.0,2376,304430.0,NaN,10448 DALTON WOODS CT NW HUNTERSVILLE,09,1,97.0,167.04,313847.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,4,CB,Above Average,2024,1.10,5,CB,MF5,2024,1.10,Size,CB,Size,2024.0,1.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,780.0,100.0,780.0,130291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",380.0,45.0,171.0,28564.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1064.0,85.0,904.0,151004.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,120.0,5.0,6.0,1002.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stoop,32.0,25.0,8.0,1336.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-Central,4.0,100.0,NaN,NaN,NaN,3/2/1,13.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10-Aluminum/Vinyl Siding,30.0,100.0,2-Pre Fabricated,1650.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,04-Electric,1.0,100.0,10-Heat Pump,4.0,100.0,09-Pine or Soft Woods,10.0,100.0,5-Drywall/Sheetrock,26.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,03-Gable,7.0,100.0,NaN,NaN,NaN,2-Slab on Grade-Residential/Commercial,5.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,3.0,0.0,1.0,0.0,0.0,1.0,NaN,FEN PVC PR,NaN,NaN,8.0,31.0,100.0,NaN,2022.0,2022.0,10.0,NaN,90.0,223.0,46707348030000.html
18,46707357690000,1,2021,2021,1844.0,532.0,2376,304430.0,NaN,10436 DALTON WOODS CT NW HUNTERSVILLE,09,1,97.0,167.04,313847.0,09 - SINGLE FAMILY TOWNHOUSE,01 - SINGLE FAMILY HOME,4,CB,Above Average,2024,1.10,5,CB,MF5,2024,1.10,Size,CB,Size,2024.0,1.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Base Living Area,780.0,100.0,780.0,130291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Garage, Finished, with Door",380.0,45.0,171.0,28564.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Upper Story, Finished",1064.0,85.0,904.0,151004.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patio,120.0,5.0,6.0,1002.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Stoop,32.0,25.0,8.0,1336.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03-Central,4.0,100.0,NaN,NaN,NaN,3/2/1,13.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10-Aluminum/Vinyl Siding,30.0,100.0,2-Pre Fabricated,1650.0,100.0,NaN,NaN,NaN,3-Continuous Footing,5.0,100.0,04-Electric,1.0,100.0,10-Heat Pump,4.0,100.0,09-Pine or Soft Woods,10.0,100.0,5-Drywall/Sheetrock,26.0,100.0,NaN,NaN,NaN,03-Asphalt or Composition Shingle,3.0,100.0,03-Gable,7.0,100.0,NaN,NaN,NaN,2-Slab on Grade-Residential/Commercial,5.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,3.0,0.0,1.0,0.0,0.0,1.0,NaN,FEN PVC PR,NaN,NaN,44.0,31.0,100.0,NaN,2021.0,2021.0,15.0,NaN,85.0,1159.0,46707357690000.html