In [1]:
import pandas as pd
import numpy as np

# Case 1: Reading csv

In [2]:
df = pd.read_csv(r"D:\North Carolina\Cabarrus\Property\Raw_Data\us_nc_37025_data_prop_exemption-codes_bronze_20251127.csv")
df

,parcel_number,code,description,value_subject_to_exemption,page_save
0,46705844430000,EV,Disabled Veteran Exclusion,716260.0,46705844430000.html
1,46706632490000,EV,Disabled Veteran Exclusion,388380.0,46706632490000.html
2,46706621490000,EV,Disabled Veteran Exclusion,418050.0,46706621490000.html
3,46717325080000,EBX,Builders Inventory Exclusion,0.0,46717325080000.html
4,46716393820000,EBX,Builders Inventory Exclusion,0.0,46716393820000.html
...,...,...,...,...,...
5677,46928383360000,EA,Homestead Exclusion,376280.0,46928383360000.html
5678,56143099440000,EA,Homestead Exclusion,175850.0,56143099440000.html
5679,45999657550000,EA,Homestead Exclusion,128360.0,45999657550000.html
5680,46946255640000,EA,Homestead Exclusion,306190.0,46946255640000.html
5681,56244171550000,EA,Homestead Exclusion,150710.0,56244171550000.html

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5682 entries, 0 to 5681
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   parcel_number               5682 non-null   int64
 1   code                        5682 non-null   object
 2   description                 5682 non-null   object
 3   value_subject_to_exemption  5682 non-null   float64
 4   page_save                   5682 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 222.1+ KB

# Case 2: Handling multi spaces

In [4]:
import re
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].apply(lambda x: re.sub(r'\s+', ' ', x).strip() if isinstance(x, str) else x)

# Case 3: Checking fake nulls

In [5]:
# Define fake null values
fake_nulls = ['', 'null', 'none', 'nan', "None", 'na', 'n/a', 'n.a.', 'NaN', 'NAN', 'NULL', 'nil', 'Nan', 'Null','NONE']
 
# ✅ Now check and replace in all columns
for col in df.columns:
    mask = df[col].astype(str).str.lower().isin([str(x).lower() for x in fake_nulls])
    problem_rows = df.loc[mask, [col]]
   
    if not problem_rows.empty:
        print(f"Rows where '{col}' has fake nulls:")
        print(problem_rows)
        # Replace fake nulls with NaN
        df[col] = df[col].replace(fake_nulls, np.nan)
 
# Optional: Summary of NaNs per column
print("\nNaN count per column:")
print(df.isna().sum())
 
# Show final cleaned DataFrame
print("\nCleaned DataFrame:")
print(df)

NaN count per column:
parcel_number                 0
code                          0
description                   0
value_subject_to_exemption    0
page_save                     0
dtype: int64

Cleaned DataFrame:
       parcel_number code                   description  \
0     46705844430000   EV    Disabled Veteran Exclusion
1     46706632490000   EV    Disabled Veteran Exclusion
2     46706621490000   EV    Disabled Veteran Exclusion
3     46717325080000  EBX  Builders Inventory Exclusion
4     46716393820000  EBX  Builders Inventory Exclusion
...              ...  ...                           ...
5677  46928383360000   EA           Homestead Exclusion
5678  56143099440000   EA           Homestead Exclusion
5679  45999657550000   EA           Homestead Exclusion
5680  46946255640000   EA           Homestead Exclusion
5681  56244171550000   EA           Homestead Exclusion

      value_subject_to_exemption            page_save
0                       716260.0  46705844430000.html
1                       388380.0  46706632490000.html
2                       418050.0  46706621490000.html
3                            0.0  46717325080000.html
4                            0.0  46716393820000.html
...                          ...                  ...
5677                    376280.0  46928383360000.html
5678                    175850.0  56143099440000.html
5679                    128360.0  45999657550000.html
5680                    306190.0  46946255640000.html
5681                    150710.0  56244171550000.html

[5682 rows x 5 columns]

In [6]:
df

,parcel_number,code,description,value_subject_to_exemption,page_save
0,46705844430000,EV,Disabled Veteran Exclusion,716260.0,46705844430000.html
1,46706632490000,EV,Disabled Veteran Exclusion,388380.0,46706632490000.html
2,46706621490000,EV,Disabled Veteran Exclusion,418050.0,46706621490000.html
3,46717325080000,EBX,Builders Inventory Exclusion,0.0,46717325080000.html
4,46716393820000,EBX,Builders Inventory Exclusion,0.0,46716393820000.html
...,...,...,...,...,...
5677,46928383360000,EA,Homestead Exclusion,376280.0,46928383360000.html
5678,56143099440000,EA,Homestead Exclusion,175850.0,56143099440000.html
5679,45999657550000,EA,Homestead Exclusion,128360.0,45999657550000.html
5680,46946255640000,EA,Homestead Exclusion,306190.0,46946255640000.html
5681,56244171550000,EA,Homestead Exclusion,150710.0,56244171550000.html

In [7]:
df['code'].value_counts()

code
EA      2569
EBX     1956
EV      1026
XXXX      48
EM        31
EOT       20
EX        18
1          8
7          3
L          2
ECB        1
Name: count, dtype: int64

In [8]:
df['description'].value_counts()

description
Homestead Exclusion                      2569
Builders Inventory Exclusion             1956
Disabled Veteran Exclusion               1026
XXXX                                       48
Homestead Exclusion Mobile Home            31
OTHER EXCLUSION                            20
Homestead Exclusion Partial Ownership      18
RELIGIOUS EXEMPTION                         8
CHARITABLE                                  3
Educational, Non-Governmental               2
Homestead Circuit Breaker                   1
Name: count, dtype: int64

# Case 4: REplaced 'XXXX' with blank space

In [9]:
df['description'] = df['description'].replace('XXXX', np.nan)

In [10]:
df['description'].value_counts()

description
Homestead Exclusion                      2569
Builders Inventory Exclusion             1956
Disabled Veteran Exclusion               1026
Homestead Exclusion Mobile Home            31
OTHER EXCLUSION                            20
Homestead Exclusion Partial Ownership      18
RELIGIOUS EXEMPTION                         8
CHARITABLE                                  3
Educational, Non-Governmental               2
Homestead Circuit Breaker                   1
Name: count, dtype: int64

In [11]:
df

,parcel_number,code,description,value_subject_to_exemption,page_save
0,46705844430000,EV,Disabled Veteran Exclusion,716260.0,46705844430000.html
1,46706632490000,EV,Disabled Veteran Exclusion,388380.0,46706632490000.html
2,46706621490000,EV,Disabled Veteran Exclusion,418050.0,46706621490000.html
3,46717325080000,EBX,Builders Inventory Exclusion,0.0,46717325080000.html
4,46716393820000,EBX,Builders Inventory Exclusion,0.0,46716393820000.html
...,...,...,...,...,...
5677,46928383360000,EA,Homestead Exclusion,376280.0,46928383360000.html
5678,56143099440000,EA,Homestead Exclusion,175850.0,56143099440000.html
5679,45999657550000,EA,Homestead Exclusion,128360.0,45999657550000.html
5680,46946255640000,EA,Homestead Exclusion,306190.0,46946255640000.html
5681,56244171550000,EA,Homestead Exclusion,150710.0,56244171550000.html

# Case 5: REplaced 0 with blank space

In [12]:
df['value_subject_to_exemption'].value_counts()

value_subject_to_exemption
0.0         1269
140000.0     236
72000.0      105
90000.0       46
120000.0      46
            ...
347070.0       1
901470.0       1
802220.0       1
338260.0       1
159050.0       1
Name: count, Length: 3591, dtype: int64

In [13]:
df['value_subject_to_exemption'] = df['value_subject_to_exemption'].replace(0, np.nan)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5682 entries, 0 to 5681
Data columns (total 5 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   parcel_number               5682 non-null   int64
 1   code                        5682 non-null   object
 2   description                 5634 non-null   object
 3   value_subject_to_exemption  4413 non-null   float64
 4   page_save                   5682 non-null   object
dtypes: float64(1), int64(1), object(3)
memory usage: 222.1+ KB

In [15]:
df

,parcel_number,code,description,value_subject_to_exemption,page_save
0,46705844430000,EV,Disabled Veteran Exclusion,716260.0,46705844430000.html
1,46706632490000,EV,Disabled Veteran Exclusion,388380.0,46706632490000.html
2,46706621490000,EV,Disabled Veteran Exclusion,418050.0,46706621490000.html
3,46717325080000,EBX,Builders Inventory Exclusion,NaN,46717325080000.html
4,46716393820000,EBX,Builders Inventory Exclusion,NaN,46716393820000.html
...,...,...,...,...,...
5677,46928383360000,EA,Homestead Exclusion,376280.0,46928383360000.html
5678,56143099440000,EA,Homestead Exclusion,175850.0,56143099440000.html
5679,45999657550000,EA,Homestead Exclusion,128360.0,45999657550000.html
5680,46946255640000,EA,Homestead Exclusion,306190.0,46946255640000.html
5681,56244171550000,EA,Homestead Exclusion,150710.0,56244171550000.html

## Found on-site same values like '1','L' and '7' so keeping it as it is.

In [16]:
df[df['code'].str.len() == 1]

,parcel_number,code,description,value_subject_to_exemption,page_save
458,55085857200000,1,RELIGIOUS EXEMPTION,1938280.0,55085857200000.html
1215,56208616560000,L,"Educational, Non-Governmental",165720.0,56208616560000.html
1520,56219563740000,1,RELIGIOUS EXEMPTION,4065540.0,56219563740000.html
1730,56234617550000,1,RELIGIOUS EXEMPTION,5819070.0,56234617550000.html
2729,56207675640000,L,"Educational, Non-Governmental",3163910.0,56207675640000.html
3138,55340967580000,1,RELIGIOUS EXEMPTION,1694400.0,55340967580000.html
3601,56032403870000,7,CHARITABLE,4852030.0,56032403870000.html
4058,56224094780000,7,CHARITABLE,966600.0,56224094780000.html
4374,56214985420000,7,CHARITABLE,1549270.0,56214985420000.html
4438,56201546010000,1,RELIGIOUS EXEMPTION,204930.0,56201546010000.html
5183,56102982520000,1,RELIGIOUS EXEMPTION,2689670.0,56102982520000.html
5299,56235262240000,1,RELIGIOUS EXEMPTION,1022840.0,56235262240000.html
5472,56701779360000,1,RELIGIOUS EXEMPTION,3063970.0,56701779360000.html

In [17]:
df

,parcel_number,code,description,value_subject_to_exemption,page_save
0,46705844430000,EV,Disabled Veteran Exclusion,716260.0,46705844430000.html
1,46706632490000,EV,Disabled Veteran Exclusion,388380.0,46706632490000.html
2,46706621490000,EV,Disabled Veteran Exclusion,418050.0,46706621490000.html
3,46717325080000,EBX,Builders Inventory Exclusion,NaN,46717325080000.html
4,46716393820000,EBX,Builders Inventory Exclusion,NaN,46716393820000.html
...,...,...,...,...,...
5677,46928383360000,EA,Homestead Exclusion,376280.0,46928383360000.html
5678,56143099440000,EA,Homestead Exclusion,175850.0,56143099440000.html
5679,45999657550000,EA,Homestead Exclusion,128360.0,45999657550000.html
5680,46946255640000,EA,Homestead Exclusion,306190.0,46946255640000.html
5681,56244171550000,EA,Homestead Exclusion,150710.0,56244171550000.html

# Case 6: Placing the file

In [18]:
df.to_csv(r"D:\North Carolina\Cabarrus\Property\Cleaned_Data\us_nc_37025_data_prop_exemption-codes_silver_20251127.csv", index=False)
df

,parcel_number,code,description,value_subject_to_exemption,page_save
0,46705844430000,EV,Disabled Veteran Exclusion,716260.0,46705844430000.html
1,46706632490000,EV,Disabled Veteran Exclusion,388380.0,46706632490000.html
2,46706621490000,EV,Disabled Veteran Exclusion,418050.0,46706621490000.html
3,46717325080000,EBX,Builders Inventory Exclusion,NaN,46717325080000.html
4,46716393820000,EBX,Builders Inventory Exclusion,NaN,46716393820000.html
...,...,...,...,...,...
5677,46928383360000,EA,Homestead Exclusion,376280.0,46928383360000.html
5678,56143099440000,EA,Homestead Exclusion,175850.0,56143099440000.html
5679,45999657550000,EA,Homestead Exclusion,128360.0,45999657550000.html
5680,46946255640000,EA,Homestead Exclusion,306190.0,46946255640000.html
5681,56244171550000,EA,Homestead Exclusion,150710.0,56244171550000.html