In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\North Carolina\Cabarrus\Property\Raw_Data\us_nc_37025_data_prop_land_bronze_20251127.csv")
df

C:\Users\keisha.sonasaniya\AppData\Local\Temp\ipykernel_17988\148153470.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"D:\North Carolina\Cabarrus\Property\Raw_Data\us_nc_37025_data_prop_land_bronze_20251127.csv")

,parcel_number,land_use,use_code,zoning,frontage,depth,depth_factor,land_model,condition_factor,adjustments,...,unit_type,total_adjustment,adjusted_unit_price,land_value,notes,ex1,total_market_frontage,total_market_units,total_market_land_value,page_save
0,46707245420000,TWH GOLF,0383,LDR,28.0,88.0,1.00,0,1.00,.06 AC,...,LT,1.000,"80,000.00","80,000.00",VIEW,NaN,28.0,1.00,"80,000.00",46707245420000.html
1,46707324050000,SFR,0100,R-CO,171.0,137.0,1.00,0,1.00,NaN,...,LT,1.000,"90,000.00","90,000.00",.26 AC,NaN,171.0,1.00,"90,000.00",46707324050000.html
2,46707338740000,TOWNHOUSE,0309,rv-cd,35.0,NaN,1.00,0,1.00,.079 AC,...,LT,1.000,"76,000.00","76,000.00",NaN,NaN,35.0,1.00,"76,000.00",46707338740000.html
3,46707357690000,TOWNHOUSE,0309,rv-cd,28.0,91.0,1.00,0,1.00,.058 AC,...,LT,1.000,"76,000.00","76,000.00",NaN,NaN,28.0,1.00,"76,000.00",46707357690000.html
4,46707350990000,SFR,0100,R-CO,0.0,0.0,1.00,0,1.00,.14 AC,...,LT,1.000,"90,000.00","90,000.00",NaN,NaN,0.0,1.00,"90,000.00",46707350990000.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99169,66023336930000,RURAL AC,120,AO,16.0,NaN,2.18,4,0.96,NaN,...,AC,2.089,"24,023.50","28,588.00",NaN,NaN,16.0,1.19,"28,588.00",66023336930000.html
99170,56902529920000,RURAL AC,120,AO,564.0,NaN,1.12,4,1.02,NaN,...,AC,1.144,"19,448.00","210,233.00",NaN,NaN,564.0,10.81,"210,233.00",56902529920000.html
99171,66020121510000,WAREHOUSNG,648,AO,679.0,0.0,1.02,4,1.01,NaN,...,AC,1.032,"11,868.00","233,206.00",NaN,NaN,679.0,19.65,"233,206.00",66020121510000.html
99172,66022571130000,RURAL AC,120,AO,NaN,NaN,1.22,4,0.85,NaN,...,AC,1.040,"11,960.00","75,109.00",NaN,NaN,NaN,6.28,"75,109.00",66022571130000.html
99173,66022012680000,RURAL AC,120,AO,0.0,0.0,1.07,4,0.70,NaN,...,AC,0.751,"8,636.50","120,047.00",NaN,NaN,0.0,13.90,"120,047.00",66022012680000.html

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99174 entries, 0 to 99173
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   parcel_number            99174 non-null  int64
 1   land_use                 99174 non-null  object
 2   use_code                 99174 non-null  object
 3   zoning                   99169 non-null  object
 4   frontage                 96854 non-null  float64
 5   depth                    84176 non-null  float64
 6   depth_factor             99174 non-null  float64
 7   land_model               99174 non-null  int64
 8   condition_factor         99174 non-null  float64
 9   adjustments              35561 non-null  object
 10  road_type                95015 non-null  object
 11  unit_price               99174 non-null  object
 12  units                    99174 non-null  float64
 13  unit_type                99174 non-null  object
 14  total_adjustment         99174 non-null  float64
 15  adjusted_unit_price      97866 non-null  object
 16  land_value               97952 non-null  object
 17  notes                    13490 non-null  object
 18  ex1                      0 non-null      float64
 19  total_market_frontage    94894 non-null  float64
 20  total_market_units       99174 non-null  float64
 21  total_market_land_value  97846 non-null  object
 22  page_save                99174 non-null  object
dtypes: float64(9), int64(2), object(12)
memory usage: 17.4+ MB

# Case 2: Handling multi spaces

In [4]:
import re
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].apply(lambda x: re.sub(r'\s+', ' ', x).strip() if isinstance(x, str) else x)

# Case 3: Checking fake nulls

In [5]:
# Define fake null values
fake_nulls = ['', 'null', 'none', 'nan', "None", 'na', 'n/a', 'n.a.', 'NaN', 'NAN', 'NULL', 'nil', 'Nan', 'Null','NONE']
 
# ✅ Now check and replace in all columns
for col in df.columns:
    mask = df[col].astype(str).str.lower().isin([str(x).lower() for x in fake_nulls])
    problem_rows = df.loc[mask, [col]]
   
    if not problem_rows.empty:
        print(f"Rows where '{col}' has fake nulls:")
        print(problem_rows)
        # Replace fake nulls with NaN
        df[col] = df[col].replace(fake_nulls, np.nan)
 
# Optional: Summary of NaNs per column
print("\nNaN count per column:")
print(df.isna().sum())
 
# Show final cleaned DataFrame
print("\nCleaned DataFrame:")
print(df)

Rows where 'zoning' has fake nulls:
      zoning
8834     NaN
24760    NaN
31730    NaN
46077    NaN
54342    NaN
Rows where 'frontage' has fake nulls:
       frontage
53          NaN
104         NaN
130         NaN
138         NaN
341         NaN
...         ...
99019       NaN
99039       NaN
99097       NaN
99132       NaN
99172       NaN

[2320 rows x 1 columns]
Rows where 'depth' has fake nulls:
       depth
2        NaN
36       NaN
44       NaN
53       NaN
72       NaN
...      ...
99164    NaN
99167    NaN
99169    NaN
99170    NaN
99172    NaN

[14998 rows x 1 columns]
Rows where 'adjustments' has fake nulls:
      adjustments
1             NaN
12            NaN
13            NaN
16            NaN
18            NaN
...           ...
99169         NaN
99170         NaN
99171         NaN
99172         NaN
99173         NaN

[63613 rows x 1 columns]
Rows where 'road_type' has fake nulls:
      road_type
284         NaN
565         NaN
594         NaN
649         NaN
668         NaN
...         ...
97224       NaN
97688       NaN
97950       NaN
98389       NaN
98566       NaN

[4159 rows x 1 columns]
Rows where 'adjusted_unit_price' has fake nulls:
      adjusted_unit_price
18                    NaN
36                    NaN
40                    NaN
44                    NaN
50                    NaN
...                   ...
97438                 NaN
97580                 NaN
98266                 NaN
98812                 NaN
98995                 NaN

[1308 rows x 1 columns]
Rows where 'land_value' has fake nulls:
      land_value
18           NaN
36           NaN
40           NaN
44           NaN
50           NaN
...          ...
97438        NaN
97580        NaN
98266        NaN
98812        NaN
98995        NaN

[1222 rows x 1 columns]
Rows where 'notes' has fake nulls:
      notes
2       NaN
3       NaN
4       NaN
5       NaN
6       NaN
...     ...
99169   NaN
99170   NaN
99171   NaN
99172   NaN
99173   NaN

[85684 rows x 1 columns]
Rows where 'ex1' has fake nulls:
       ex1
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
...    ...
99169  NaN
99170  NaN
99171  NaN
99172  NaN
99173  NaN

[99174 rows x 1 columns]
Rows where 'total_market_frontage' has fake nulls:
       total_market_frontage
53                       NaN
104                      NaN
130                      NaN
138                      NaN
156                      NaN
...                      ...
99078                    NaN
99097                    NaN
99132                    NaN
99152                    NaN
99172                    NaN

[4280 rows x 1 columns]
Rows where 'total_market_land_value' has fake nulls:
      total_market_land_value
18                        NaN
36                        NaN
40                        NaN
44                        NaN
50                        NaN
...                       ...
98527                     NaN
98562                     NaN
98812                     NaN
98914                     NaN
98995                     NaN

[1328 rows x 1 columns]

NaN count per column:
parcel_number                  0
land_use                       0
use_code                       0
zoning                         5
frontage                    2320
depth                      14998
depth_factor                   0
land_model                     0
condition_factor               0
adjustments                63613
road_type                   4159
unit_price                     0
units                          0
unit_type                      0
total_adjustment               0
adjusted_unit_price         1308
land_value                  1222
notes                      85684
ex1                        99174
total_market_frontage       4280
total_market_units             0
total_market_land_value     1328
page_save                      0
dtype: int64

Cleaned DataFrame:
        parcel_number    land_use use_code zoning  frontage  depth  \
0      46707245420000    TWH GOLF     0383    LDR      28.0   88.0
1      46707324050000         SFR     0100   R-CO     171.0  137.0
2      46707338740000   TOWNHOUSE     0309  rv-cd      35.0    NaN
3      46707357690000   TOWNHOUSE     0309  rv-cd      28.0   91.0
4      46707350990000         SFR     0100   R-CO       0.0    0.0
...               ...         ...      ...    ...       ...    ...
99169  66023336930000    RURAL AC      120     AO      16.0    NaN
99170  56902529920000    RURAL AC      120     AO     564.0    NaN
99171  66020121510000  WAREHOUSNG      648     AO     679.0    0.0
99172  66022571130000    RURAL AC      120     AO       NaN    NaN
99173  66022012680000    RURAL AC      120     AO       0.0    0.0

       depth_factor  land_model  condition_factor adjustments  ... unit_type  \
0              1.00           0              1.00      .06 AC  ...        LT
1              1.00           0              1.00         NaN  ...        LT
2              1.00           0              1.00     .079 AC  ...        LT
3              1.00           0              1.00     .058 AC  ...        LT
4              1.00           0              1.00      .14 AC  ...        LT
...             ...         ...               ...         ...  ...       ...
99169          2.18           4              0.96         NaN  ...        AC
99170          1.12           4              1.02         NaN  ...        AC
99171          1.02           4              1.01         NaN  ...        AC
99172          1.22           4              0.85         NaN  ...        AC
99173          1.07           4              0.70         NaN  ...        AC

      total_adjustment  adjusted_unit_price  land_value   notes ex1  \
0                1.000            80,000.00   80,000.00    VIEW NaN
1                1.000            90,000.00   90,000.00  .26 AC NaN
2                1.000            76,000.00   76,000.00     NaN NaN
3                1.000            76,000.00   76,000.00     NaN NaN
4                1.000            90,000.00   90,000.00     NaN NaN
...                ...                  ...         ...     ...  ..
99169            2.089            24,023.50   28,588.00     NaN NaN
99170            1.144            19,448.00  210,233.00     NaN NaN
99171            1.032            11,868.00  233,206.00     NaN NaN
99172            1.040            11,960.00   75,109.00     NaN NaN
99173            0.751             8,636.50  120,047.00     NaN NaN

      total_market_frontage total_market_units  total_market_land_value  \
0                      28.0               1.00                80,000.00
1                     171.0               1.00                90,000.00
2                      35.0               1.00                76,000.00
3                      28.0               1.00                76,000.00
4                       0.0               1.00                90,000.00
...                     ...                ...                      ...
99169                  16.0               1.19                28,588.00
99170                 564.0              10.81               210,233.00
99171                 679.0              19.65               233,206.00
99172                   NaN               6.28                75,109.00
99173                   0.0              13.90               120,047.00

                 page_save
0      46707245420000.html
1      46707324050000.html
2      46707338740000.html
3      46707357690000.html
4      46707350990000.html
...                    ...
99169  66023336930000.html
99170  56902529920000.html
99171  66020121510000.html
99172  66022571130000.html
99173  66022012680000.html

[99174 rows x 23 columns]

In [6]:
df

,parcel_number,land_use,use_code,zoning,frontage,depth,depth_factor,land_model,condition_factor,adjustments,...,unit_type,total_adjustment,adjusted_unit_price,land_value,notes,ex1,total_market_frontage,total_market_units,total_market_land_value,page_save
0,46707245420000,TWH GOLF,0383,LDR,28.0,88.0,1.00,0,1.00,.06 AC,...,LT,1.000,"80,000.00","80,000.00",VIEW,NaN,28.0,1.00,"80,000.00",46707245420000.html
1,46707324050000,SFR,0100,R-CO,171.0,137.0,1.00,0,1.00,NaN,...,LT,1.000,"90,000.00","90,000.00",.26 AC,NaN,171.0,1.00,"90,000.00",46707324050000.html
2,46707338740000,TOWNHOUSE,0309,rv-cd,35.0,NaN,1.00,0,1.00,.079 AC,...,LT,1.000,"76,000.00","76,000.00",NaN,NaN,35.0,1.00,"76,000.00",46707338740000.html
3,46707357690000,TOWNHOUSE,0309,rv-cd,28.0,91.0,1.00,0,1.00,.058 AC,...,LT,1.000,"76,000.00","76,000.00",NaN,NaN,28.0,1.00,"76,000.00",46707357690000.html
4,46707350990000,SFR,0100,R-CO,0.0,0.0,1.00,0,1.00,.14 AC,...,LT,1.000,"90,000.00","90,000.00",NaN,NaN,0.0,1.00,"90,000.00",46707350990000.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99169,66023336930000,RURAL AC,120,AO,16.0,NaN,2.18,4,0.96,NaN,...,AC,2.089,"24,023.50","28,588.00",NaN,NaN,16.0,1.19,"28,588.00",66023336930000.html
99170,56902529920000,RURAL AC,120,AO,564.0,NaN,1.12,4,1.02,NaN,...,AC,1.144,"19,448.00","210,233.00",NaN,NaN,564.0,10.81,"210,233.00",56902529920000.html
99171,66020121510000,WAREHOUSNG,648,AO,679.0,0.0,1.02,4,1.01,NaN,...,AC,1.032,"11,868.00","233,206.00",NaN,NaN,679.0,19.65,"233,206.00",66020121510000.html
99172,66022571130000,RURAL AC,120,AO,NaN,NaN,1.22,4,0.85,NaN,...,AC,1.040,"11,960.00","75,109.00",NaN,NaN,NaN,6.28,"75,109.00",66022571130000.html
99173,66022012680000,RURAL AC,120,AO,0.0,0.0,1.07,4,0.70,NaN,...,AC,0.751,"8,636.50","120,047.00",NaN,NaN,0.0,13.90,"120,047.00",66022012680000.html

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99174 entries, 0 to 99173
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   parcel_number            99174 non-null  int64
 1   land_use                 99174 non-null  object
 2   use_code                 99174 non-null  object
 3   zoning                   99169 non-null  object
 4   frontage                 96854 non-null  float64
 5   depth                    84176 non-null  float64
 6   depth_factor             99174 non-null  float64
 7   land_model               99174 non-null  int64
 8   condition_factor         99174 non-null  float64
 9   adjustments              35561 non-null  object
 10  road_type                95015 non-null  object
 11  unit_price               99174 non-null  object
 12  units                    99174 non-null  float64
 13  unit_type                99174 non-null  object
 14  total_adjustment         99174 non-null  float64
 15  adjusted_unit_price      97866 non-null  object
 16  land_value               97952 non-null  object
 17  notes                    13490 non-null  object
 18  ex1                      0 non-null      float64
 19  total_market_frontage    94894 non-null  float64
 20  total_market_units       99174 non-null  float64
 21  total_market_land_value  97846 non-null  object
 22  page_save                99174 non-null  object
dtypes: float64(9), int64(2), object(12)
memory usage: 17.4+ MB

# Case 4: Dropped empty column

In [8]:
df.drop(columns={'ex1'}, inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99174 entries, 0 to 99173
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   parcel_number            99174 non-null  int64
 1   land_use                 99174 non-null  object
 2   use_code                 99174 non-null  object
 3   zoning                   99169 non-null  object
 4   frontage                 96854 non-null  float64
 5   depth                    84176 non-null  float64
 6   depth_factor             99174 non-null  float64
 7   land_model               99174 non-null  int64
 8   condition_factor         99174 non-null  float64
 9   adjustments              35561 non-null  object
 10  road_type                95015 non-null  object
 11  unit_price               99174 non-null  object
 12  units                    99174 non-null  float64
 13  unit_type                99174 non-null  object
 14  total_adjustment         99174 non-null  float64
 15  adjusted_unit_price      97866 non-null  object
 16  land_value               97952 non-null  object
 17  notes                    13490 non-null  object
 18  total_market_frontage    94894 non-null  float64
 19  total_market_units       99174 non-null  float64
 20  total_market_land_value  97846 non-null  object
 21  page_save                99174 non-null  object
dtypes: float64(8), int64(2), object(12)
memory usage: 16.6+ MB

In [10]:
df

,parcel_number,land_use,use_code,zoning,frontage,depth,depth_factor,land_model,condition_factor,adjustments,...,units,unit_type,total_adjustment,adjusted_unit_price,land_value,notes,total_market_frontage,total_market_units,total_market_land_value,page_save
0,46707245420000,TWH GOLF,0383,LDR,28.0,88.0,1.00,0,1.00,.06 AC,...,1.00,LT,1.000,"80,000.00","80,000.00",VIEW,28.0,1.00,"80,000.00",46707245420000.html
1,46707324050000,SFR,0100,R-CO,171.0,137.0,1.00,0,1.00,NaN,...,1.00,LT,1.000,"90,000.00","90,000.00",.26 AC,171.0,1.00,"90,000.00",46707324050000.html
2,46707338740000,TOWNHOUSE,0309,rv-cd,35.0,NaN,1.00,0,1.00,.079 AC,...,1.00,LT,1.000,"76,000.00","76,000.00",NaN,35.0,1.00,"76,000.00",46707338740000.html
3,46707357690000,TOWNHOUSE,0309,rv-cd,28.0,91.0,1.00,0,1.00,.058 AC,...,1.00,LT,1.000,"76,000.00","76,000.00",NaN,28.0,1.00,"76,000.00",46707357690000.html
4,46707350990000,SFR,0100,R-CO,0.0,0.0,1.00,0,1.00,.14 AC,...,1.00,LT,1.000,"90,000.00","90,000.00",NaN,0.0,1.00,"90,000.00",46707350990000.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99169,66023336930000,RURAL AC,120,AO,16.0,NaN,2.18,4,0.96,NaN,...,1.19,AC,2.089,"24,023.50","28,588.00",NaN,16.0,1.19,"28,588.00",66023336930000.html
99170,56902529920000,RURAL AC,120,AO,564.0,NaN,1.12,4,1.02,NaN,...,10.81,AC,1.144,"19,448.00","210,233.00",NaN,564.0,10.81,"210,233.00",56902529920000.html
99171,66020121510000,WAREHOUSNG,648,AO,679.0,0.0,1.02,4,1.01,NaN,...,19.65,AC,1.032,"11,868.00","233,206.00",NaN,679.0,19.65,"233,206.00",66020121510000.html
99172,66022571130000,RURAL AC,120,AO,NaN,NaN,1.22,4,0.85,NaN,...,6.28,AC,1.040,"11,960.00","75,109.00",NaN,NaN,6.28,"75,109.00",66022571130000.html
99173,66022012680000,RURAL AC,120,AO,0.0,0.0,1.07,4,0.70,NaN,...,13.90,AC,0.751,"8,636.50","120,047.00",NaN,0.0,13.90,"120,047.00",66022012680000.html

In [11]:
df['land_use'].value_counts()

land_use
SFR           66378
RURAL AC      13164
TOWNHOUSE      4740
COMMERCIAL     2987
MBL HM SUB     1645
              ...
MF COMMON         1
LUMBER YRD        1
PARKING           1
POULT/TRKY        1
HOG FARMS         1
Name: count, Length: 127, dtype: int64

In [12]:
df['use_code'].value_counts()

use_code
0100    44893
100     21485
0120     7786
120      5378
0309     3499
        ...
8800        1
9010        1
728         1
658         1
656         1
Name: count, Length: 219, dtype: int64

In [13]:
df[df['use_code'] == '0100']

,parcel_number,land_use,use_code,zoning,frontage,depth,depth_factor,land_model,condition_factor,adjustments,...,units,unit_type,total_adjustment,adjusted_unit_price,land_value,notes,total_market_frontage,total_market_units,total_market_land_value,page_save
1,46707324050000,SFR,0100,R-CO,171.0,137.0,1.00,0,1.00,NaN,...,1.00,LT,1.000,"90,000.00","90,000.00",.26 AC,171.0,1.00,"90,000.00",46707324050000.html
4,46707350990000,SFR,0100,R-CO,0.0,0.0,1.00,0,1.00,.14 AC,...,1.00,LT,1.000,"90,000.00","90,000.00",NaN,0.0,1.00,"90,000.00",46707350990000.html
5,46706951200000,SFR,0100,LDR,65.0,135.0,1.00,0,1.00,.20 AC,...,1.00,LT,1.000,"130,000.00","130,000.00",NaN,65.0,1.00,"130,000.00",46706951200000.html
9,46707457780000,SFR,0100,RV,103.0,139.0,1.00,0,1.00,.24 AC,...,1.00,LT,1.000,"165,000.00","165,000.00",NaN,103.0,1.00,"165,000.00",46707457780000.html
14,46707533450000,SFR,0100,RV,81.0,155.0,1.00,0,1.00,.29 AC,...,1.00,LT,1.000,"165,000.00","165,000.00",NaN,81.0,1.00,"165,000.00",46707533450000.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65522,55074759720000,SFR,0100,RM,100.0,205.0,1.00,0,1.00,NaN,...,1.00,LT,1.000,"65,000.00","65,000.00",NaN,100.0,1.00,"65,000.00",55074759720000.html
65525,56221900040000,SFR,0100,RV,100.0,150.0,1.00,0,1.00,NaN,...,1.00,LT,1.000,"47,000.00","47,000.00",NaN,100.0,1.00,"47,000.00",56221900040000.html
65528,56132479570000,SFR,0100,R8,50.0,150.0,1.00,0,1.00,SZE,...,1.00,LT,1.000,"53,000.00","53,000.00",NaN,50.0,1.00,"53,000.00",56132479570000.html
65534,55074896660000,SFR,0100,RM,100.0,205.0,1.00,0,1.00,NaN,...,1.00,LT,1.000,"65,000.00","65,000.00",NaN,100.0,1.00,"65,000.00",55074896660000.html
65535,56036501580000,SFR,0100,AG,156.0,NaN,2.18,8,0.64,NaN,...,1.36,AC,1.393,"90,545.00","123,141.00",0.14 FLD,NaN,0.14,210.00,56036501580000.html

In [14]:
df['zoning'].value_counts()

zoning
AO         9445
RC         8306
R4         7830
LDR        6983
RV         6537
           ...
O-ISU         1
LOCUST        1
PRD-CZ        1
CZ-RM-1       1
I1-CD         1
Name: count, Length: 116, dtype: int64

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99174 entries, 0 to 99173
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   parcel_number            99174 non-null  int64
 1   land_use                 99174 non-null  object
 2   use_code                 99174 non-null  object
 3   zoning                   99169 non-null  object
 4   frontage                 96854 non-null  float64
 5   depth                    84176 non-null  float64
 6   depth_factor             99174 non-null  float64
 7   land_model               99174 non-null  int64
 8   condition_factor         99174 non-null  float64
 9   adjustments              35561 non-null  object
 10  road_type                95015 non-null  object
 11  unit_price               99174 non-null  object
 12  units                    99174 non-null  float64
 13  unit_type                99174 non-null  object
 14  total_adjustment         99174 non-null  float64
 15  adjusted_unit_price      97866 non-null  object
 16  land_value               97952 non-null  object
 17  notes                    13490 non-null  object
 18  total_market_frontage    94894 non-null  float64
 19  total_market_units       99174 non-null  float64
 20  total_market_land_value  97846 non-null  object
 21  page_save                99174 non-null  object
dtypes: float64(8), int64(2), object(12)
memory usage: 16.6+ MB

In [16]:
df['adjustments'].value_counts()

adjustments
SZE                     3325
SZ                      2707
RP                      1015
.17 AC                   846
.16 AC                   845
                        ...
-35STREAM                  1
Narrow Shape               1
30FT UTILITES EASEME       1
shape and pond             1
.428ac                     1
Name: count, Length: 4843, dtype: int64

# Case 5: Converted columns to integer

In [17]:
df['frontage'].value_counts()

frontage
100.0     4970
75.0      4733
50.0      4196
60.0      4011
0.0       3398
          ...
1547.0       1
1771.0       1
2861.0       1
2960.0       1
1416.0       1
Name: count, Length: 1742, dtype: int64

In [18]:
df['frontage'] = df['frontage'].astype('Int64')

In [19]:
df['frontage'].value_counts()

frontage
100     4970
75      4733
50      4196
60      4011
0       3398
        ...
1547       1
1771       1
2861       1
2960       1
1416       1
Name: count, Length: 1742, dtype: Int64

In [20]:
df['depth'].value_counts()

depth
0.0       14385
150.0      4837
200.0      2446
120.0      1918
140.0      1515
          ...
949.0         1
744.0         1
1043.0        1
1766.0        1
682.0         1
Name: count, Length: 976, dtype: int64

In [21]:
df['depth'] = df['depth'].astype('Int64')

In [22]:
df['depth'].value_counts()

depth
0       14385
150      4837
200      2446
120      1918
140      1515
        ...
949         1
744         1
1043        1
1766        1
682         1
Name: count, Length: 976, dtype: Int64

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99174 entries, 0 to 99173
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   parcel_number            99174 non-null  int64
 1   land_use                 99174 non-null  object
 2   use_code                 99174 non-null  object
 3   zoning                   99169 non-null  object
 4   frontage                 96854 non-null  Int64
 5   depth                    84176 non-null  Int64
 6   depth_factor             99174 non-null  float64
 7   land_model               99174 non-null  int64
 8   condition_factor         99174 non-null  float64
 9   adjustments              35561 non-null  object
 10  road_type                95015 non-null  object
 11  unit_price               99174 non-null  object
 12  units                    99174 non-null  float64
 13  unit_type                99174 non-null  object
 14  total_adjustment         99174 non-null  float64
 15  adjusted_unit_price      97866 non-null  object
 16  land_value               97952 non-null  object
 17  notes                    13490 non-null  object
 18  total_market_frontage    94894 non-null  float64
 19  total_market_units       99174 non-null  float64
 20  total_market_land_value  97846 non-null  object
 21  page_save                99174 non-null  object
dtypes: Int64(2), float64(6), int64(2), object(12)
memory usage: 16.8+ MB

In [24]:
df['land_model'].value_counts()

land_model
0    77892
4    13795
8     3999
7     1384
6     1276
2      502
3      321
1        5
Name: count, dtype: int64

In [25]:
df['road_type'].value_counts()

road_type
PS    70923
RP    13558
PW     5105
PD     2857
NX      813
RT      607
RD      551
RG      346
SP      120
SD       92
AC       11
UT        9
UP        6
UD        6
S         2
PR        1
ER        1
E         1
[S        1
OS        1
OW        1
LT        1
RS        1
SZ        1
Name: count, dtype: int64

# Case 6: REplaced '[' with blank space

In [26]:
df[df['road_type'] == '[S']

,parcel_number,land_use,use_code,zoning,frontage,depth,depth_factor,land_model,condition_factor,adjustments,...,units,unit_type,total_adjustment,adjusted_unit_price,land_value,notes,total_market_frontage,total_market_units,total_market_land_value,page_save
34635,56019674610000,SFR,0100,RV,62,162,1.0,0,1.0,.24 AC,...,1.0,LT,1.0,"75,000.00","75,000.00",NaN,62.0,1.0,"75,000.00",56019674610000.html

In [27]:
df['road_type'] = df['road_type'].replace('[S', 'S')

In [28]:
df[df['road_type'] == 'S']

,parcel_number,land_use,use_code,zoning,frontage,depth,depth_factor,land_model,condition_factor,adjustments,...,units,unit_type,total_adjustment,adjusted_unit_price,land_value,notes,total_market_frontage,total_market_units,total_market_land_value,page_save
34635,56019674610000,SFR,0100,RV,62,162,1.0,0,1.0,.24 AC,...,1.0,LT,1.0,"75,000.00","75,000.00",NaN,62.0,1.0,"75,000.00",56019674610000.html
43062,46717325240000,TOWNHOUSE,0309,RV,23,<NA>,1.0,0,1.0,NaN,...,1.0,LT,1.0,"82,000.00","82,000.00",NaN,23.0,1.0,"82,000.00",46717325240000.html
94024,56305864470000,SFR,100,RM-1,79,180,1.0,0,1.2,LOC SZ,...,1.0,LT,1.2,"75,600.00","75,600.00",NaN,79.0,1.0,"75,600.00",56305864470000.html

In [29]:
df['unit_price'].value_counts()

unit_price
19,000.00     7339
100,000.00    4874
65,000.00     4443
80,000.00     4102
50,000.00     3958
              ...
325,000.00       1
400.00           1
205,000.00       1
67,001.00        1
1,900.00         1
Name: count, Length: 262, dtype: int64

# Case 7: Replaced ',' and 'XXXX' with blank space

In [30]:
df['unit_price'] = (
    df['unit_price']
        .astype(str)
        .str.replace(',', '', regex=True)
        .str.strip()
)

df['unit_price'] = df['unit_price'].replace('XXXX', np.nan).astype(float)

In [31]:
df['unit_price'].value_counts()

unit_price
19000.0     7339
100000.0    4874
65000.0     4443
80000.0     4102
50000.0     3958
            ...
325000.0       1
400.0          1
205000.0       1
67001.0        1
1900.0         1
Name: count, Length: 261, dtype: int64

In [32]:
df['units'].value_counts()

units
1.000     72760
2.000      1788
3.000       365
1.500       343
4.000       197
          ...
42.830        1
25.561        1
13.485        1
0.864         1
3.974         1
Name: count, Length: 7766, dtype: int64

In [33]:
df['unit_type'].value_counts()

unit_type
LT    73087
AC    22178
SF     1984
UT     1098
FF      827
Name: count, dtype: int64

In [34]:
df['adjusted_unit_price'].value_counts()

adjusted_unit_price
100,000.00    4548
80,000.00     3760
65,000.00     3749
70,000.00     3371
90,000.00     2893
              ...
9,970.50         1
15,122.50        1
16,203.50        1
25,461.00        1
9,706.00         1
Name: count, Length: 12050, dtype: int64

# Case 8:Replaced ',' and 'XXXX' with blank space

In [35]:
cols = ['adjusted_unit_price', 'total_market_land_value', 'land_value']

df[cols] = (
    df[cols]
        .astype(str)
        .apply(lambda col: (
            col.str.replace(',', '', regex=True)    # remove commas
               .str.replace('XXXX', '', regex=False)  # replace XXXX with empty string
               .str.strip()
        ))
        .replace('', np.nan)  # convert empty strings to NaN
)

In [36]:
df[cols]

      adjusted_unit_price total_market_land_value land_value
0                80000.00                80000.00   80000.00
1                90000.00                90000.00   90000.00
2                76000.00                76000.00   76000.00
3                76000.00                76000.00   76000.00
4                90000.00                90000.00   90000.00
...                   ...                     ...        ...
99169            24023.50                28588.00   28588.00
99170            19448.00               210233.00  210233.00
99171            11868.00               233206.00  233206.00
99172            11960.00                75109.00   75109.00
99173             8636.50               120047.00  120047.00

[99174 rows x 3 columns]

In [37]:
df['notes'].value_counts()

notes
SHP           513
0.01 FLD      204
0.00 FLD      203
FLD           152
SIZE          144
             ...
ACC ROAD        1
1.960AC         1
PERK/R.O.W      1
PRK/SHP         1
NO PERK'05      1
Name: count, Length: 2829, dtype: int64

In [38]:
df[df['notes'].str.len() == 1]

,parcel_number,land_use,use_code,zoning,frontage,depth,depth_factor,land_model,condition_factor,adjustments,...,units,unit_type,total_adjustment,adjusted_unit_price,land_value,notes,total_market_frontage,total_market_units,total_market_land_value,page_save
17055,55295976050000,TOWNHOUSE,0309,RV,39,<NA>,1.00,0,0.30,SZE/TOPO,...,1.000,LT,0.300,14400.00,14400.00,R,39.0,1.000,14400.00,55295976050000.html
23730,55296454870000,SFR,0100,RC,50,142,1.00,0,1.00,.16 AC,...,1.000,LT,1.000,65000.00,65000.00,.,50.0,1.000,65000.00,55296454870000.html
23923,55296071410000,SFR,0100,LDR,290,<NA>,1.25,4,0.76,SHP,...,5.650,AC,0.948,26544.00,149974.00,S,NaN,0.770,1155.00,55296071410000.html
43020,55092750410000,SFR,0100,RV,71,126,1.00,0,1.00,NaN,...,1.000,LT,1.000,90000.00,90000.00,.,71.0,1.000,90000.00,55092750410000.html
48761,46811666350000,TOWNHOUSE,0309,RM-2-CU,38,98,1.00,0,1.00,.09 AC,...,1.000,LT,1.000,76000.00,76000.00,\,38.0,1.000,76000.00,46811666350000.html
61768,46913500670000,SFR,0100,CR,200,0,1.00,0,1.00,NaN,...,1.000,LT,1.000,90000.00,90000.00,.,200.0,1.000,90000.00,46913500670000.html
66489,56039894290000,TOWNHOUSE,309,R18,20,<NA>,1.00,0,1.00,NaN,...,1.000,LT,1.000,50000.00,50000.00,R,20.0,1.000,50000.00,56039894290000.html
67885,56213097820000,TOWNHOUSE,309,RC,20,75,1.00,0,1.00,.047ac,...,1.000,LT,1.000,55000.00,55000.00,R,20.0,1.000,55000.00,56213097820000.html
72238,56213096980000,TOWNHOUSE,309,RC,20,75,1.00,0,1.00,.035ac,...,1.000,LT,1.000,55000.00,55000.00,R,20.0,1.000,55000.00,56213096980000.html
75355,56214006050000,TOWNHOUSE,309,RC,35,75,1.00,0,1.00,.06ac,...,1.000,LT,1.000,55000.00,55000.00,R,35.0,1.000,55000.00,56214006050000.html
75742,56301153550000,SFR,100,RM-2,75,211,1.00,0,1.00,NaN,...,1.000,LT,1.000,80000.00,80000.00,+,75.0,1.000,80000.00,56301153550000.html
88131,56213097160000,TOWNHOUSE,309,RC,27,75,1.00,0,1.00,.047ac,...,1.000,LT,1.000,55000.00,55000.00,R,27.0,1.000,55000.00,56213097160000.html
88551,55192320950000,SFR,100,CURV,0,0,1.00,0,1.00,.30 AC,...,1.000,LT,1.000,80000.00,80000.00,0,0.0,1.000,80000.00,55192320950000.html
90095,56126546490000,SFR,100,R4,100,163,1.00,0,0.50,TOPO,...,1.000,LT,0.500,32500.00,32500.00,O,100.0,1.000,32500.00,56126546490000.html
94435,56213097900000,TOWNHOUSE,309,RC,20,75,1.00,0,1.00,.035ac,...,1.000,LT,1.000,55000.00,55000.00,R,20.0,1.000,55000.00,56213097900000.html
96623,56636046550000,RURAL AC,120,AO,100,<NA>,1.16,4,0.96,NaN,...,8.919,AC,1.111,12776.50,113954.00,R,100.0,8.919,113954.00,56636046550000.html
98758,56523960900000,RURAL AC,120,AO,404,0,1.20,4,0.89,NaN,...,6.890,AC,1.071,20349.00,140205.00,.,0.0,3.110,4665.00,56523960900000.html

# Case 9: REPlaced 'R', 'O', '0', '+', '.', "\\",'S' with blank space

In [39]:
df['notes'] = df['notes'].replace(['R', 'O', '0', '+', '.', "\\",'S'], np.nan)

In [40]:
df[df['notes'].str.len() == 1]

Empty DataFrame
Columns: [parcel_number, land_use, use_code, zoning, frontage, depth, depth_factor, land_model, condition_factor, adjustments, road_type, unit_price, units, unit_type, total_adjustment, adjusted_unit_price, land_value, notes, total_market_frontage, total_market_units, total_market_land_value, page_save]
Index: []

[0 rows x 22 columns]

In [41]:
zero_cols = df.columns[(df == 0).any()].tolist()
print(zero_cols)

['frontage', 'depth', 'land_model', 'condition_factor', 'unit_price', 'units', 'total_adjustment', 'total_market_frontage', 'total_market_units']

# Case 10: Replaced 0 with blank space

In [42]:
colls = ['frontage', 'depth', 'land_model','total_market_frontage']

df[colls] = df[colls].replace(0, np.nan).astype('Int64')

In [43]:
coll = ['condition_factor', 'unit_price', 'units', 'total_adjustment', 'total_market_units', ]
df[coll] = df[coll].replace(0, np.nan).astype(float)

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99174 entries, 0 to 99173
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   parcel_number            99174 non-null  int64
 1   land_use                 99174 non-null  object
 2   use_code                 99174 non-null  object
 3   zoning                   99169 non-null  object
 4   frontage                 93456 non-null  Int64
 5   depth                    69791 non-null  Int64
 6   depth_factor             99174 non-null  float64
 7   land_model               21282 non-null  Int64
 8   condition_factor         99173 non-null  float64
 9   adjustments              35561 non-null  object
 10  road_type                95015 non-null  object
 11  unit_price               96865 non-null  float64
 12  units                    99159 non-null  float64
 13  unit_type                99174 non-null  object
 14  total_adjustment         99173 non-null  float64
 15  adjusted_unit_price      98667 non-null  object
 16  land_value               98667 non-null  object
 17  notes                    13473 non-null  object
 18  total_market_frontage    90796 non-null  Int64
 19  total_market_units       99168 non-null  float64
 20  total_market_land_value  98667 non-null  object
 21  page_save                99174 non-null  object
dtypes: Int64(4), float64(6), int64(1), object(11)
memory usage: 17.0+ MB

# Case 11: Converted column to float

In [45]:
df['total_market_land_value'].value_counts()

total_market_land_value
100000.00     4567
80000.00      3770
65000.00      3716
70000.00      3364
90000.00      2931
              ...
108106.00        1
1161614.00       1
205159.00        1
26288.00         1
297160.00        1
Name: count, Length: 19041, dtype: int64

In [46]:
df['total_market_land_value'] = df['total_market_land_value'].astype(float)

In [47]:
df['total_market_land_value'].value_counts()

total_market_land_value
100000.0    4567
80000.0     3770
65000.0     3716
70000.0     3364
90000.0     2931
            ...
41371.0        1
55668.0        1
53587.0        1
65813.0        1
224098.0       1
Name: count, Length: 19040, dtype: int64

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99174 entries, 0 to 99173
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   parcel_number            99174 non-null  int64
 1   land_use                 99174 non-null  object
 2   use_code                 99174 non-null  object
 3   zoning                   99169 non-null  object
 4   frontage                 93456 non-null  Int64
 5   depth                    69791 non-null  Int64
 6   depth_factor             99174 non-null  float64
 7   land_model               21282 non-null  Int64
 8   condition_factor         99173 non-null  float64
 9   adjustments              35561 non-null  object
 10  road_type                95015 non-null  object
 11  unit_price               96865 non-null  float64
 12  units                    99159 non-null  float64
 13  unit_type                99174 non-null  object
 14  total_adjustment         99173 non-null  float64
 15  adjusted_unit_price      98667 non-null  object
 16  land_value               98667 non-null  object
 17  notes                    13473 non-null  object
 18  total_market_frontage    90796 non-null  Int64
 19  total_market_units       99168 non-null  float64
 20  total_market_land_value  97339 non-null  float64
 21  page_save                99174 non-null  object
dtypes: Int64(4), float64(7), int64(1), object(10)
memory usage: 17.0+ MB

# Case 12: Placing the file

In [49]:
df.to_csv(r"D:\North Carolina\Cabarrus\Property\Cleaned_Data\us_nc_37025_data_prop_land_silver_20251127.csv", index=False)
df

,parcel_number,land_use,use_code,zoning,frontage,depth,depth_factor,land_model,condition_factor,adjustments,...,units,unit_type,total_adjustment,adjusted_unit_price,land_value,notes,total_market_frontage,total_market_units,total_market_land_value,page_save
0,46707245420000,TWH GOLF,0383,LDR,28,88,1.00,<NA>,1.00,.06 AC,...,1.00,LT,1.000,80000.00,80000.00,VIEW,28,1.00,80000.0,46707245420000.html
1,46707324050000,SFR,0100,R-CO,171,137,1.00,<NA>,1.00,NaN,...,1.00,LT,1.000,90000.00,90000.00,.26 AC,171,1.00,90000.0,46707324050000.html
2,46707338740000,TOWNHOUSE,0309,rv-cd,35,<NA>,1.00,<NA>,1.00,.079 AC,...,1.00,LT,1.000,76000.00,76000.00,NaN,35,1.00,76000.0,46707338740000.html
3,46707357690000,TOWNHOUSE,0309,rv-cd,28,91,1.00,<NA>,1.00,.058 AC,...,1.00,LT,1.000,76000.00,76000.00,NaN,28,1.00,76000.0,46707357690000.html
4,46707350990000,SFR,0100,R-CO,<NA>,<NA>,1.00,<NA>,1.00,.14 AC,...,1.00,LT,1.000,90000.00,90000.00,NaN,<NA>,1.00,90000.0,46707350990000.html
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99169,66023336930000,RURAL AC,120,AO,16,<NA>,2.18,4,0.96,NaN,...,1.19,AC,2.089,24023.50,28588.00,NaN,16,1.19,28588.0,66023336930000.html
99170,56902529920000,RURAL AC,120,AO,564,<NA>,1.12,4,1.02,NaN,...,10.81,AC,1.144,19448.00,210233.00,NaN,564,10.81,210233.0,56902529920000.html
99171,66020121510000,WAREHOUSNG,648,AO,679,<NA>,1.02,4,1.01,NaN,...,19.65,AC,1.032,11868.00,233206.00,NaN,679,19.65,233206.0,66020121510000.html
99172,66022571130000,RURAL AC,120,AO,<NA>,<NA>,1.22,4,0.85,NaN,...,6.28,AC,1.040,11960.00,75109.00,NaN,<NA>,6.28,75109.0,66022571130000.html
99173,66022012680000,RURAL AC,120,AO,<NA>,<NA>,1.07,4,0.70,NaN,...,13.90,AC,0.751,8636.50,120047.00,NaN,<NA>,13.90,120047.0,66022012680000.html