In [1]:
import pandas as pd
import numpy as np

# Case 1: Reading csv

In [2]:
df = pd.read_csv(r"D:\North Carolina\Cabarrus\Property\Raw_Data\us_nc_37025_data_prop_location-codes_bronze_20251127.csv")
df

         parcel_number  category code  description            page_save
0       46707318010000  Township   02  Poplar Tent  46707318010000.html
1       46707318010000      City   02      Concord  46707318010000.html
2       46707318010000      Fire   11        Odell  46707318010000.html
3       46707245420000  Township   02  Poplar Tent  46707245420000.html
4       46707245420000      City   00        Rural  46707245420000.html
...                ...       ...  ...          ...                  ...
299719  66022012680000      City   00        Rural  66022012680000.html
299720  66022012680000      Fire   15    Northeast  66022012680000.html
299721  66022571130000  Township   07    Gold Hill  66022571130000.html
299722  66022571130000      City   00        Rural  66022571130000.html
299723  66022571130000      Fire   18    Richfield  66022571130000.html

[299724 rows x 5 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299724 entries, 0 to 299723
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   parcel_number  299724 non-null  int64
 1   category       299724 non-null  object
 2   code           299724 non-null  object
 3   description    299724 non-null  object
 4   page_save      299724 non-null  object
dtypes: int64(1), object(4)
memory usage: 11.4+ MB

# Case 2: Handling multi spaces

In [4]:
import re
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].apply(lambda x: re.sub(r'\s+', ' ', x).strip() if isinstance(x, str) else x)

# Case 3: Checking fake nulls

In [5]:
# Define fake null values
fake_nulls = ['', 'null', 'none', 'nan', "None", 'na', 'n/a', 'n.a.', 'NaN', 'NAN', 'NULL', 'nil', 'Nan', 'Null','NONE']
 
# ✅ Now check and replace in all columns
for col in df.columns:
    mask = df[col].astype(str).str.lower().isin([str(x).lower() for x in fake_nulls])
    problem_rows = df.loc[mask, [col]]
   
    if not problem_rows.empty:
        print(f"Rows where '{col}' has fake nulls:")
        print(problem_rows)
        # Replace fake nulls with NaN
        df[col] = df[col].replace(fake_nulls, np.nan)
 
# Optional: Summary of NaNs per column
print("\nNaN count per column:")
print(df.isna().sum())
 
# Show final cleaned DataFrame
print("\nCleaned DataFrame:")
print(df)

NaN count per column:
parcel_number    0
category         0
code             0
description      0
page_save        0
dtype: int64

Cleaned DataFrame:
         parcel_number  category code  description            page_save
0       46707318010000  Township   02  Poplar Tent  46707318010000.html
1       46707318010000      City   02      Concord  46707318010000.html
2       46707318010000      Fire   11        Odell  46707318010000.html
3       46707245420000  Township   02  Poplar Tent  46707245420000.html
4       46707245420000      City   00        Rural  46707245420000.html
...                ...       ...  ...          ...                  ...
299719  66022012680000      City   00        Rural  66022012680000.html
299720  66022012680000      Fire   15    Northeast  66022012680000.html
299721  66022571130000  Township   07    Gold Hill  66022571130000.html
299722  66022571130000      City   00        Rural  66022571130000.html
299723  66022571130000      Fire   18    Richfield  66022571130000.html

[299724 rows x 5 columns]

In [6]:
df

         parcel_number  category code  description            page_save
0       46707318010000  Township   02  Poplar Tent  46707318010000.html
1       46707318010000      City   02      Concord  46707318010000.html
2       46707318010000      Fire   11        Odell  46707318010000.html
3       46707245420000  Township   02  Poplar Tent  46707245420000.html
4       46707245420000      City   00        Rural  46707245420000.html
...                ...       ...  ...          ...                  ...
299719  66022012680000      City   00        Rural  66022012680000.html
299720  66022012680000      Fire   15    Northeast  66022012680000.html
299721  66022571130000  Township   07    Gold Hill  66022571130000.html
299722  66022571130000      City   00        Rural  66022571130000.html
299723  66022571130000      Fire   18    Richfield  66022571130000.html

[299724 rows x 5 columns]

In [7]:
df['category'].value_counts()

category
Township             99174
City                 99174
Fire                 99174
Special District      1783
Business District      419
Name: count, dtype: int64

In [8]:
df['code'].value_counts()

code
00    98548
02    60085
04    44719
01    25863
11    14772
03    12094
12     8537
05     5083
10     4975
08     4594
07     4372
06     4290
09     2812
16     2696
13     1519
T4     1302
14     1211
15      865
B4      419
T1      345
17      268
18      151
CD      136
19       34
20       34
Name: count, dtype: int64

In [9]:
df[df['code'].str.len() == 1]

Empty DataFrame
Columns: [parcel_number, category, code, description, page_save]
Index: []

In [10]:
df

         parcel_number  category code  description            page_save
0       46707318010000  Township   02  Poplar Tent  46707318010000.html
1       46707318010000      City   02      Concord  46707318010000.html
2       46707318010000      Fire   11        Odell  46707318010000.html
3       46707245420000  Township   02  Poplar Tent  46707245420000.html
4       46707245420000      City   00        Rural  46707245420000.html
...                ...       ...  ...          ...                  ...
299719  66022012680000      City   00        Rural  66022012680000.html
299720  66022012680000      Fire   15    Northeast  66022012680000.html
299721  66022571130000  Township   07    Gold Hill  66022571130000.html
299722  66022571130000      City   00        Rural  66022571130000.html
299723  66022571130000      Fire   18    Richfield  66022571130000.html

[299724 rows x 5 columns]

In [11]:
df['description'].value_counts()

description
City                         73828
Concord                      50171
Kannapolis                   41706
Rural                        24720
Harrisburg                   24556
Poplar Tent                  17703
Odell                        13345
Central Cabarrus             10690
Midland                       9996
Georgeville                   3629
MT Pleasant                   3552
Mt. Pleasant                  3184
Harrisburg Outside City       3101
Allen                         3013
New Gilead                    2358
Cold Water                    1975
Gold Hill                     1539
Rimertown                     1505
Rimer                         1404
Kannapolis Rural              1307
Kannapolis TIF District       1302
Flowes Store                  1211
Northeast                      865
Jackson Park                   748
MT Mitchell                    702
Locust                         489
Kannapolis Business            419
Harrisburg TIF District        345
Richfield                      151
Concord Downtown District      136
Concord Rural                   34
Harrisburg Inside City          34
Huntersville                     6
Name: count, dtype: int64

In [12]:
df

         parcel_number  category code  description            page_save
0       46707318010000  Township   02  Poplar Tent  46707318010000.html
1       46707318010000      City   02      Concord  46707318010000.html
2       46707318010000      Fire   11        Odell  46707318010000.html
3       46707245420000  Township   02  Poplar Tent  46707245420000.html
4       46707245420000      City   00        Rural  46707245420000.html
...                ...       ...  ...          ...                  ...
299719  66022012680000      City   00        Rural  66022012680000.html
299720  66022012680000      Fire   15    Northeast  66022012680000.html
299721  66022571130000  Township   07    Gold Hill  66022571130000.html
299722  66022571130000      City   00        Rural  66022571130000.html
299723  66022571130000      Fire   18    Richfield  66022571130000.html

[299724 rows x 5 columns]

# Case 4: Placing the file

In [13]:
df.to_csv(r"D:\North Carolina\Cabarrus\Property\Cleaned_Data\us_nc_37025_data_prop_location-codes_silver_20251127.csv", index=False)
df

         parcel_number  category code  description            page_save
0       46707318010000  Township   02  Poplar Tent  46707318010000.html
1       46707318010000      City   02      Concord  46707318010000.html
2       46707318010000      Fire   11        Odell  46707318010000.html
3       46707245420000  Township   02  Poplar Tent  46707245420000.html
4       46707245420000      City   00        Rural  46707245420000.html
...                ...       ...  ...          ...                  ...
299719  66022012680000      City   00        Rural  66022012680000.html
299720  66022012680000      Fire   15    Northeast  66022012680000.html
299721  66022571130000  Township   07    Gold Hill  66022571130000.html
299722  66022571130000      City   00        Rural  66022571130000.html
299723  66022571130000      Fire   18    Richfield  66022571130000.html

[299724 rows x 5 columns]