In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\North Carolina\Cabarrus\Property\Raw_Data\us_nc_37025_data_prop_sales_bronze_20251127.csv")
df

,parcel_number,book,page,sale_date,deed_type,qualified_unqualified,sales_price,vacant_improved,instrument_number,page_save
0,46707348030000,15522,0001,09/24/2021,SW,Unqualified,"401,500",Vacant,SW,46707348030000.html
1,46707348030000,15810,0286,01/27/2022,SW,Qualified,"369,000",Improved,SW,46707348030000.html
2,46707318010000,15887,0077,03/03/2022,SW,Unqualified,"401,500",Improved,SW,46707318010000.html
3,46707318010000,16109,0163,07/11/2022,SW,Qualified,"399,000",Improved,SW,46707318010000.html
4,46707533450000,4992,0047,11/18/2003,SW,Unqualified,0,Vacant,SW,46707533450000.html
...,...,...,...,...,...,...,...,...,...,...
291546,56617851540000,682,0064,09/03/1988,GW,Unqualified,0,Vacant,GW,56617851540000.html
291547,66010853060000,6591,0055,03/07/2006,QF,Unqualified,"60,500",Vacant,QF,66010853060000.html
291548,56934560820000,442,661,05/01/1974,WD,Qualified,"12,000",Vacant,WD,56934560820000.html
291549,56928189020000,3946,0306,08/08/2002,GW,Unqualified,0,Vacant,GW,56928189020000.html
291550,56928189020000,5682,0038,12/01/2004,GW,Unqualified,0,Vacant,GW,56928189020000.html

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291551 entries, 0 to 291550
Data columns (total 10 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   parcel_number          291551 non-null  int64
 1   book                   291512 non-null  object
 2   page                   291510 non-null  object
 3   sale_date              291551 non-null  object
 4   deed_type              289958 non-null  object
 5   qualified_unqualified  288960 non-null  object
 6   sales_price            288960 non-null  object
 7   vacant_improved        288960 non-null  object
 8   instrument_number      289958 non-null  object
 9   page_save              291551 non-null  object
dtypes: int64(1), object(9)
memory usage: 22.2+ MB

# Case 2: Handling multi spaces

In [4]:
import re
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].apply(lambda x: re.sub(r'\s+', ' ', x).strip() if isinstance(x, str) else x)

# Case 3: Checking fake nulls

In [5]:
# Define fake null values
fake_nulls = ['', 'null', 'none', 'nan', "None", 'na', 'n/a', 'n.a.', 'NaN', 'NAN', 'NULL', 'nil', 'Nan', 'Null','NONE']
 
# ✅ Now check and replace in all columns
for col in df.columns:
    mask = df[col].astype(str).str.lower().isin([str(x).lower() for x in fake_nulls])
    problem_rows = df.loc[mask, [col]]
   
    if not problem_rows.empty:
        print(f"Rows where '{col}' has fake nulls:")
        print(problem_rows)
        # Replace fake nulls with NaN
        df[col] = df[col].replace(fake_nulls, np.nan)
 
# Optional: Summary of NaNs per column
print("\nNaN count per column:")
print(df.isna().sum())
 
# Show final cleaned DataFrame
print("\nCleaned DataFrame:")
print(df)

Rows where 'book' has fake nulls:
       book
7170    NaN
36183   NaN
40627   NaN
40783   NaN
41548   NaN
42215   NaN
45007   NaN
47057   NaN
48179   NaN
48230   NaN
51243   NaN
55994   NaN
65817   NaN
73504   NaN
74065   NaN
76094   NaN
81666   NaN
90176   NaN
90227   NaN
92446   NaN
93994   NaN
105217  NaN
115880  NaN
126892  NaN
130215  NaN
137714  NaN
137964  NaN
139481  NaN
140629  NaN
156857  NaN
178917  NaN
181125  NaN
190742  NaN
192408  NaN
202718  NaN
207958  NaN
209687  NaN
225552  NaN
234967  NaN
Rows where 'page' has fake nulls:
       page
7170    NaN
36183   NaN
40627   NaN
40783   NaN
41548   NaN
42215   NaN
45007   NaN
47057   NaN
48179   NaN
48230   NaN
50209   NaN
51243   NaN
55994   NaN
65817   NaN
73504   NaN
74065   NaN
76094   NaN
81666   NaN
90176   NaN
90227   NaN
92446   NaN
93994   NaN
105217  NaN
115880  NaN
126892  NaN
130215  NaN
137714  NaN
137964  NaN
139481  NaN
139569  NaN
140629  NaN
156857  NaN
178917  NaN
181125  NaN
190742  NaN
192408  NaN
202718  NaN
207958  NaN
209687  NaN
225552  NaN
234967  NaN
Rows where 'deed_type' has fake nulls:
       deed_type
209          NaN
2388         NaN
2622         NaN
3057         NaN
3076         NaN
...          ...
290963       NaN
291201       NaN
291326       NaN
291367       NaN
291373       NaN

[1593 rows x 1 columns]
Rows where 'qualified_unqualified' has fake nulls:
       qualified_unqualified
17                       NaN
30                       NaN
49                       NaN
96                       NaN
106                      NaN
...                      ...
286986                   NaN
287571                   NaN
287638                   NaN
291467                   NaN
291468                   NaN

[2591 rows x 1 columns]
Rows where 'sales_price' has fake nulls:
       sales_price
17             NaN
30             NaN
49             NaN
96             NaN
106            NaN
...            ...
286986         NaN
287571         NaN
287638         NaN
291467         NaN
291468         NaN

[2591 rows x 1 columns]
Rows where 'vacant_improved' has fake nulls:
       vacant_improved
17                 NaN
30                 NaN
49                 NaN
96                 NaN
106                NaN
...                ...
286986             NaN
287571             NaN
287638             NaN
291467             NaN
291468             NaN

[2591 rows x 1 columns]
Rows where 'instrument_number' has fake nulls:
       instrument_number
209                  NaN
2388                 NaN
2622                 NaN
3057                 NaN
3076                 NaN
...                  ...
290963               NaN
291201               NaN
291326               NaN
291367               NaN
291373               NaN

[1593 rows x 1 columns]

NaN count per column:
parcel_number               0
book                       39
page                       41
sale_date                   0
deed_type                1593
qualified_unqualified    2591
sales_price              2591
vacant_improved          2591
instrument_number        1593
page_save                   0
dtype: int64

Cleaned DataFrame:
         parcel_number   book  page   sale_date deed_type  \
0       46707348030000  15522  0001  09/24/2021        SW
1       46707348030000  15810  0286  01/27/2022        SW
2       46707318010000  15887  0077  03/03/2022        SW
3       46707318010000  16109  0163  07/11/2022        SW
4       46707533450000   4992  0047  11/18/2003        SW
...                ...    ...   ...         ...       ...
291546  56617851540000    682  0064  09/03/1988        GW
291547  66010853060000   6591  0055  03/07/2006        QF
291548  56934560820000    442   661  05/01/1974        WD
291549  56928189020000   3946  0306  08/08/2002        GW
291550  56928189020000   5682  0038  12/01/2004        GW

       qualified_unqualified sales_price vacant_improved instrument_number  \
0                Unqualified     401,500          Vacant                SW
1                  Qualified     369,000        Improved                SW
2                Unqualified     401,500        Improved                SW
3                  Qualified     399,000        Improved                SW
4                Unqualified           0          Vacant                SW
...                      ...         ...             ...               ...
291546           Unqualified           0          Vacant                GW
291547           Unqualified      60,500          Vacant                QF
291548             Qualified      12,000          Vacant                WD
291549           Unqualified           0          Vacant                GW
291550           Unqualified           0          Vacant                GW

                  page_save
0       46707348030000.html
1       46707348030000.html
2       46707318010000.html
3       46707318010000.html
4       46707533450000.html
...                     ...
291546  56617851540000.html
291547  66010853060000.html
291548  56934560820000.html
291549  56928189020000.html
291550  56928189020000.html

[291551 rows x 10 columns]

In [6]:
df

,parcel_number,book,page,sale_date,deed_type,qualified_unqualified,sales_price,vacant_improved,instrument_number,page_save
0,46707348030000,15522,0001,09/24/2021,SW,Unqualified,"401,500",Vacant,SW,46707348030000.html
1,46707348030000,15810,0286,01/27/2022,SW,Qualified,"369,000",Improved,SW,46707348030000.html
2,46707318010000,15887,0077,03/03/2022,SW,Unqualified,"401,500",Improved,SW,46707318010000.html
3,46707318010000,16109,0163,07/11/2022,SW,Qualified,"399,000",Improved,SW,46707318010000.html
4,46707533450000,4992,0047,11/18/2003,SW,Unqualified,0,Vacant,SW,46707533450000.html
...,...,...,...,...,...,...,...,...,...,...
291546,56617851540000,682,0064,09/03/1988,GW,Unqualified,0,Vacant,GW,56617851540000.html
291547,66010853060000,6591,0055,03/07/2006,QF,Unqualified,"60,500",Vacant,QF,66010853060000.html
291548,56934560820000,442,661,05/01/1974,WD,Qualified,"12,000",Vacant,WD,56934560820000.html
291549,56928189020000,3946,0306,08/08/2002,GW,Unqualified,0,Vacant,GW,56928189020000.html
291550,56928189020000,5682,0038,12/01/2004,GW,Unqualified,0,Vacant,GW,56928189020000.html

In [7]:
df['book'].value_counts()

book
6893     1043
4971      669
LIFE      489
5101      465
4155      463
         ...
16657       1
E2002       1
30620       1
27690       1
269         1
Name: count, Length: 17639, dtype: int64

In [8]:
df['page'].value_counts()

page
0001    5730
0220    1377
0296    1312
0278    1188
0047    1163
        ...
0950       1
-269       1
198        1
7003       1
560        1
Name: count, Length: 1332, dtype: int64

In [9]:
df[df['page'] == '-269']

,parcel_number,book,page,sale_date,deed_type,qualified_unqualified,sales_price,vacant_improved,instrument_number,page_save
268266,56233289880000,1-SP,-269,09/04/2001,SP,Unqualified,0,Improved,SP,56233289880000.html

In [10]:
df['sale_date'].value_counts()

sale_date
06/30/2007    1035
11/07/2003     691
01/20/2004     491
12/20/2001     482
11/22/2002     477
              ...
11/19/1990       1
02/11/1983       1
04/06/1981       1
09/25/1974       1
12/15/1955       1
Name: count, Length: 12176, dtype: int64

# Case 4: Converted column to 'yyyy-mm-dd' format

In [11]:
df["sale_date"] = pd.to_datetime(df["sale_date"], errors="raise")

In [12]:
df['sale_date'].value_counts()

sale_date
2007-06-30    1035
2003-11-07     691
2004-01-20     491
2001-12-20     482
2002-11-22     477
              ...
1990-11-19       1
1983-02-11       1
1981-04-06       1
1974-09-25       1
1955-12-15       1
Name: count, Length: 12176, dtype: int64

In [13]:
df

,parcel_number,book,page,sale_date,deed_type,qualified_unqualified,sales_price,vacant_improved,instrument_number,page_save
0,46707348030000,15522,0001,2021-09-24,SW,Unqualified,"401,500",Vacant,SW,46707348030000.html
1,46707348030000,15810,0286,2022-01-27,SW,Qualified,"369,000",Improved,SW,46707348030000.html
2,46707318010000,15887,0077,2022-03-03,SW,Unqualified,"401,500",Improved,SW,46707318010000.html
3,46707318010000,16109,0163,2022-07-11,SW,Qualified,"399,000",Improved,SW,46707318010000.html
4,46707533450000,4992,0047,2003-11-18,SW,Unqualified,0,Vacant,SW,46707533450000.html
...,...,...,...,...,...,...,...,...,...,...
291546,56617851540000,682,0064,1988-09-03,GW,Unqualified,0,Vacant,GW,56617851540000.html
291547,66010853060000,6591,0055,2006-03-07,QF,Unqualified,"60,500",Vacant,QF,66010853060000.html
291548,56934560820000,442,661,1974-05-01,WD,Qualified,"12,000",Vacant,WD,56934560820000.html
291549,56928189020000,3946,0306,2002-08-08,GW,Unqualified,0,Vacant,GW,56928189020000.html
291550,56928189020000,5682,0038,2004-12-01,GW,Unqualified,0,Vacant,GW,56928189020000.html

In [14]:
df['deed_type'].value_counts()

deed_type
GW    149762
WD     42208
SW     38505
QC     10812
CV      9409
       ...
AC         1
WP         1
FG         1
U          1
HW         1
Name: count, Length: 115, dtype: int64

In [15]:
df['qualified_unqualified'].value_counts()

qualified_unqualified
Unqualified    160640
Qualified      128320
Name: count, dtype: int64

In [16]:
df

,parcel_number,book,page,sale_date,deed_type,qualified_unqualified,sales_price,vacant_improved,instrument_number,page_save
0,46707348030000,15522,0001,2021-09-24,SW,Unqualified,"401,500",Vacant,SW,46707348030000.html
1,46707348030000,15810,0286,2022-01-27,SW,Qualified,"369,000",Improved,SW,46707348030000.html
2,46707318010000,15887,0077,2022-03-03,SW,Unqualified,"401,500",Improved,SW,46707318010000.html
3,46707318010000,16109,0163,2022-07-11,SW,Qualified,"399,000",Improved,SW,46707318010000.html
4,46707533450000,4992,0047,2003-11-18,SW,Unqualified,0,Vacant,SW,46707533450000.html
...,...,...,...,...,...,...,...,...,...,...
291546,56617851540000,682,0064,1988-09-03,GW,Unqualified,0,Vacant,GW,56617851540000.html
291547,66010853060000,6591,0055,2006-03-07,QF,Unqualified,"60,500",Vacant,QF,66010853060000.html
291548,56934560820000,442,661,1974-05-01,WD,Qualified,"12,000",Vacant,WD,56934560820000.html
291549,56928189020000,3946,0306,2002-08-08,GW,Unqualified,0,Vacant,GW,56928189020000.html
291550,56928189020000,5682,0038,2004-12-01,GW,Unqualified,0,Vacant,GW,56928189020000.html

In [17]:
df['vacant_improved'].value_counts()

vacant_improved
Improved    200166
Vacant       88794
Name: count, dtype: int64

In [18]:
df['instrument_number'].value_counts()

instrument_number
GW    149762
WD     42208
SW     38505
QC     10812
CV      9409
       ...
AC         1
WP         1
FG         1
U          1
HW         1
Name: count, Length: 115, dtype: int64

In [19]:
df['sales_price'].value_counts()

sales_price
0          89394
25,000      1403
150,000     1318
30,000      1294
20,000      1289
           ...
43,600         1
93,800         1
77,395         1
141,874        1
75,606         1
Name: count, Length: 4218, dtype: int64

In [20]:
df['sales_price'] = df['sales_price'].replace({r',':''}, regex=True)

In [21]:
df['sales_price'].value_counts()

sales_price
0         89394
25000      1403
150000     1318
30000      1294
20000      1289
          ...
43600         1
93800         1
77395         1
141874        1
75606         1
Name: count, Length: 4218, dtype: int64

# Case 5: Replaced 0 and ',' with blank space and converted to float

In [22]:
df['sales_price'] = df['sales_price'].replace([0,0.0,'0'], np.nan).astype(float)

In [23]:
df['sales_price'].value_counts()

sales_price
25000.0      1403
150000.0     1318
30000.0      1294
20000.0      1289
50000.0      1255
             ...
207060.0        1
828000.0        1
96050.0         1
9412000.0       1
4250.0          1
Name: count, Length: 4217, dtype: int64

In [24]:
df

,parcel_number,book,page,sale_date,deed_type,qualified_unqualified,sales_price,vacant_improved,instrument_number,page_save
0,46707348030000,15522,0001,2021-09-24,SW,Unqualified,401500.0,Vacant,SW,46707348030000.html
1,46707348030000,15810,0286,2022-01-27,SW,Qualified,369000.0,Improved,SW,46707348030000.html
2,46707318010000,15887,0077,2022-03-03,SW,Unqualified,401500.0,Improved,SW,46707318010000.html
3,46707318010000,16109,0163,2022-07-11,SW,Qualified,399000.0,Improved,SW,46707318010000.html
4,46707533450000,4992,0047,2003-11-18,SW,Unqualified,NaN,Vacant,SW,46707533450000.html
...,...,...,...,...,...,...,...,...,...,...
291546,56617851540000,682,0064,1988-09-03,GW,Unqualified,NaN,Vacant,GW,56617851540000.html
291547,66010853060000,6591,0055,2006-03-07,QF,Unqualified,60500.0,Vacant,QF,66010853060000.html
291548,56934560820000,442,661,1974-05-01,WD,Qualified,12000.0,Vacant,WD,56934560820000.html
291549,56928189020000,3946,0306,2002-08-08,GW,Unqualified,NaN,Vacant,GW,56928189020000.html
291550,56928189020000,5682,0038,2004-12-01,GW,Unqualified,NaN,Vacant,GW,56928189020000.html

# Case 6: Placing the file

In [25]:
df.to_csv(r"D:\North Carolina\Cabarrus\Property\Cleaned_Data\us_nc_37025_data_prop_sales_silver_20251127.csv", index=False)
df

,parcel_number,book,page,sale_date,deed_type,qualified_unqualified,sales_price,vacant_improved,instrument_number,page_save
0,46707348030000,15522,0001,2021-09-24,SW,Unqualified,401500.0,Vacant,SW,46707348030000.html
1,46707348030000,15810,0286,2022-01-27,SW,Qualified,369000.0,Improved,SW,46707348030000.html
2,46707318010000,15887,0077,2022-03-03,SW,Unqualified,401500.0,Improved,SW,46707318010000.html
3,46707318010000,16109,0163,2022-07-11,SW,Qualified,399000.0,Improved,SW,46707318010000.html
4,46707533450000,4992,0047,2003-11-18,SW,Unqualified,NaN,Vacant,SW,46707533450000.html
...,...,...,...,...,...,...,...,...,...,...
291546,56617851540000,682,0064,1988-09-03,GW,Unqualified,NaN,Vacant,GW,56617851540000.html
291547,66010853060000,6591,0055,2006-03-07,QF,Unqualified,60500.0,Vacant,QF,66010853060000.html
291548,56934560820000,442,661,1974-05-01,WD,Qualified,12000.0,Vacant,WD,56934560820000.html
291549,56928189020000,3946,0306,2002-08-08,GW,Unqualified,NaN,Vacant,GW,56928189020000.html
291550,56928189020000,5682,0038,2004-12-01,GW,Unqualified,NaN,Vacant,GW,56928189020000.html